//--------------------------------------------- 1) Definir Las Variables Correspondintes---------------------------------------------
var opt_RENGLON_011 = new Array ("-",
"011-ASESOR PROFESIONAL ESPECIALIZADO II",
"011-ASESOR PROFESIONAL ESPECIALIZADO IV",
"011-ASISTENTE PROFESIONAL I",
"011-ASISTENTE PROFESIONAL II",
"011-ASISTENTE PROFESIONAL III",
"011-ASISTENTE PROFESIONAL IV",
"011-ASISTENTE PROFESIONAL JEFE",
"011-DIRECTOR DE AREA DE SALUD",
"011-DIRECTOR DE DISPENSARIO I 4 HRS.",
"011-DIRECTOR DE HOSPITAL DISTRITAL",
"011-DIRECTOR DE HOSPITAL I",
"011-DIRECTOR DE HOSPITAL I 4 HRS.",
"011-DIRECTOR DE HOSPITAL II",
"011-DIRECTOR REGIONAL",
"011-DIRECTOR TECNICO II",
"011-JEFE DE AREA",
"011-JEFE TECNICO I",
"011-JEFE TECNICO II",
"011-JEFE TECNICO PROFESIONAL I",
"011-JEFE TECNICO PROFESIONAL I 4 HRS.",
"011-JEFE TECNICO PROFESIONAL II",
"011-JEFE TECNICO PROFESIONAL III",
"011-OFICIAL MAYOR",
"011-OFICINISTA I",
"011-OFICINISTA II",
"011-OFICINISTA III",
"011-OFICINISTA IV",
"011-PARAMEDICO I",
"011-PARAMEDICO I 2 HRS.",
"011-PARAMEDICO I 3 HRS.",
"011-PARAMEDICO I 4 HRS.",
"011-PARAMEDICO II",
"011-PARAMEDICO III",
"011-PARAMEDICO III 4 HRS.",
"011-PARAMEDICO IV",
"011-PARAMEDICO IV 4 HRS.",
"011-PARAMEDICO JEFE I",
"011-PARAMEDICO JEFE II",
"011-PARAMEDICO JEFE III",
"011-PROFESIONAL I",
"011-PROFESIONAL I 2 HRS.",
"011-PROFESIONAL I 3 HRS.",
"011-PROFESIONAL I 4 HRS.",
"011-PROFESIONAL I 6 HRS.",
"011-PROFESIONAL II",
"011-PROFESIONAL II 1 HRA.",
"011-PROFESIONAL II 2 HRS.",
"011-PROFESIONAL II 4 HRS.",
"011-PROFESIONAL II 6 HRS.",
"011-PROFESIONAL III",
"011-PROFESIONAL III 1 HRA.",
"011-PROFESIONAL III 2 HRS.",
"011-PROFESIONAL III 4 HRS.",
"011-PROFESIONAL III 6 HRS.",
"011-PROFESIONAL JEFE I",
"011-PROFESIONAL JEFE I 2 HRS.",
"011-PROFESIONAL JEFE I 3 HRS.",
"011-PROFESIONAL JEFE I 4 HRS.",
"011-PROFESIONAL JEFE I 6 HRS.",
"011-PROFESIONAL JEFE II",
"011-PROFESIONAL JEFE II 2 HRS.",
"011-PROFESIONAL JEFE II 3 HRS.",
"011-PROFESIONAL JEFE II 4 HRS.",
"011-PROFESIONAL JEFE II 6 HRS.",
"011-PROFESIONAL JEFE III",
"011-PROFESIONAL JEFE III 2 HRS.",
"011-PROFESIONAL JEFE III 3 HRS.",
"011-PROFESIONAL JEFE III 4 HRS.",
"011-PROFESIONAL JEFE III 6 HRS.",
"011-SECRETARIO EJECUTIVO I",
"011-SECRETARIO EJECUTIVO II",
"011-SECRETARIO EJECUTIVO III",
"011-SECRETARIO EJECUTIVO IV",
"011-SECRETARIO EJECUTIVO MINISTERIAL I",
"011-SECRETARIO EJECUTIVO MINISTERIAL II",
"011-SECRETARIO EJECUTIVO V",
"011-SECRETARIO OFICINISTA",
"011-SUB DIRECTOR DE HOSPITAL I",
"011-SUB DIRECTOR DE HOSPITAL II",
"011-SUB DIRECTOR GENERAL",
"011-SUBDIRECTOR TECNICO II",
"011-TECNICO EN INFORMATICA I",
"011-TECNICO I",
"011-TECNICO II",
"011-TECNICO III",
"011-TECNICO III 4 HRS.",
"011-TECNICO III 6 HRS.",
"011-TECNICO PROFESIONAL I",
"011-TECNICO PROFESIONAL I 4 HRS.",
"011-TECNICO PROFESIONAL I 6 HRS.",
"011-TECNICO PROFESIONAL II",
"011-TECNICO PROFESIONAL II 1 HRA.",
"011-TECNICO PROFESIONAL III",
"011-TECNICO PROFESIONAL INFORMATICA III",
"011-TRABAJADOR ESPECIALIZADO I",
"011-TRABAJADOR ESPECIALIZADO I 6 HRS.",
"011-TRABAJADOR ESPECIALIZADO II",
"011-TRABAJADOR ESPECIALIZADO III",
"011-TRABAJADOR ESPECIALIZADO JEFE I",
"011-TRABAJADOR ESPECIALIZADO JEFE II",
"011-TRABAJADOR OPERATIVO II",
"011-TRABAJADOR OPERATIVO III",
"011-TRABAJADOR OPERATIVO IV",
"011-TRABAJADOR OPERATIVO JEFE I",
"011-TRABAJADOR OPERATIVO JEFE II",
"011-VICEMINISTRO",
"011-MINISTRO DE SALUD PUBLICA Y A.S.",
"011-ASESOR PROFESIONAL ESPEC I 6 HRS",
"011-PARAMEDICO II 4 HRS.",
"011-PARAMEDICO IV 6 HRS.",
"011-PARAMEDICO JEFE I 4 HRS.",
"011-PEÓN",
"011-PROFESIONAL III 3 HRS.",
"011-PROFESIONAL III 4 HORAS",
"011-PROFESIONAL JEFE III 4 HRS.",
"011-TECNICO I 6 HRS.",
"011-TECNICO PROFESIONAL  EN INFORMATICA II",
"011-TECNICO PROFESIONAL II 6 HRS.",
"011-TRABAJADOR ESPECIALIZADO II 4 HRS.",
"011-TRABAJADOR ESPECIALIZADO III 4 HRS",
"011-TRABAJADOR ESPECIALIZADO III 6 HRS",);

var opt_RENGLON_021 = new Array ("-", 
"021-ANALISTA DE CONTABILIDAD",
"021-ANALISTA DE PRESUPUESTO",
"021-ENCARGADO DE COMPRAS",
"021-ENCARGADO DE PRESUPUESTO",
"021-ENCARGADO DE TESORERÍA",
"021-JEFE ADMINISTRATIVO",
"021-JEFE DE GESTIÓN DE PROGRAMAS, PROYECTOS Y COOPERACIÓN INTERNACIONAL",
"021-JEFE DE INGENIERÍA DE PROYECTOS",
"021-JEFE DE RESIDENTE",
"021-JEFE DE SEGUIMIENTO DE INGENIERÍA",
"021-MÉDICO DE URGENCIA",
"021-MÉDICO RESIDENTE I",
"021-MÉDICO RESIDENTE II",
"021-MÉDICO RESIDENTE III",
"021-MÉDICO RESIDENTE IV",
"021-MÉDICO TURNISTA 4 HORAS",
"021-PROFESIONAL AMBIENTAL",
"021-PROFESIONAL EN ADMINISTRACIÓN DE PROGRAMAS Y PROYECTOS",
"021-PROFESIONAL EN INGENIERÍA INDUSTRIAL",
"021-PROFESIONAL II",
"021-PROFESIONAL JURÍDICO",
"021-SECRETARIA",
"021-SECRETARIA EJECUTIVA",
"021-JEFE FINANCIERO",
"021-TÉCNICO DE ALMACÉN",
"021-ANALISTA DE TESORERÍA",
"021-PROFESIONAL EN INGENIERÍA CIVIL",
"021-PROFESIONAL EN INGENIERÍA MECÁNICA",
"021-PROFESIONAL EN PROGRAMAS, PROYECTOS Y COOPERACIÓN INTERNACIONAL",
"021-PROFESIONAL EN ARQUITECTURA",
"021-MENSAJERO",
"021-CONSERJE",
"021-ENCARGADO DE INVENTARIOS",
"021-PILOTO",
"021-TÉCNICO DE INVENTARIOS",
"021-ENCARGADO DE CONTABILIDAD",
"021-ENCARGADO DE ALMACEN",
"021-ANALISTA DE COMPRAS",
"021-PROFESIONAL EN SERVICIOS DE SALUD",
"021-PROFESIONAL EN INGENIERÍA ELÉCTRICA",
"021-PROFESIONAL EN INGENIERÍA SANITARIA");

var opt_RENGLON_022 = new Array ("-",
"022-DIRECTOR EJECUTIVO I",
"022-DIRECTOR EJECUTIVO II",
"022-OFICINISTA IV",
"022-SUBDIRECTOR EJECUTIVO I",
"022-SUBDIRECTOR EJECUTIVO II",
"022-TECNICO I",
"022-TECNICO III",
"022-PROFESIONAL II",
"022-TRABAJADOR ESPECIALIZADO II");


var opt_RENGLON_031 = new Array ("-", 
"031-ALBAÑIL I",
"031-AUXILIAR DE BODEGA",
"031-AUXILIAR DE OPERACIÓN DE ",
"031-AUXILIAR MISCELÁNEO",
"031-BODEGUERO IV",
"031-CARPINTERO I",
"031-COCINERO",
"031-CONDUCTOR DE VEHÍCULOS ",
"031-CONSERJE",
"031-ELECTRICISTA I",
"031-FONTANERO I",
"031-HERRERO I",
"031-LAVANDERA I",
"031-MECÁNICO AUTOMOTRÍZ I",
"031-MENSAJERO I",
"031-OPERADOR DE EQUIPO DE ",
"031-PEÓN VIGILANTE I",
"031-PEÓN VIGILANTE II",
"031-PEÓN VIGILANTE V",
"031-PEÓN VIVANDERA",
"031-PILOTO I VEHÍCULOS ",
"031-PINTOR I",
"031-TRABAJADOR ECÓNOMO",
"031-ALBAÑIL III",
"031-ALBAÑIL IV",
"031-ALBAÑIL V",
"031-AUXILIAR DE ALBAÑILERÍA",
"031-AUXILIAR DE CAPORAL",
"031-AUXILIAR DE CARPINTERÍA",
"031-AUXILIAR DE ELECTRICIDAD",
"031-AUXILIAR DE FONTANERÍA",
"031-AUXILIAR DE HERRERÍA",
"031-AUXILIAR DE MECÁNICA",
"031-AUXILIAR DE OPERACIÓN DE MAQUINARIA Y EQUIPO",
"031-BODEGUERO I",
"031-BODEGUERO II",
"031-BODEGUERO III",
"031-CONDUCTOR DE VEHÍCULOS LIVIANOS",
"031-CONDUCTOR DE VEHÍCULOS PESADOS",
"031-ELECTRICISTA II",
"031-ELECTRICISTA III",
"031-ENCARGADO I DE OPERACIONES DE MAQUINARIA Y EQUIPO",
"031-JARDINERO I",
"031-JARDINERO II",
"031-LAVANDERA II",
"031-MAESTRO DE OBRAS",
"031-MECÁNICO AUTOMOTRÍZ II",
"031-MECÁNICO AUTOMOTRÍZ III",
"031-MENSAJERO II",
"031-OPERADOR DE EQUIPO",
"031-OPERADOR DE EQUIPO DE ESTADÍSTICA",
"031-OPERADOR DE MAQUINARIA",
"031-PEÓN",
"031-PEÓN VIGILANTE III",
"031-PEÓN VIGILANTE IV",
"031-PILOTO I VEHÍCULOS LIVIANOS",
"031-PILOTO II VEHÍCULOS PESADOS",
"031-Puesto Oficial",
"031-SASTRE",
"031-TRABAJADOR  VIVANDERA",
"031-TRABAJADOR DE MANTENIMIENTO DE TELECOMUNICACIONES I");

// ---------------------------------------------2) crear una funcion que permita ejecutar el cambio dinamico---------------------------------------------

function cambia(){
    var Renglon;
    //Se toma el vamor de la "cosa seleccionada"
    Renglon = document.formulario1.Renglon[document.formulario1.Renglon.selectedIndex].value;
    //se chequea si la "cosa" esta definida
    if(Renglon!=0){
        //selecionamos las cosas Correctas
        mis_opts=eval("opt_" + Renglon);
        //se calcula el numero de cosas
        num_opts=mis_opts.length;
        //marco el numero de opt en el select
        document.formulario1.opt.length = num_opts;
        //para cada opt del array, la pongo en el select
        for(i=0; i<num_opts; i++){
            document.formulario1.opt.options[i].value=mis_opts[i];
            document.formulario1.opt.options[i].text=mis_opts[i];
        }
        }else{
            //si no habia ninguna opt seleccionada, elimino las cosas del select
            document.formulario1.opt.length = 1;
            //ponemos un guion en la unica opt que he dejado
            document.formulario1.opt.options[0].value="-";
            document.formulario1.opt.options[0].text="-";
        }
        //hacer un reset de las opts
        document.formulario1.opt.options[0].selected = true;
        
    }


//--------------------------------------------- 1) Definir Las Variables Especialidad Correspondintes---------------------------------------------


var Especialidad_RENGLON_011 = new Array ("-",
"ACTIVIDADES PARAMEDICAS",
"ACTIVIDADES RELIGIOSAS",
"ACTIVIDADES SECRETARIALES",
"ADIESTRAMIENTO",
"ADMINISTRACION",
"ADMINISTRACION ALIMENTARIA",
"ADMINISTRACION AREAS DE SALUD",
"ADMINISTRACION DE HOSPITALES",
"ADMINISTRACION DE PERSONAL",
"ADMINISTRACION DE RECURSOS HUMANOS",
"ALBAÑILERIA",
"ALIMENTOS",
"ALMACENAJE",
"ANESTESIOLOGIA",
"ARCHIVOLOGIA",
"ARQUITECTURA",
"ARTES GRAFICAS",
"ASESORIA JURIDICA",
"ASESORIA TECNICA",
"AUDITORIA",
"BARBERIA",
"BIBLIOTECOLOGIA",
"BIOLOGIA",
"CARDIOLOGIA",
"CARDIOLOGÍA PEDIÁTRICA",
"CARPINTERIA",
"CATASTRO",
"CIRUGIA CARDIOVASCULAR TORAX",
"CIRUGÍA DE PIÉ",
"CIRUGIA GENERAL",
"CIRUGIA ORAL Y MAXILOFACIAL",
"CIRUGIA PEDIATRICA",
"CIRUGIA PLASTICA",
"CITOLOGIA",
"COMPRAS Y SUMINISTROS",
"COMPUTACION",
"CONDUCCION DE VEHICULOS",
"CONSERJERIA",
"CONSTRUCCION CIVIL",
"CONSTRUCCION Y MANTENIMIENTO DE EDIFICIOS",
"CONTABILIDAD",
"CORTE Y CONFECCION",
"CUIDADO DE NIÑOS",
"CUIDADOS INTENSIVOS",
"DERECHO",
"DERMATOLOGIA",
"DIBUJO",
"DOCUMENTACION TECNICA",
"ECONOMIA",
"EDUCACION",
"EDUCACION ESPECIAL",
"ELECTRICIDAD",
"ELECTRONICA",
"ENDOCRINOLOGIA",
"ENFERMERIA",
"ENFERMERIA AUXILIAR",
"EPIDEMIOLOGIA",
"ESTADISTICA",
"FARMACIA",
"FINANZAS",
"FISIOTERAPIA",
"FONOAUDIOLOGIA",
"FOTOGRABACION",
"GASTROENTEROLOGIA",
"GERIATRIA",
"GINECOLOGIA Y OBSTETRICIA",
"HEMATOLOGÍA PEDIÁTRICA",
"HERRERIA",
"HIDROGEOLOGIA",
"ILUSTRACION",
"IMPRESION",
"INFECTOLOGIA",
"INFECTOLOGIA PEDIATRICA",
"INFORMATICA",
"INGENIERIA CIVIL",
"INGENIERIA ELECTRICA",
"INGENIERIA INDUSTRIAL",
"INGENIERIA MECANICA",
"INGENIERIA SANITARIA",
"INHALOTERAPIA",
"INSPECCION SANITARIA ALIMENTOS PECUARIOS",
"INSTRUCCION VOCACIONAL",
"JARDINERIA",
"LABORATORIO",
"LAVANDERIA",
"MALARIA",
"MANEJO DE FONDOS",
"MATERIAL DIDACTICO",
"MECANICA",
"MEDICINA",
"MEDICINA CRITICA Y CUIDADOS INTENSIVOS PEDIATRICOS",
"MEDICINA EN GUARDIA Y TURNO",
"MEDICINA FISICA Y REHABILITACION",
"MEDICINA FORENSE",
"MEDICINA INTERNA",
"MENSAJERIA",
"MICROBIOLOGIA",
"NECROPSIAS",
"NEFROLOGIA",
"NEFROLOGIA PEDIATRICA",
"NEONATOLOGÍA",
"NEUMOLOGIA",
"NEUMOLOGÍA PEDIÁTRICA",
"NEUROCIRUGIA",
"NEUROFISIOLOGÍA",
"NEUROLOGIA",
"NEUROPSICOLOGÍA",
"NUTRICION",
"ODONTOLOGIA",
"ODONTOLOGÍA PEDIÁTRICA",
"OFICINA",
"OFTALMOLOGIA",
"ONCOLOGÍA GINECOLÓGICA",
"ONCOLOGIA MEDICA",
"ONCOLOGIA QUIRURGICA",
"OPERACION AUTOCLAVE",
"OPERACION DE MAQUINARIA PESADA",
"OPERACION DE RADIO",
"OPERACION EQUIPO PROYECCION",
"OPERACION PLANTA ELECTRICA",
"OPERACION Y MANTENIMIENTO  MAQUINARIA Y EQUIPO",
"ORTESIS",
"ORTOPEDIA Y TRAUMATOLOGIA",
"OTORRINOLARINGOLOGIA",
"PANADERIA",
"PATOLOGIA",
"PEDIATRIA",
"PERIODISMO",
"PINTURA",
"PLANIFICACION",
"PREPARACION DE ALIMENTOS",
"PREPARACION Y SERVICIOS DE ALIMENTOS",
"PRESUPUESTO",
"PREVENCION DE ENFERMEDADES ENDEMICAS",
"PROMOCION SOCIAL",
"PSICOLOGIA",
"PSICOLOGÍA FORENSE",
"PSIQUIATRIA GENERAL",
"PSIQUIATRIA PEDIATRICA",
"QUIMICA",
"QUÍMICA FARMACÉUTICA",
"QUIMICO-BIOLOGO",
"RADIOLOGIA",
"RELACIONES PUBLICAS",
"REPARACION DE ACUMULADORES",
"RESGUARDO Y VIGILANCIA",
"REUMATOLOGIA",
"ROPERIA",
"SALUD PUBLICA",
"SALUD RURAL",
"SANEAMIENTO AMBIENTAL",
"SASTRERIA",
"SEGURIDAD PERSONAL",
"SIN ESPECIALIDAD",
"SOLDADURA",
"TECNICAS AUDIOVISUALES",
"TERAPIA DEL LENGUAJE",
"TERAPIA OCUPACIONAL",
"TOPOGRAFIA",
"TRABAJO SOCIAL",
"UROGINECOLOGÍA",
"UROLOGIA",
"VETERINARIA");


var Especialidad_RENGLON_021 = new Array ("-",
"ANESTESIOLOGIA",
"CARDIOLOGIA",
"CIRUGIA CARDIOVASCULAR TORAX",
"CIRUGIA GENERAL",
"CIRUGIA ORAL Y MAXILOFACIAL",
"CIRUGIA PEDIATRICA",
"CONSERJERIA",
"CUIDADOS INTENSIVOS",
"DERMATOLOGIA",
"ENFERMERIA",
"ENFERMERIA AUXILIAR",
"FISIOTERAPIA",
"GASTROENTEROLOGIA",
"GINECOLOGIA Y OBSTETRICIA",
"HEMATO-ONCOLOGÍA-PEDIÁTICA",
"INFECTOLOGIA",
"INFECTOLOGIA PEDIATRICA",
"LABORATORIO",
"LAVANDERIA",
"MEDICINA",
"MEDICINA CRITICA Y CUIDADOS INTENSIVOS PEDIATRICOS",
"MEDICINA EN GUARDIA Y TURNO",
"MEDICINA FISICA Y REHABILITACION",
"MEDICINA INTERNA",
"MISCELANEOS",
"NEFROLOGIA",
"NEFROLOGIA PEDIATRICA",
"NEONATOLOGÍA",
"NEUMOLOGIA",
"NEUROCIRUGIA",
"NEUROFISIOLOGÍA",
"NEUROLOGIA",
"NUTRICION",
"OFTALMOLOGIA",
"ORTOPEDIA Y TRAUMATOLOGIA",
"PATOLOGIA",
"PEDIATRIA",
"PREPARACION Y SERVICIOS DE ALIMENTOS",
"PSICOLOGIA",
"PSIQUIATRIA GENERAL",
"PSIQUIATRIA INFANTO-JUVENIL",
"QUÍMICA FARMACÉUTICA",
"QUIMICO-BIOLOGO",
"RADIOLOGIA",
"REUMATOLOGIA",
"SIN ESPECIALIDAD",
"TERAPIA RESPIRATORIA",
"TRABAJO SOCIAL",
"UROLOGIA");

var Especialidad_RENGLON_022 = new Array ("-", "ACTIVIDADES PARAMEDICAS", "ADMINISTRACIÓN", "ALMACENAJE", "CONTABILIDAD", "MANEJO DE FONDOS", "PRESUPUESTO", "SIN ESPECIALIDAD");

var Especialidad_RENGLON_031 = new Array ("SIN ESPECIALIDAD");


// ---------------------------------------------2) crear una funcion que permita ejecutar el cambio dinamico---------------------------------------------
function cambias(){
    var Renglon;
    //Se toma el vamor de la "cosa seleccionada"
    Renglon = document.formulario1.Renglon[document.formulario1.Renglon.selectedIndex].value;
    //se chequea si la "cosa" esta definida
    if(Renglon!=0){
        //selecionamos las cosas Correctas
        mis_opts=eval("Especialidad_" + Renglon);
        //se calcula el numero de cosas
        num_opts=mis_opts.length;
        //marco el numero de opt en el select
        document.formulario1.Especialidad.length = num_opts;
        //para cada opt del array, la pongo en el select
        for(i=0; i<num_opts; i++){
            document.formulario1.Especialidad.options[i].value=mis_opts[i];
            document.formulario1.Especialidad.options[i].text=mis_opts[i];
        }
        }else{
            //si no habia ninguna opt seleccionada, elimino las cosas del select
            document.formulario1.opt.length = 1;
            //ponemos un guion en la unica opt que he dejado
            document.formulario1.opt.options[0].value="-";
            document.formulario1.opt.options[0].text="-";
        }
        //hacer un reset de las opts
        document.formulario1.Especialidad.options[0].selected = true;
        
    }




//--------------------------------------------- 1) Definir Las Variables Departamento y Municiío Correspondintes---------------------------------------------
var Municipio_GUATEMALA = new Array("-",
"GUATEMALA",
"SANTA CATARINA PINULA",
"SAN JOSÉ PINULA",
"SAN JOSÉ DEL GOLFO",
"PALENCIA",
"CHINAUTLA",
"SAN PEDRO AYAMPUC",
"MIXCO",
"SAN PEDRO SACATEPÉQUEZ",
"SAN JUAN SACATEPÉQUEZ",
"SAN RAYMUNDO",
"CHUARRANCHO",
"FRAIJANES",
"AMATITLÁN",
"VILLA NUEVA",
"VILLA CANALES",
"PETAPA");


var Municipio_EL_PROGRESO = new Array("-",
"GUASTATOYA",
"MORAZÁN",
"SAN AGUSTÍN ACASAGUASTLÁN",
"SAN CRISTÓBAL ACASAGUASTLÁN",
"EL JÍCARO",
"SANSARE",
"SANARATE",
"SAN ANTONIO LA PAZ");


var Municipio_SACATEPÉQUEZ = new Array("-",
"ANTIGUA GUATEMALA",
"JOCOTENANGO",
"PASTORES",
"SUMPANGO",
"SANTO DOMINGO XENACOJ",
"SANTIAGO SACATEPÉQUEZ",
"SAN BARTOLOMÉ MILPAS ALTAS",
"SAN LUCAS SACATEPÉQUEZ",
"SANTA LUCÍA MILPAS ALTAS",
"MAGDALENA MILPAS ALTAS",
"SANTA MARÍA DE JESÚS",
"CIUDAD VIEJA",
"SAN MIGUEL DUEÑAS",
"ALOTENANGO",
"SAN ANTONIO AGUAS CALIENTES",
"SANTA CATARINA BARAHONA");


var Municipio_CHIMALTENANGO = new Array("-",
"CHIMALTENANGO",
"SAN JOSÉ POAQUIL",
"SAN MARTÍN JILOTEPEQUE",
"COMALAPA",
"SANTA APOLONIA",
"TECPÁN GUATEMALA",
"PATZÚN",
"POCHUTA",
"PATZICÍA",
"SANTA CRUZ BALANYÁ",
"ACATENANGO",
"YEPOCAPA",
"SAN ANDRÉS ITZAPA",
"PARRAMOS",
"ZARAGOZA",
"EL TEJAR");


var Municipio_ESCUINTLA = new Array("-",
"ESCUINTLA",
"SANTA LUCÍA COTZUMALGUAPA",
"LA DEMOCRACIA",
"SIQUINALÁ",
"MASAGUA",
"TIQUISATE",
"LA GOMERA",
"GUANAGAZAPA",
"SAN JOSÉ",
"IZTAPA",
"PALÍN",
"SAN VICENTE PACAYA",
"NUEVA CONCEPCIÓN");


var Municipio_SANTA_ROSA = new Array("-",
"CUILAPA",
"BARBERENA",
"SANTA ROSA DE LIMA",
"CASILLAS",
"SAN RAFAEL LAS FLORES",
"ORATORIO",
"SAN JUAN TECUACO",
"CHIQUIMULILLA",
"TAXISCO",
"SANTA MARÍA IXHUATÁN",
"GUAZACAPÁN",
"SANTA CRUZ NARANJO",
"PUEBLO NUEVO VIÑAS",
"NUEVA SANTA ROSA");


var Municipio_SOLOLÁ = new Array("-",
"SOLOLÁ",
"SAN JOSÉ CHACAYÁ",
"SANTA MARÍA VISITACIÓN",
"SANTA LUCÍA UTATLÁN",
"NAHUALÁ",
"SANTA CATARINA IXTAHUACÁN",
"SANTA CLARA LA LAGUNA",
"CONCEPCIÓN",
"SAN ANDRÉS SEMETABAJ",
"PANAJACHEL",
"SANTA CATARINA PALOPÓ",
"SAN ANTONIO PALOPÓ",
"SAN LUCAS TOLIMÁN",
"SANTA CRUZ LA LAGUNA",
"SAN PABLO LA LAGUNA",
"SAN MARCOS LA LAGUNA",
"SAN JUAN LA LAGUNA",
"SAN PEDRO LA LAGUNA",
"SANTIAGO ATITLÁN");


var Municipio_TOTONICAPÁN = new Array("-",
"TOTONICAPÁN",
"SAN CRISTÓBAL TOTONICAPÁN",
"SAN FRANCISCO EL ALTO",
"SAN ANDRÉS XECUL",
"MOMOSTENANGO",
"SANTA MARÍA CHIQUIMULA",
"SANTA LUCÍA LA REFORMA",
"SAN BARTOLO");


var Municipio_QUETZALTENANGO = new Array("-",
"QUETZALTENANGO",
"SALCAJÁ",
"OLINTEPEQUE",
"SAN CARLOS SIJA",
"SIBILIA",
"CABRICÁN",
"CAJOLÁ",
"SAN MIGUEL SIGUILÁ",
"OSTUNCALCO",
"SAN MATEO",
"CONCEPCIÓN CHIQUIRICHAPA",
"SAN MARTÍN SACATEPÉQUEZ",
"ALMOLONGA",
"CANTEL",
"HUITÁN",
"ZUNIL",
"COLOMBA",
"SAN FRANCISCO LA UNIÓN",
"EL PALMAR",
"COATEPEQUE",
"GÉNOVA",
"FLORES COSTA CUCA",
"LA ESPERANZA",
"PALESTINA DE LOS ALTOS");


var Municipio_SUCHITEPÉQUEZ = new Array("-",
"MAZATENANGO",
"CUYOTENANGO",
"SAN FRANCISCO ZAPOTITLÁN",
"SAN BERNARDINO",
"SAN JOSÉ EL IDOLO",
"SANTO DOMINGO SUCHITEPÉQUEZ",
"SAN LORENZO",
"SAMAYAC",
"SAN PABLO JOCOPILAS",
"SAN ANTONIO SUCHITEPÉQUEZ",
"SAN MIGUEL PANÁN",
"SAN GABRIEL",
"CHICACAO",
"PATULUL",
"SANTA BÁRBARA",
"SAN JUAN BAUTISTA",
"SANTO TOMÁS LA UNIÓN",
"ZUNILITO",
"PUEBLO NUEVO",
"RÍO BRAVO",
"SAN JOSÉ LA MÁQUINA");


var Municipio_RETALHULEU = new Array("-",
"RETALHULEU",
"SAN SEBASTIÁN",
"SANTA CRUZ MULUÁ",
"SAN MARTÍN ZAPOTITLÁN",
"SAN FELIPE",
"SAN ANDRÉS VILLA SECA",
"CHAMPERICO",
"NUEVO SAN CARLOS",
"EL ASINTAL");


var Municipio_SAN_MARCOS = new Array("-",
"SAN MARCOS",
"SAN PEDRO SACATEPÉQUEZ",
"SAN ANTONIO SACATEPÉQUEZ",
"COMITANCILLO",
"SAN MIGUEL IXTAHUACÁN",
"CONCEPCIÓN TUTUAPA",
"TACANÁ",
"SIBINAL",
"TAJUMULCO",
"TEJUTLA",
"SAN RAFAEL PIÉ DE LA CUESTA",
"NUEVO PROGRESO",
"EL TUMBADOR",
"EL RODEO",
"MALACATÁN",
"CATARINA",
"AYUTLA",
"OCÓS",
"SAN PABLO",
"EL QUETZAL",
"LA REFORMA",
"PAJAPITA",
"IXCHIGUÁN",
"SAN JOSÉ OJETENÁN",
"SAN CRISTÓBAL CUCHO",
"SIPACAPA",
"ESQUIPULAS PALO GORDO",
"RÍO BLANCO",
"SAN LORENZO",
"LA BLANCA");


var Municipio_HUEHUETENANGO = new Array("-",
"HUEHUETENANGO",
"CHIANTLA",
"MALACATANCITO",
"CUILCO",
"NENTÓN",
"SAN PEDRO NECTA",
"JACALTENANGO",
"SOLOMA",
"IXTAHUACÁN",
"SANTA BÁRBARA",
"LA LIBERTAD",
"LA DEMOCRACIA",
"SAN MIGUEL ACATÁN",
"SAN RAFAEL LA INDEPENDENCIA",
"TODOS SANTOS CUCHUMATÁN",
"SAN JUAN ATITÁN",
"SANTA EULALIA",
"SAN MATEO IXTATÁN",
"COLOTENANGO",
"SAN SEBASTIÁN HUEHUETENANGO",
"TECTITÁN",
"TETAPAN",
"CONCEPCIÓN HUISTA",
"SAN JUAN IXCOY",
"SAN ANTONIO HUISTA",
"SAN SEBASTIÁN COATÁN",
"BARILLAS",
"AGUACATÁN",
"SAN RAFAEL PETZAL",
"SAN GASPAR IXCHIL",
"SANTIAGO CHIMALTENANGO",
"SANTA ANA HUISTA",
"UNIÓN CANTINIL");


var Municipio_QUICHÉ = new Array("-",
"SANTA CRUZ DEL QUICHÉ",
"CHICHÉ",
"CHINIQUE",
"ZACUALPA",
"CHAJUL",
"CHICHICASTENANGO",
"PATZITÉ",
"SAN ANTONIO ILOTENANGO",
"SAN PEDRO JOCOPILAS",
"CUNÉN",
"SAN JUAN COTZAL",
"JOYABAJ",
"NEBAJ",
"SAN ANDRÉS SAJCABAJÁ",
"USPANTÁN",
"SACAPULAS",
"SAN BARTOLOMÉ JOCOTENANGO",
"CANILLÁ",
"CHICAMÁN",
"IXCÁN",
"PACHALUM");


var Municipio_BAJA_VERAPAZ = new Array("-",
"SALAMÁ",
"SAN MIGUEL CHICAJ",
"RABINAL",
"CUBULCO",
"GRANADOS",
"EL CHOL",
"SAN JERÓNIMO",
"PURULHÁ");


var Municipio_ALTA_VERAPAZ = new Array("-",
"COBÁN",
"SANTA CRUZ VERAPAZ",
"SAN CRISTÓBAL VERAPAZ",
"TACTIC",
"TAMAHÚ",
"TUCURÚ",
"PANZÓS",
"SENAHÚ",
"SAN PEDRO CARCHÁ",
"SAN JUAN CHAMELCO",
"LANQUÍN",
"CAHABÓN",
"CHISEC",
"CHAHAL",
"FRAY BARTOLOMÉ DE LAS CASAS",
"SANTA CATALINA LA TINTA",
"RAXRUHÁ");


var Municipio_PETÉN = new Array("-",
"FLORES",
"SAN JOSÉ",
"SAN BENITO",
"SAN ANDRÉS",
"LA LIBERTAD",
"SAN FRANCISCO",
"SANTA ANA",
"DOLORES",
"SAN LUIS",
"SAYAXCHÉ",
"MELCHOR DE MENCOS",
"POPTÚN",
"LAS CRUCES",
"EL CHAL");


var Municipio_IZABAL = new Array("-",
"PUERTO BARRIOS",
"LIVINGSTON",
"EL ESTOR",
"MORALES",
"LOS AMATES");


var Municipio_ZACAPA = new Array("-",
"ZACAPA",
"ESTANZUELA",
"RÍO HONDO",
"GUALÁN",
"TECULUTÁN",
"USUMATLÁN",
"CABAÑAS",
"SAN DIEGO",
"LA UNIÓN",
"HUITÉ",
"SAN JORGE");


var Municipio_CHIQUIMULA = new Array("-",
"CHIQUIMULA",
"SAN JOSÉ LA ARADA",
"SAN JUAN ERMITA",
"JOCOTÁN",
"CAMOTÁN",
"OLOPA",
"ESQUIPULAS",
"CONCEPCIÓN LAS MINAS",
"QUETZALTEPEQUE",
"SAN JACINTO",
"IPALA");


var Municipio_JALAPA = new Array("-",
"JALAPA",
"SAN PEDRO PINULA",
"SAN LUIS JILOTEPEQUE",
"SAN MANUEL CHAPARRÓN",
"SAN CARLOS ALZATATE",
"MONJAS",
"MATAQUESCUINTLA");


var Municipio_JUTIAPA = new Array("-",
"JUTIAPA",
"EL PROGRESO",
"SANTA CATARINA MITA",
"AGUA BLANCA",
"ASUNCIÓN MITA",
"YUPILTEPEQUE",
"ATESCATEMPA",
"JEREZ",
"EL ADELANTO",
"ZAPOTITLÁN",
"COMAPA",
"JALPATAGUA",
"CONGUACO",
"MOYUTA",
"PASACO",
"SAN JOSÉ ACATEMPA",
"QUESADA");



// ---------------------------------------------2) crear una funcion que permita ejecutar el cambio dinamico---------------------------------------------

function cambiasss(){
    var Departamento;
    //Se toma el vamor de la "cosa seleccionada"
    Departamento = document.formulario1.Departamento[document.formulario1.Departamento.selectedIndex].value;
    //se chequea si la "cosa" esta definida
    if(Departamento!=0){
        //selecionamos las cosas Correctas
        mis_opts=eval("Municipio_" + Departamento);
        //se calcula el numero de cosas
        num_opts=mis_opts.length;
        //marco el numero de opt en el select
        document.formulario1.Municipio.length = num_opts;
        //para cada opt del array, la pongo en el select
        for(i=0; i<num_opts; i++){
            document.formulario1.Municipio.options[i].value=mis_opts[i];
            document.formulario1.Municipio.options[i].text=mis_opts[i];
        }
        }else{
            //si no habia ninguna opt seleccionada, elimino las cosas del select
            document.formulario1.opt.length = 1;
            //ponemos un guion en la unica opt que he dejado
            document.formulario1.opt.options[0].value="-";
            document.formulario1.opt.options[0].text="-";
        }
        //hacer un reset de las opts
        document.formulario1.Municipio.options[0].selected = true;
        
    }




    
//--------------------------------------------- 1) Definir Las Variables Educación Correspondintes---------------------------------------------

var NivelEdu_PRIMARIA = new Array ("-",
"PRIMERO",
"SEGUNDO",
"TERCERO",
"CUARTO",
"QUINTO",
"SEXTO");

var NivelEdu_SECUNDARIA = new Array ("-",
"PRIMERO BASICO",
"SEGUNDO BASICO",
"TERCERO BASICO");


var NivelEdu_DIVERSIFICADO = new Array ("-",
"BACH CON ORIENT.TECNICA OCUP. EN ELECTRICIDAD Y SOLDADURA",
"BACH EN CIENCIAS Y LETRAS POR MADUREZ CON ORIENT EN COMPU",
"BACH. EN CC Y LL CON ORIENT. OCUP. EN MECANICA AUTOMOTRIZ",
"BACH. EN CIENCIAS Y LETRAS CON ESPEC. EN MUSICA",
"BACH. INDUSTRIAL, PERITO EN ELECTRICIDAD Y MECANICA AUTOMOT.",
"BACH.IND.Y PER. EN ELECTRONICA,ELECTRICIDAD Y MEC.AUTOM.",
"BACHILLER EN CIENCIAS Y LETRAS CON ORIENTACION EN ELECTRICIDAD",
"BACHILLER INDUST.Y PERITO EN CONSTRUCC Y DIBUJO COMPUTARIZA",
"BACHILLER INDUSTRIAL CON ESPECIALIDAD EN BELLEZA",
"BACHILLER INDUSTRIAL Y PERITO EN CONSTRUCCION",
"BACHILLERATO BILINGUE EN CIENCIAS Y HUMANIDADES",
"BACHILLERATO EN ADMON INDUST. Y PERITO EN ALGUNA ESPEC.",
"BACHILLERATO EN ADMON. INDUSTRIAL Y P. DIBUJO CONSTRUCCION",
"BACHILLERATO EN CIENCAS Y LETRAS CON ORIENTACION EN HOTELERIA Y HOGAR",
"BACHILLERATO EN CIENCIAS DE LA COMUNICACION",
"BACHILLERATO EN CIENCIAS Y LETRAS",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN ARTES ESCENICAS",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN ARTES VISUALES",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN CIENCIAS BIOLOGICAS",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN COMPUTACION",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN DISEÑO GRAFICO",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN EDUCACION",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN EDUCACION DE ARTES PLASTICAS",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN EDUCACION DE PRODUCTIVIDAD Y DESARROLLO",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN EDUCACION FISICA",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN EDUCACION MUSICAL",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN FINANZAS Y ADMINISTRACION",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN GESTION DE OFICINAS",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN MECANICA AUTOMOTRIZ",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN MUSICA",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN PRODUCTIVIDAD Y EMPRENDIMIENTO",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN TEXTILES",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN TURISMO",
"BACHILLERATO EN CIENCIAS Y LETRAS POR MADUREZ",
"BACHILLERATO EN CIENCIAS Y LETRAS Y SECRETARIADO BILINGUE",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACIÓN EN CIENCIAS BIOLÓGICAS Y DIPLOMADO EN MEDICINA",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACIÓN EN MEDICINA",
"BACHILLERATO EN CIENCIAS Y LETRAS EN CIENCIAS DE LA SALUD",
"BACHILLERATO EN CIENCIAS DE LA SALUD",
"BACHILLERATO EN CIENCIAS DE ENFERMERÍA",
"BACHILLERATO EN COMPUTACION",
"BACHILLERATO EN COMPUTACION CON ORIENTACION CIENTIFICA",
"BACHILLERATO EN COMPUTACION CON ORIENTACION COMERCIAL",
"BACHILLERATO EN CONSTRUCCION",
"BACHILLERATO EN CONSTRUCCION Y DIBUJO COMPUTARIZADO",
"BACHILLERATO EN COSMETOLOGIA",
"BACHILLERATO EN FISIOTERAPIA Y REHABILITACIÓN",
"BACHILLERATO EN DIBUJO TECNICO Y CONSTRUCION CON COMPUTACION",
"BACHILLERATO EN DIBUJO TECNICO Y DE CONSTRUCCION",
"BACHILLERATO EN DISEÑO DE INTERIORES",
"BACHILLERATO EN DISEÑO DE MODAS",
"BACHILLERATO EN DISEÑO GRAFICO",
"BACHILLERATO EN FILOSOFIA Y TEOLOGIA",
"BACHILLERATO EN HOTELERIA Y HOGAR",
"BACHILLERATO EN MERCADOTECNIA",
"BACHILLERATO EN TELECOMUNICACIONES",
"BACHILLERATO EN TURISMO",
"BACHILLERATO EN TURISMO CON ORIENTACION EN COMPUTACION",
"BACHILLERATO EN TURISMO ECOLOGICO",
"BACHILLERATO EN TURISMO Y ADMINISTRACION EN/DE HOTELES",
"BACHILLERATO EN TURISMO Y HOTELERIA",
"BACHILLERATO EN ARQUITECTURA",
"BACHILLERATO ECIENTIFICO-TECNOLÒGICO",                                    
"BACHILLERATO INDUS Y PERITO EN COSTURA INDUSTRIAL",
"BACHILLERATO INDUSTRIAL",
"BACHILLERATO INDUSTRIAL CON UNA ESPECIALIDAD",
"BACHILLERATO INDUSTRIAL Y PERITO CON ESP. EN DISEÑO DE MODAS",
"BACHILLERATO INDUSTRIAL Y PERITO CON ESPECIALIDAD EN COMPU.",
"BACHILLERATO INDUSTRIAL Y PERITO EN DIBUJO COMPUTARIZADO",
"BACHILLERATO INDUSTRIAL Y PERITO EN DIBUJO DE ARQUITECTURA E INGENIERIA",
"BACHILLERATO INDUSTRIAL Y PERITO EN DIBUJO DE CONSTRUCCION",
"BACHILLERATO INDUSTRIAL Y PERITO EN DISEÑO GRAFICO",
"BACHILLERATO INDUSTRIAL Y PERITO EN ELECTRICIDAD",
"BACHILLERATO INDUSTRIAL Y PERITO EN ELECTRONICA",
"BACHILLERATO INDUSTRIAL Y PERITO EN ENDEREZADO Y PINTURA",
"BACHILLERATO INDUSTRIAL Y PERITO EN INFORMATICA Y COMPUTACION",
"BACHILLERATO INDUSTRIAL Y PERITO EN MECANICA AUTOMOTRIZ",
"BACHILLERATO INDUSTRIAL Y PERITO EN MECANICA DE MANTENIMIENTO INDUSTRIAL",
"BACHTO. EN CIENCIAS Y LETRAS Y SECRET. BILG.(INGLES-ESPAÑOL)",
"MAGISTERIO DE EDUC. PREPRIMARIA CON ORIENT. A LA DEMOCRACIA",
"MAGISTERIO DE EDUCACION INFANTIL BILINGUE INTERCULTURAL",
"MAGISTERIO DE EDUCACION INFANTIL INTERCULTURAL",
"MAGISTERIO DE EDUCACION PREPRIMARIA BILINGUE ESPAÑOL-INGLES",
"MAGISTERIO DE EDUCACION PRIMARIA",
"MAGISTERIO DE EDUCACION PARA EL HOGAR",
"NORMAL PREPRIMARIA",
"NORMAL PREPRIMARIA BILINGUE",
"PERITO CONT. CON ESP. EN ADMON. DE PEQUEÑAS EMPRESAS AGRIC.",
"PERITO CONTADOR",
"PERITO CONTADOR BILINGUE (ESPAÑOL-INGLES)",
"PERITO CONTADOR CON ESPECIALIDAD EN COMPUTACION",
"PERITO CONTADOR CON ESPECIALIDAD EN COMPUTACION COMERCIAL",
"PERITO CONTADOR CON ORIENTACION ARTESANAL Y COMPUTACION",
"PERITO CONTADOR CON ORIENTACION COMERCIAL Y TURISMO",
"PERITO CONTADOR CON ORIENTACION EN ADMINISTRACION PORTUARIA",
"PERITO CONTADOR CON ORIENTACION EN COMPUTACION",
"PERITO CONTADOR CON ORIENTACION EN COMPUTACION COMERCIAL",
"PERITO CONTADOR EN COMPUTACION",
"PERITO EN CONSTRUCCIÓN",
"PERITO EN ADMINISTRACION",
"PERITO EN ADMINISTRACION DE EMPRESAS",
"PERITO EN ADMINISTRACION DE EMPRESAS CON ORIENTACION EN COMP",
"PERITO EN ADMINISTRACION PUBLICA",
"PERITO EN ADMINISTRACION TURISTICA Y HOTELERA",
"PERITO EN ADMON. PUBLICA CON ORIENTACION EN COMPUTACION",
"PERITO EN CIEN DE LA COMUNI CON ESPECI EN TELE RADIO COMUNIC",
"PERITO EN CIENCIAS AMBIENTALES",
"PERITO EN CIENCIAS DE LA COMUNICACION",
"PERITO EN CIENCIAS TURISTICAS",
"PERITO EN COMPUTACION",
"PERITO EN COMPUTACION Y BACHILLERATO EN CIENCIAS Y LETRAS",
"PERITO EN DESARROLLO COMUNITARIO",
"PERITO EN DIBUJO DE CONSTRUCCION",
"PERITO EN DIBUJO TECNICO DE INGENIERIA Y ARQUITECTURA",
"PERITO EN DIBUJO TECNICO DE INGENIERIA Y ARQUITECTURA Y BACHILLERATO EN CIENCIAS Y LETRAS",
"PERITO EN ECOTURISMO",
"PERITO EN ELECTRICIDAD INDUSTRIAL",
"PERITO EN ELECTRONICA Y DISPOSITIVOS DIGITALES",
"PERITO EN GERENCIA ADMINISTRATIVA",
"PERITO EN INDUSTRIA DE ALIMENTOS",
"PERITO EN INFORMATICA",
"PERITO EN MECANICA AUTOMOTRIZ",
"PERITO EN MECANICA AUTOMOTRIZ Y BACHILLERATO EN CIENCIAS Y LETRAS",
"PERITO EN MECANICA GENERAL (TORNOS)",
"PERITO EN MERCADOTECNIA Y PUBLICIDAD",
"PERITO EN RELACIONES PUBLICAS EMPRESARIALES",
"PERITO EN TURISMO SUSTENTABLE",
"PERITO EN HIGIENE DENTAL",
"PERITO INDUSTRIAL",
"PERITO INDUSTRIAL CON ESPECIALIDAD EN DIBUJO TECNICO Y DE CONSTRUCCION",
"PERITO INDUSTRIAL CON ESPECIALIDAD EN MECANICA AUTOMOTRIZ",
"PERITO EN MEDICINA DE LA EDUCACIÓN FÍSICA Y EL DEPORTE",
"PERITO EN EDUCACIÓN DEL DEPORTE",
"PERITO EN EDUCACIÓN FÍSICA",
"SECRET BILINGUE CON ORIENT EN IDIOMAS DIPLOMACIA Y REL INTER",
"SECRETARIADO BILINGUE / SECRETARIADO BILINGUE ESPAÑOL-INGLES",
"SECRETARIADO BILINGUE CON ESPECIALIDAD EN COMPUTACION",
"SECRETARIADO BILINGUE CON ORIENTA.TURISMO Y HOTELERIA",
"SECRETARIADO BILINGUE CON ORIENTACION EN COMPUTACION",
"SECRETARIADO BILINGUE ORIENTACION TURISMO-AGENCIA DE VIAJES",
"SECRETARIADO COMERCIAL",
"SECRETARIADO COMERCIAL CON ORIENTACION EN COMPUTACION",
"SECRETARIADO COMERCIAL Y OFICINISTA",
"SECRETARIADO EJECUTIVO",
"SECRETARIADO EJECUTIVO BILINGUE",
"SECRETARIADO EJECUTIVO BILINGUE CON ORIENT. EN MERC. Y PUB.",
"SECRETARIADO EJECUTIVO BILINGUE CON ORIENTA. COMP.COMERCIAL",
"SECRETARIADO EJECUTIVO EN COMPUTACION",
"SECRETARIADO EJECUTIVO EN ESPAÑOL",
"SECRETARIADO EJECUTIVO EN ESPAÑOL CON ORIENTACION EN COMPUT.",
"SECRETARIADO OFICINISTA CON ORIENTACION EN COMPUTACION",
"SECRETARIADO TRILINGUE CON ORIENT EN COMERCIO INTERNACIONAL",
"SECRETARIADO Y OFICINISTA",
"SECRETARIADO Y OFICINISTA CON ORIENTACION EN COMPUTACION",
"SECRETARIADO Y OFICINISTA CON ORIENTACION JURIDICA");



// ---------------------------------------------2) crear una funcion que permita ejecutar el cambio dinamico---------------------------------------------

function NivelEdus(){
    var Nivel_Academico;
    //Se toma el vamor de la "cosa seleccionada"
    Nivel_Academico = document.formulario1.Nivel_Academico[document.formulario1.Nivel_Academico.selectedIndex].value;
    //se chequea si la "cosa" esta definida
    if(Nivel_Academico!=0){
        //selecionamos las cosas Correctas
        mis_opts=eval("NivelEdu_" + Nivel_Academico);
        //se calcula el numero de cosas
        num_opts=mis_opts.length;
        //marco el numero de opt en el select
        document.formulario1.NivelEdu.length = num_opts;
        //para cada opt del array, la pongo en el select
        for(i=0; i<num_opts; i++){
            document.formulario1.NivelEdu.options[i].value=mis_opts[i];
            document.formulario1.NivelEdu.options[i].text=mis_opts[i];
        }
        }else{
            //si no habia ninguna opt seleccionada, elimino las cosas del select
            document.formulario1.opt.length = 1;
            //ponemos un guion en la unica opt que he dejado
            document.formulario1.opt.options[0].value="-";
            document.formulario1.opt.options[0].text="-";
        }
        //hacer un reset de las opts
        document.formulario1.NivelEdu.options[0].selected = true;
        
    }

//--------------------------------------------- 1) Definir Las Variables Colegio Profesional Correspondintes---------------------------------------------

var Colegio_GRADUADO = new Array ("-",
"Colegio De Abogados Y Notarios De Guatemala",
"Colegio De Arquitectos De Guatemala",
"Colegio De Contadores Públicos Y Auditores De Guatemala",
"Colegio De Economistas, Contadores Públicos Y Auditores Y Administradores De Empresas",
"Colegio De Farmacéuticos Y Químicos De Guatemala",
"Colegio De Ingenieros Agrónomos De Guatemala",
"Colegio De Ingenieros De Guatemala",
"Colegio De Ingenieros Químicos De Guatemala",
"Colegio De Médicos Veterinarios Y Zootecnistas De Guatemala",
"Colegio De Médicos Y Cirujanos De Guatemala",
"Colegio De Psicólogos De Guatemala",
"Colegio Estomatológico De Guatemala",
"Colegio Profesional De Humanidades De Guatemala",
"Colegio Profesional De Enfermería De Guatemala"
);


var Colegio_1er_TRIMESTRE = new Array("No Aplica");
var Colegio_2do_TRIMESTRE = new Array("No Aplica");
var Colegio_3er_TRIMESTRE = new Array("No Aplica");
var Colegio_4to_TRIMESTRE = new Array("No Aplica");
var Colegio_5to_TRIMESTRE = new Array("No Aplica");
var Colegio_6to_TRIMESTRE = new Array("No Aplica");
var Colegio_7mo_TRIMESTRE = new Array("No Aplica");
var Colegio_8avo_TRIMESTRE = new Array("No Aplica");
var Colegio_9no_TRIMESTRE = new Array("No Aplica");
var Colegio_10mo_TRIMESTRE = new Array("No Aplica");
var Colegio_11avo_TRIMESTRE = new Array("No Aplica");
var Colegio_12avo_TRIMESTRE = new Array("No Aplica");
var Colegio_13avo_TRIMESTRE = new Array("No Aplica");
var Colegio_14avo_TRIMESTRE = new Array("No Aplica");
var Colegio_15avo_TRIMESTRE = new Array("No Aplica");
var Colegio_16avo_TRIMESTRE = new Array("No Aplica");
var Colegio_17avo_TRIMESTRE = new Array("No Aplica");
var Colegio_18avo_TRIMESTRE = new Array("No Aplica");
var Colegio_19avo_TRIMESTRE = new Array("No Aplica");
var Colegio_20avo_TRIMESTRE = new Array("No Aplica");
var Colegio_21avo_TRIMESTRE = new Array("No Aplica");
var Colegio_22avo_TRIMESTRE = new Array("No Aplica");
var Colegio_23avo_TRIMESTRE = new Array("No Aplica");
var Colegio_24avo_TRIMESTRE = new Array("No Aplica");
var Colegio_1er_SEMESTRE = new Array("No Aplica");
var Colegio_2do_SEMESTRE = new Array("No Aplica");
var Colegio_3er_SEMESTRE = new Array("No Aplica");
var Colegio_4to_SEMESTRE = new Array("No Aplica");
var Colegio_5to_SEMESTRE = new Array("No Aplica");
var Colegio_6to_SEMESTRE = new Array("No Aplica");
var Colegio_7mo_SEMESTRE = new Array("No Aplica");
var Colegio_8vo_SEMESTRE = new Array("No Aplica");
var Colegio_9no_SEMESTRE = new Array("No Aplica");
var Colegio_10mo_SEMESTRE = new Array("No Aplica");
var Colegio_11avo_SEMESTRE = new Array("No Aplica");
var Colegio_12avo_SEMESTRE = new Array("No Aplica");
var Colegio_1er_AÑO = new Array("No Aplica");
var Colegio_2do_AÑO = new Array("No Aplica");
var Colegio_3er_AÑO = new Array("No Aplica");
var Colegio_4to_AÑO = new Array("No Aplica");
var Colegio_5to_AÑO = new Array("No Aplica");
var Colegio_6to_AÑO = new Array("No Aplica");
var Colegio_PENSUM_CERRADO = new Array("No Aplica");


// ---------------------------------------------2) crear una funcion que permita ejecutar el cambio dinamico---------------------------------------------

function NoColegioG(){
    var Grado;
    //Se toma el vamor de la "cosa seleccionada"
    Grado = document.formulario1.Grado[document.formulario1.Grado.selectedIndex].value;
    //se chequea si la "cosa" esta definida
    if(Grado!=0){
        //selecionamos las cosas Correctas
        mis_opts=eval("Colegio_" + Grado);
        //se calcula el numero de cosas
        num_opts=mis_opts.length;
        //marco el numero de opt en el select
        document.formulario1.Colegio.length = num_opts;
        //para cada opt del array, la pongo en el select
        for(i=0; i<num_opts; i++){
            document.formulario1.Colegio.options[i].value=mis_opts[i];
            document.formulario1.Colegio.options[i].text=mis_opts[i];
        }
        }else{
            //si no habia ninguna opt seleccionada, elimino las cosas del select
            document.formulario1.opt.length = 1;
            //ponemos un guion en la unica opt que he dejado
            document.formulario1.opt.options[0].value="-";
            document.formulario1.opt.options[0].text="-";
        }
        //hacer un reset de las opts
        document.formulario1.Colegio.options[0].selected = true;
        
    }


//--------------------------------------------- 1) Definir Las Variables Departamento y Municiío Correspondintes---------------------------------------------
var MuniLabol_GUATEMALA = new Array("-",
"GUATEMALA",
"SANTA CATARINA PINULA",
"SAN JOSÉ PINULA",
"SAN JOSÉ DEL GOLFO",
"PALENCIA",
"CHINAUTLA",
"SAN PEDRO AYAMPUC",
"MIXCO",
"SAN PEDRO SACATEPÉQUEZ",
"SAN JUAN SACATEPÉQUEZ",
"SAN RAYMUNDO",
"CHUARRANCHO",
"FRAIJANES",
"AMATITLÁN",
"VILLA NUEVA",
"VILLA CANALES",
"PETAPA",
);


var MuniLabol_EL_PROGRESO = new Array("-",
"GUASTATOYA",
"MORAZÁN",
"SAN AGUSTÍN ACASAGUASTLÁN",
"SAN CRISTÓBAL ACASAGUASTLÁN",
"EL JÍCARO",
"SANSARE",
"SANARATE",
"SAN ANTONIO LA PAZ",
);


var MuniLabol_SACATEPÉQUEZ = new Array("-",
"ANTIGUA GUATEMALA",
"JOCOTENANGO",
"PASTORES",
"SUMPANGO",
"SANTO DOMINGO XENACOJ",
"SANTIAGO SACATEPÉQUEZ",
"SAN BARTOLOMÉ MILPAS ALTAS",
"SAN LUCAS SACATEPÉQUEZ",
"SANTA LUCÍA MILPAS ALTAS",
"MAGDALENA MILPAS ALTAS",
"SANTA MARÍA DE JESÚS",
"CIUDAD VIEJA",
"SAN MIGUEL DUEÑAS",
"ALOTENANGO",
"SAN ANTONIO AGUAS CALIENTES",
"SANTA CATARINA BARAHONA",
);


var MuniLabol_CHIMALTENANGO = new Array("-",
"CHIMALTENANGO",
"SAN JOSÉ POAQUIL",
"SAN MARTÍN JILOTEPEQUE",
"COMALAPA",
"SANTA APOLONIA",
"TECPÁN GUATEMALA",
"PATZÚN",
"POCHUTA",
"PATZICÍA",
"SANTA CRUZ BALANYÁ",
"ACATENANGO",
"YEPOCAPA",
"SAN ANDRÉS ITZAPA",
"PARRAMOS",
"ZARAGOZA",
"EL TEJAR",
);


var MuniLabol_ESCUINTLA = new Array("-",
"ESCUINTLA",
"SANTA LUCÍA COTZUMALGUAPA",
"LA DEMOCRACIA",
"SIQUINALÁ",
"MASAGUA",
"TIQUISATE",
"LA GOMERA",
"GUANAGAZAPA",
"SAN JOSÉ",
"IZTAPA",
"PALÍN",
"SAN VICENTE PACAYA",
"NUEVA CONCEPCIÓN",
);


var MuniLabol_SANTA_ROSA = new Array("-",
"CUILAPA",
"BARBERENA",
"SANTA ROSA DE LIMA",
"CASILLAS",
"SAN RAFAEL LAS FLORES",
"ORATORIO",
"SAN JUAN TECUACO",
"CHIQUIMULILLA",
"TAXISCO",
"SANTA MARÍA IXHUATÁN",
"GUAZACAPÁN",
"SANTA CRUZ NARANJO",
"PUEBLO NUEVO VIÑAS",
"NUEVA SANTA ROSA",
);


var MuniLabol_SOLOLÁ = new Array("-",
"SOLOLÁ",
"SAN JOSÉ CHACAYÁ",
"SANTA MARÍA VISITACIÓN",
"SANTA LUCÍA UTATLÁN",
"NAHUALÁ",
"SANTA CATARINA IXTAHUACÁN",
"SANTA CLARA LA LAGUNA",
"CONCEPCIÓN",
"SAN ANDRÉS SEMETABAJ",
"PANAJACHEL",
"SANTA CATARINA PALOPÓ",
"SAN ANTONIO PALOPÓ",
"SAN LUCAS TOLIMÁN",
"SANTA CRUZ LA LAGUNA",
"SAN PABLO LA LAGUNA",
"SAN MARCOS LA LAGUNA",
"SAN JUAN LA LAGUNA",
"SAN PEDRO LA LAGUNA",
"SANTIAGO ATITLÁN",
);


var MuniLabol_TOTONICAPÁN = new Array("-",
"TOTONICAPÁN",
"SAN CRISTÓBAL TOTONICAPÁN",
"SAN FRANCISCO EL ALTO",
"SAN ANDRÉS XECUL",
"MOMOSTENANGO",
"SANTA MARÍA CHIQUIMULA",
"SANTA LUCÍA LA REFORMA",
"SAN BARTOLO",
);


var MuniLabol_QUETZALTENANGO = new Array("-",
"QUETZALTENANGO",
"SALCAJÁ",
"OLINTEPEQUE",
"SAN CARLOS SIJA",
"SIBILIA",
"CABRICÁN",
"CAJOLÁ",
"SAN MIGUEL SIGUILÁ",
"OSTUNCALCO",
"SAN MATEO",
"CONCEPCIÓN CHIQUIRICHAPA",
"SAN MARTÍN SACATEPÉQUEZ",
"ALMOLONGA",
"CANTEL",
"HUITÁN",
"ZUNIL",
"COLOMBA",
"SAN FRANCISCO LA UNIÓN",
"EL PALMAR",
"COATEPEQUE",
"GÉNOVA",
"FLORES COSTA CUCA",
"LA ESPERANZA",
"PALESTINA DE LOS ALTOS",
);


var MuniLabol_SUCHITEPÉQUEZ = new Array("-",
"MAZATENANGO",
"CUYOTENANGO",
"SAN FRANCISCO ZAPOTITLÁN",
"SAN BERNARDINO",
"SAN JOSÉ EL IDOLO",
"SANTO DOMINGO SUCHITEPÉQUEZ",
"SAN LORENZO",
"SAMAYAC",
"SAN PABLO JOCOPILAS",
"SAN ANTONIO SUCHITEPÉQUEZ",
"SAN MIGUEL PANÁN",
"SAN GABRIEL",
"CHICACAO",
"PATULUL",
"SANTA BÁRBARA",
"SAN JUAN BAUTISTA",
"SANTO TOMÁS LA UNIÓN",
"ZUNILITO",
"PUEBLO NUEVO",
"RÍO BRAVO",
"SAN JOSÉ LA MÁQUINA",
);


var MuniLabol_RETALHULEU = new Array("-",
"RETALHULEU",
"SAN SEBASTIÁN",
"SANTA CRUZ MULUÁ",
"SAN MARTÍN ZAPOTITLÁN",
"SAN FELIPE",
"SAN ANDRÉS VILLA SECA",
"CHAMPERICO",
"NUEVO SAN CARLOS",
"EL ASINTAL",
);


var MuniLabol_SAN_MARCOS = new Array("-",
"SAN MARCOS",
"SAN PEDRO SACATEPÉQUEZ",
"SAN ANTONIO SACATEPÉQUEZ",
"COMITANCILLO",
"SAN MIGUEL IXTAHUACÁN",
"CONCEPCIÓN TUTUAPA",
"TACANÁ",
"SIBINAL",
"TAJUMULCO",
"TEJUTLA",
"SAN RAFAEL PIÉ DE LA CUESTA",
"NUEVO PROGRESO",
"EL TUMBADOR",
"EL RODEO",
"MALACATÁN",
"CATARINA",
"AYUTLA",
"OCÓS",
"SAN PABLO",
"EL QUETZAL",
"LA REFORMA",
"PAJAPITA",
"IXCHIGUÁN",
"SAN JOSÉ OJETENÁN",
"SAN CRISTÓBAL CUCHO",
"SIPACAPA",
"ESQUIPULAS PALO GORDO",
"RÍO BLANCO",
"SAN LORENZO",
"LA BLANCA",
);


var MuniLabol_HUEHUETENANGO = new Array("-",
"HUEHUETENANGO",
"CHIANTLA",
"MALACATANCITO",
"CUILCO",
"NENTÓN",
"SAN PEDRO NECTA",
"JACALTENANGO",
"SOLOMA",
"IXTAHUACÁN",
"SANTA BÁRBARA",
"LA LIBERTAD",
"LA DEMOCRACIA",
"SAN MIGUEL ACATÁN",
"SAN RAFAEL LA INDEPENDENCIA",
"TODOS SANTOS CUCHUMATÁN",
"SAN JUAN ATITÁN",
"SANTA EULALIA",
"SAN MATEO IXTATÁN",
"COLOTENANGO",
"SAN SEBASTIÁN HUEHUETENANGO",
"TECTITÁN",
"TETAPAN",
"CONCEPCIÓN HUISTA",
"SAN JUAN IXCOY",
"SAN ANTONIO HUISTA",
"SAN SEBASTIÁN COATÁN",
"BARILLAS",
"AGUACATÁN",
"SAN RAFAEL PETZAL",
"SAN GASPAR IXCHIL",
"SANTIAGO CHIMALTENANGO",
"SANTA ANA HUISTA",
"UNIÓN CANTINIL",
);


var MuniLabol_QUICHÉ = new Array("-",
"SANTA CRUZ DEL QUICHÉ",
"CHICHÉ",
"CHINIQUE",
"ZACUALPA",
"CHAJUL",
"CHICHICASTENANGO",
"PATZITÉ",
"SAN ANTONIO ILOTENANGO",
"SAN PEDRO JOCOPILAS",
"CUNÉN",
"SAN JUAN COTZAL",
"JOYABAJ",
"NEBAJ",
"SAN ANDRÉS SAJCABAJÁ",
"USPANTÁN",
"SACAPULAS",
"SAN BARTOLOMÉ JOCOTENANGO",
"CANILLÁ",
"CHICAMÁN",
"IXCÁN",
"PACHALUM",
);


var MuniLabol_BAJA_VERAPAZ = new Array("-",
"SALAMÁ",
"SAN MIGUEL CHICAJ",
"RABINAL",
"CUBULCO",
"GRANADOS",
"EL CHOL",
"SAN JERÓNIMO",
"PURULHÁ",
);


var MuniLabol_ALTA_VERAPAZ = new Array("-",
"COBÁN",
"SANTA CRUZ VERAPAZ",
"SAN CRISTÓBAL VERAPAZ",
"TACTIC",
"TAMAHÚ",
"TUCURÚ",
"PANZÓS",
"SENAHÚ",
"SAN PEDRO CARCHÁ",
"SAN JUAN CHAMELCO",
"LANQUÍN",
"CAHABÓN",
"CHISEC",
"CHAHAL",
"FRAY BARTOLOMÉ DE LAS CASAS",
"SANTA CATALINA LA TINTA",
"RAXRUHÁ",
);


var MuniLabol_PETÉN = new Array("-",
"FLORES",
"SAN JOSÉ",
"SAN BENITO",
"SAN ANDRÉS",
"LA LIBERTAD",
"SAN FRANCISCO",
"SANTA ANA",
"DOLORES",
"SAN LUIS",
"SAYAXCHÉ",
"MELCHOR DE MENCOS",
"POPTÚN",
"LAS CRUCES",
"EL CHAL",
);


var MuniLabol_IZABAL = new Array("-",
"PUERTO BARRIOS",
"LIVINGSTON",
"EL ESTOR",
"MORALES",
"LOS AMATES",
);


var MuniLabol_ZACAPA = new Array("-",
"ZACAPA",
"ESTANZUELA",
"RÍO HONDO",
"GUALÁN",
"TECULUTÁN",
"USUMATLÁN",
"CABAÑAS",
"SAN DIEGO",
"LA UNIÓN",
"HUITÉ",
"SAN JORGE",
);


var MuniLabol_CHIQUIMULA = new Array("-",
"CHIQUIMULA",
"SAN JOSÉ LA ARADA",
"SAN JUAN ERMITA",
"JOCOTÁN",
"CAMOTÁN",
"OLOPA",
"ESQUIPULAS",
"CONCEPCIÓN LAS MINAS",
"QUETZALTEPEQUE",
"SAN JACINTO",
"IPALA",
);


var MuniLabol_JALAPA = new Array("-",
"JALAPA",
"SAN PEDRO PINULA",
"SAN LUIS JILOTEPEQUE",
"SAN MANUEL CHAPARRÓN",
"SAN CARLOS ALZATATE",
"MONJAS",
"MATAQUESCUINTLA",
);


var MuniLabol_JUTIAPA = new Array("-",
"JUTIAPA",
"EL PROGRESO",
"SANTA CATARINA MITA",
"AGUA BLANCA",
"ASUNCIÓN MITA",
"YUPILTEPEQUE",
"ATESCATEMPA",
"JEREZ",
"EL ADELANTO",
"ZAPOTITLÁN",
"COMAPA",
"JALPATAGUA",
"CONGUACO",
"MOYUTA",
"PASACO",
"SAN JOSÉ ACATEMPA",
"QUESADA",
);



// ---------------------------------------------2) crear una funcion que permita ejecutar el cambio dinamico---------------------------------------------

function DepartamentoLabol(){
    var DeptoLabol;
    //Se toma el vamor de la "cosa seleccionada"
    DeptoLabol = document.formulario1.DeptoLabol[document.formulario1.DeptoLabol.selectedIndex].value;
    //se chequea si la "cosa" esta definida
    if(DeptoLabol!=0){
        //selecionamos las cosas Correctas
        mis_opts=eval("MuniLabol_" + DeptoLabol);
        //se calcula el numero de cosas
        num_opts=mis_opts.length;
        //marco el numero de opt en el select
        document.formulario1.MuniLabol.length = num_opts;
        //para cada opt del array, la pongo en el select
        for(i=0; i<num_opts; i++){
            document.formulario1.MuniLabol.options[i].value=mis_opts[i];
            document.formulario1.MuniLabol.options[i].text=mis_opts[i];
        }
        }else{
            //si no habia ninguna opt seleccionada, elimino las cosas del select
            document.formulario1.opt.length = 1;
            //ponemos un guion en la unica opt que he dejado
            document.formulario1.opt.options[0].value="-";
            document.formulario1.opt.options[0].text="-";
        }
        //hacer un reset de las opts
        document.formulario1.MuniLabol.options[0].selected = true;
        
    }
