//--------------------------------------------- 1) Definir Las Variables Correspondintes---------------------------------------------
var opt_RENGLON_029 = new Array ("-", 
"029-SERVICIOS TÉCNICOS", 
"029-SERVICIOS PROFESIONALES");

var opt_RENGLON_036 = new Array ("NO APLICA");

var opt_RENGLON_081 = new Array ("-",
"081-SERVICIOS TÉCNICOS", 
"081-SERVICIOS PROFESIONALES");

var opt_RENGLON_181 = new Array ("NO APLICA");

var opt_RENGLON_182 = new Array ("-", 
"182-SERVICIOS TÉCNICOS", 
"182-SERVICIOS PROFESIONALES");

var opt_RENGLON_183 = new Array ("-", 
"183-SERVICIOS TÉCNICOS", 
"183-SERVICIOS PROFESIONALES");

var opt_RENGLON_184 = new Array ("-", 
"184-SERVICIOS TÉCNICOS", 
"184-SERVICIOS PROFESIONALES");

var opt_RENGLON_185 = new Array ("-", 
"185-SERVICIOS TÉCNICOS", 
"185-SERVICIOS PROFESIONALES");

var opt_RENGLON_186 = new Array ("-", 
"186-SERVICIOS TÉCNICOS", 
"186-SERVICIOS PROFESIONALES");

var opt_RENGLON_187 = new Array ("NO APLICA");

var opt_RENGLON_188 = new Array ("-", 
"188-SERVICIOS TÉCNICOS", 
"188-SERVICIOS PROFESIONALES");

var opt_RENGLON_189 = new Array ("-", 
"189-SERVICIOS TÉCNICOS", 
"189-SERVICIOS PROFESIONALES");


// ---------------------------------------------2) crear una funcion que permita ejecutar el cambio dinamico---------------------------------------------

function cambia(){
    var Renglon;
    //Se toma el vamor de la "cosa seleccionada"
    Renglon = document.formulario1.Renglon[document.formulario1.Renglon.selectedIndex].value;
    //se chequea si la "cosa" esta definida
    if(Renglon!=0){
        //selecionamos las cosas Correctas
        mis_opts=eval("opt_" + Renglon);
        //se calcula el numero de cosas
        num_opts=mis_opts.length;
        //marco el numero de opt en el select
        document.formulario1.opt.length = num_opts;
        //para cada opt del array, la pongo en el select
        for(i=0; i<num_opts; i++){
            document.formulario1.opt.options[i].value=mis_opts[i];
            document.formulario1.opt.options[i].text=mis_opts[i];
        }
        }else{
            //si no habia ninguna opt seleccionada, elimino las cosas del select
            document.formulario1.opt.length = 1;
            //ponemos un guion en la unica opt que he dejado
            document.formulario1.opt.options[0].value="-";
            document.formulario1.opt.options[0].text="-";
        }
        //hacer un reset de las opts
        document.formulario1.opt.options[0].selected = true;
        
    }


//--------------------------------------------- 1) Definir Las Variables Especialidad Correspondintes---------------------------------------------
var Terminos_RENGLON_029 = new Array ("-",
"029-ADMINISTRADOR DE SISTEMAS",
"029-AGENTE DE SEGURIDAD",
"029-ANALISTA ADMINISTRATIVO- FINANCIERO",
"029-ANALISTA ADMINISTRATIVO-FINANCIERO",
"029-ANALISTA CONTABLE",
"029-ANALISTA DE ADMINISTRACION DE NOMINA",
"029-ANALISTA DE CAJA FISCAL",
"029-ANALISTA DE COMPRAS",
"029-ANALISTA DE CONTABILIDAD FINANCIERA",
"029-ANALISTA DE CONTRATOS PLANTA CENTRAL",
"029-ANALISTA DE COOPERACION TECNICA",
"029-ANALISTA DE COSTOS / UPE",
"029-ANALISTA DE DATOS DE CAPACITACION",
"029-ANALISTA DE DOTACION DE PERSONAL ",
"029-ANALISTA DE DOTACION DE PERSONAL",
"029-ANALISTA DE DOTACION DE RECURSOS HUMANOS (201)",
"029-ANALISTA DE GASTO",
"029-ANALISTA DE GESTION DE PROYECTOS",
"029-ANALISTA DE INFORMACION EPIDEMIOLOGICA",
"029-ANALISTA DE INFORMACION",
"029-ANALISTA DE LA SECCION DE ANALISIS DE PUESTOS",
"029-ANALISTA DE LA SECCION DE MONITOREO DE ESCUELAS DE AUXILIARES, ESCUELAS TECNICAS Y UNIVERSIDADES DE ENFERMERIA DEL DEPARTAMENTO DE FORMACION",
"029-ANALISTA DE LA UNIDAD DE TRANSPARENCIA Y ANTICORRUPCION II",
"029-ANALISTA DE PLANIFICACION ESTRATEGICA",
"029-ANALISTA DE PLANIFICACION Y PROGRAMACION II",
"029-ANALISTA DE PLANIFICACION Y PROGRAMACION",
"029-ANALISTA DE PRESUPUESTO 201",
"029-ANALISTA DE PRESUPUESTO",
"029-ANALISTA DE PROVISION DE LOS SERVICIOS",
"029-ANALISTA DE RECURSOS HUMANOS ",
"029-ANALISTA DE RECURSOS HUMANOS DEL DEPARTAMENTO DE RRHH  PLANTA CENTRAL (201)",
"029-ANALISTA DE RECURSOS HUMANOS",
"029-ANALISTA DE REGISTROS DE ACREDITACION Y CONTROL DE ESTABLECIMIENTOS DE SALUD",
"029-ANALISTA DE REGISTROS DE ALIMENTOS",
"029-ANALISTA DE SECCION DE ACCIONES DE PERSONAL",
"029-ANALISTA DE SECRETARIA EJECUTIVA",
"029-ANALISTA DE SEGUIMIENTO DE PROCESOS",
"029-ANALISTA DE SEGUIMIENTO Y VERIFICACION",
"029-ANALISTA DE VENTANILLA UNICA (SIAD)",
"029-ANALISTA DEL DEPARTAMENTO ADMINISTRATIVO",
"029-ANALISTA E INVESTIGADOR DE LA SECCION DE PLANIFICACION E INVESTIGACION DEL DEPARTAMENTO DE FORMACION",
"029-ANALISTA EN INFRAESTRUCTURA Y SEGURIDAD DE REDES",
"029-ANALISTA FINANCIERO DEL AREA DE TESORERIA",
"029-ANALISTA FINANCIERO",
"029-ANALISTA JURIDICO",
"029-ANALISTA PLANIFICADOR EN INFRAESTRUCTURA",
"029-ANALISTA TECNICO EN DISEÑO WEB",
"029-APOYO TECNICO FINANCIERO Y ADMINISTRATIVO",
"029-ASESOR (A) ADMINISTRATIVO (A) DE DIRECCION GENERAL DE RECURSOS HUMANOS",
"029-ASESOR (A) ANALITICO (A)",
"029-ASESOR (A) DE COORDINACION INTERINSTITUCIONAL DE UNIDAD DE GENERO",
"029-ASESOR (A) DE DESPACHO MINISTERIAL I",
"029-ASESOR (A) DE DESPACHO MINISTERIAL",
"029-ASESOR (A) DE PLANIFICACION DE LA COMISION TECNICA DE EVALUACION",
"029-ASESOR (A) DE VICEMINISTERIO ADMINISTRATIVO I",
"029-ASESOR (A) ESPECIFICO (A) DE RECURSOS HUMANOS I",
"029-ASESOR (A) ESPECIFICO DE RECURSOS HUMANOS",
"029-ASESOR (A) JURIDICO (A) DE REGULACION II",
"029-ASESOR (A) JURIDICO (A) DE REGULACION",
"029-ASESOR (A) JURIDICO (A) DE SECRETARIA EJECUTIVA",
"029-ASESOR (A) JURIDICO (A) DEL DEPARTAMENTO DE ADQUISICIONES Y MANTENIMIENTO",
"029-ASESOR (A) JURIDICO DE SECRETARIA EJECUTIVA I",
"029-ASESOR (A) LEGAL",
"029-ASESOR (A) TECNICO (A) DE VICEMINISTERIO TECNICO",
"029-ASESOR ADMINISTRATIVO DE SECRETARIA EJECUTIVA",
"029-ASESOR ADMINISTRATIVO FINANCIERO",
"029-ASESOR DE DIRECCION",
"029-ASESOR DE VICEMINISTERIO ADMINISTRATIVO II",
"029-ASESOR DE VICEMINISTERIO ADMINISTRATIVO III",
"029-ASESOR DE VICEMINISTERIO ADMINISTRATIVO IV",
"029-ASESOR ESPECIALISTA EN INFRAESTRUCTURA HOSPITALARIA",
"029-ASESOR ESPECIFICO DE COMUNICACION SOCIAL",
"029-ASESOR ESPECIFICO DE DESPACHO MINISTERIAL",
"029-ASESOR FINANCIERO",
"029-ASESOR JURIDICO DE SECRETARIA EJECUTIVA II",
"029-ASESOR PROFESIONAL EN PROYECTOS",
"029-ASESOR TECNICO DE VICEMINISTERIO DE HOSPITALES",
"029-ASESOR TECNICO",
"029-ASESOR Y TRADUCTOR JURADO DE LA GERENCIA GENERAL ADMINISTRATIVA FINANCIERA",
"029-ASISTENCIA TECNICA EN BANCO DE LECHE HUMANA",
"029-ASISTENCIA TECNICA EN INGENIERIA BIOMEDICA PARA LA GESTION DE MANTENIMIENTO EN LA RED HOSPITALARIA",
"029-ASISTENCIA TECNICA EN LA SECCION DE VIOLENCIA SEXUAL",
"029-ASISTENCIA TECNICA EN SERVICIOS DE SALUD MENTAL",
"029-ASISTENCIA Y VERIFICACION DE LA ADMINISTRACION DE RECURSOS HUMANOS EN LA RED HOSPITALARIA",
"029-ASISTENTE ADMINISTRATIVO DE SECRETARIA EJECUTIVA",
"029-ASISTENTE ADMINISTRATIVO DE SERVICIOS GENERALES",
"029-ASISTENTE ADMINISTRATIVO DE VICEMINISTERIO",
"029-ASISTENTE ADMINISTRATIVO EN PROCURACION",
"029-ASISTENTE ADMINISTRATIVO FINANCIERO",
"029-ASISTENTE ADMINISTRATIVO",
"029-ASISTENTE ADMINISTRATIVO-FINANCIERO",
"029-ASISTENTE COMUNICACION EXTERNA",
"029-ASISTENTE DE COMUNICACION SOCIAL",
"029-ASISTENTE DE COMUNICACION",
"029-ASISTENTE DE CONTABILIDAD II",
"029-ASISTENTE DE CONTABILIDAD III",
"029-ASISTENTE DE CONTABILIDAD",
"029-ASISTENTE DE DIRECCION",
"029-ASISTENTE DE ENLACE DE COMUNICACION SOCIAL",
"029-ASISTENTE DE FACILITADOR DEL AREA HOSPITALARIA",
"029-ASISTENTE DE FORMACION DE LA UNIDAD DE ATENCION DE LA SALUD DE LOS PUEBLOS INDIGENAS E INTERCULTURALIDAD",
"029-ASISTENTE DE GESTION DE RIESGO",
"029-ASISTENTE DE GESTION DE VEHICULOS",
"029-ASISTENTE DE IMPORTACIONES",
"029-ASISTENTE DE KARDEX",
"029-ASISTENTE DE LA UNIDAD DE LICENCIAS SANITARIAS",
"029-ASISTENTE DE LICENCIAS FARMACEUTICAS",
"029-ASISTENTE DE LOGISTICA DE MALARIA",
"029-ASISTENTE DE LOGISTICA Y CORRESPONDENCIA",
"029-ASISTENTE DE MANTENIMIENTO ",
"029-ASISTENTE DE MANTENIMIENTO",
"029-ASISTENTE DE MONITOREO DE COMUNICACION SOCIAL",
"029-ASISTENTE DE PROCESOS DE SEGURIDAD",
"029-ASISTENTE DE PROMOCION DE LA SALUD",
"029-ASISTENTE DE PROTOCOLO DE COMUNICACION SOCIAL",
"029-ASISTENTE DE RECURSOS HUMANOS",
"029-ASISTENTE DE REGISTRO Y VERIFICACION DE INGRESO DE VISITANTES",
"029-ASISTENTE DE REGISTROS SANITARIOS",
"029-ASISTENTE DE SECRETARIA EJECUTIVA",
"029-ASISTENTE DEL DEPARTAMENTO ADMINISTRATIVO",
"029-ASISTENTE DEL DESPACHO MINISTERIAL",
"029-ASISTENTE EN INFRAESTRUCTURA HOSPITALARIA",
"029-ASISTENTE EN PROMOCION DE LA SALUD",
"029-ASISTENTE FARMACEUTICO",
"029-ASISTENTE FINANCIERO",
"029-ASISTENTE GESTORA DE LOGISTICA Y ADMINISTRACION EN COMUNICACION SOCIAL",
"029-ASISTENTE JURIDICO",
"029-ASISTENTE PROFESIONAL DE COMUNICACION SOCIAL",
"029-ASISTENTE TECNICA EN GESTION DE RIESGO EN SUPERVISION DE HOSPITALES",
"029-ASISTENTE TECNICO DE ADQUISICIONES Y MANTENIMIENTO",
"029-ASISTENTE TECNICO DE DESARROLLO DE LOS SERVICIOS",
"029-ASISTENTE TECNICO DE HOSPITALES",
"029-ASISTENTE TECNICO DE LAS AREAS DE SALUD",
"029-ASISTENTE TECNICO EN GESTION ADMINISTRATIVA FINANCIERA",
"029-ASISTENTE TECNICO",
"029-AUDITOR DE AUDITORIA INTERNA",
"029-AUXILIAR CONTABLE ",
"029-AUXILIAR DE ALMACEN",
"029-AUXILIAR DE ARCHIVO",
"029-AUXILIAR DE ATENCION AL USUARIO",
"029-AUXILIAR DE AUDITORIA",
"029-AUXILIAR DE BODEGA",
"029-AUXILIAR DE CONTABILIDAD",
"029-AUXILIAR DE ENFERMERIA DE TUBERCULOSIS",
"029-AUXILIAR DE ESTADISTICA",
"029-AUXILIAR DE HOSPITAL",
"029-AUXILIAR DE INFORMACION (RECEPCION)",
"029-AUXILIAR DE INFORMATICA",
"029-AUXILIAR DE INSPECCION SANITARIA",
"029-AUXILIAR DE INVENTARIOS",
"029-AUXILIAR DE MANTENIMIENTO ",
"029-AUXILIAR DE MANTENIMIENTO DE MATERIAL VOLUMETRICO DE LABORATORIO NACIONAL DE SALUD",
"029-AUXILIAR DE MANTENIMIENTO",
"029-AUXILIAR DE MONITOREO DE SERVICIOS",
"029-AUXILIAR DE PRESUPUESTO",
"029-AUXILIAR DE PROVISION",
"029-AUXILIAR DE REGISTROS MEDICOS",
"029-AUXILIAR DE REGISTROS Y ESTADISTICA DEL DEPARTAMENTO DE ADQUISICIONES Y MANTENIMIENTO",
"029-CAMAROGRAFO (A)",
"029-CONSULTOR (A) DE PROYECTOS DE REMOZAMIENTO DE PUESTOS DE SALUD",
"029-CONSULTOR ESPECIALISTA FINANCIERO",
"029-CREATIVO VISUAL",
"029-DESARROLLADOR DE PROYECTOS DE LA COORDINACION DE HOSPITALES",
"029-DIBUJANTE",
"029-DIGITADOR SIGSA WEB",
"029-DIGITADOR",
"029-DISEÑADOR (A) GRAFICO",
"029-EDUCADOR (A) EN SALUD Y NUTRICION",
"029-ENFERMERO (A) DE CAMPO",
"029-ENLACE CONTABLE",
"029-ENTOMOLOGO DE MALARIA",
"029-EPIDEMIOLOGO (A)",
"029-ESPECIALISTA AMBIENTAL",
"029-ESPECIALISTA EN DONACIONES Y COOPERACION TECNICA",
"029-ESPECIALISTA EN RELACIONES INTERNACIONALES",
"029-FACILITADOR (A)  DE DESARROLLO EPIDEMIOLOGICO",
"029-FACILITADOR (A) ADMINISTRATIVO FINANCIERO II",
"029-FACILITADOR (A) ADMINISTRATIVO FINANCIERO",
"029-FACILITADOR (A) CREATIVO (A) DE COMUNICACION SOCIAL ",
"029-FACILITADOR (A) DE ADUANAS",
"029-FACILITADOR (A) DE ALIMENTOS ",
"029-FACILITADOR (A) DE ANALISIS DE PUESTOS  (201)",
"029-FACILITADOR (A) DE ASISTENCIA TECNICA",
"029-FACILITADOR (A) DE AUTORIZACIONES SANITARIAS",
"029-FACILITADOR (A) DE CALIDAD DE INFORMACION DEL PROGRAMA DE MALARIA",
"029-FACILITADOR (A) DE COMISION DE PLAGUICIDAS",
"029-FACILITADOR (A) DE COMUNICACION SOCIAL DE MEDICINA TRANSFUSIONAL Y BANCOS DE SANGRE",
"029-FACILITADOR (A) DE CONTROLES INTERNOS DE RECURSOS HUMANOS",
"029-FACILITADOR (A) DE COSTOS Y PRODUCCION HOSPITALARIA",
"029-FACILITADOR (A) DE DESARROLLO ESTRATEGICO",
"029-FACILITADOR (A) DE DIRECCION",
"029-FACILITADOR (A) DE ESTABLECIMIENTOS",
"029-FACILITADOR (A) DE FARMACOVIGILANCIA",
"029-FACILITADOR (A) DE HOSPITALES II",
"029-FACILITADOR (A) DE LA RED DE LABORATORIOS DE SALUD",
"029-FACILITADOR (A) DE LA RED DE SALUD",
"029-FACILITADOR (A) DE LA SECCION DE COMPRAS DEL DEPARTAMENTO ADMINISTRATIVO",
"029-FACILITADOR (A) DE LA SECCION DE PRESUPUESTO",
"029-FACILITADOR (A) DE LA UNIDAD DE INFORMACION PUBLICA",
"029-FACILITADOR (A) DE LA UNIDAD ESPECIALIZADA DE COOPERACION INTERNACIONAL",
"029-FACILITADOR (A) DE MANTENIMIENTO",
"029-FACILITADOR (A) DE MEDICAMENTOS",
"029-FACILITADOR (A) DE MONITOREO Y EVALUACION TB",
"029-FACILITADOR (A) DE PLANIFICACION DE TRANSPORTES",
"029-FACILITADOR (A) DE PROCESOS DE LA UNIDAD TECNICA DE TRANSPARENCIA Y ANTICORRUPCION",
"029-FACILITADOR (A) DE PROCESOS DE SEGURIDAD",
"029-FACILITADOR (A) DE PRODUCCION AUDIOVISUAL",
"029-FACILITADOR (A) DE PROTOCOLO DE COMUNICACION SOCIAL",
"029-FACILITADOR (A) DE PROYECTOS DE INFRAESTRUCTURA Y CONSTRUCCION",
"029-FACILITADOR (A) DE RECURSOS HUMANOS",
"029-FACILITADOR (A) DE REDES SOCIALES ",
"029-FACILITADOR (A) DE REGULACION Y CONTROL DE ALIMENTOS",
"029-FACILITADOR (A) DE RELACIONES INTERINSTITUCIONALES",
"029-FACILITADOR (A) DE SANEAMIENTO AMBIENTAL",
"029-FACILITADOR (A) DE SEGUIMIENTO, MONITOREO Y EVALUACION DE LA UNIDAD DE GENERO",
"029-FACILITADOR (A) DE TRANSPORTES",
"029-FACILITADOR (A) DEL AREA DE VIOLENCIA SEXUAL, MALTRATO INFANTIL Y EMBARAZOS A NIÑAS",
"029-FACILITADOR (A) DEL COMPONENTE DE LOGISTICA DE MEDICAMENTOS",
"029-FACILITADOR (A) DEL DEPARTAMENTO DE DESARROLLO HUMANO",
"029-FACILITADOR (A) DEL DEPARTAMENTO DE REGULACION, ACREDITACION Y CONTROL DE ESTABLECIMIENTOS DE SALUD",
"029-FACILITADOR (A) EN EL PROGRAMA NACIONAL DEL ITS, VIH Y SIDA",
"029-FACILITADOR (A) EN MONITOREO DE SERVICIOS DE SALUD",
"029-FACILITADOR (A) GENERAL DE SIGSA",
"029-FACILITADOR (A) INTERINSTITUCIONAL EN GESTION DE HOSPITALES UNIVERSITARIOS",
"029-FACILITADOR (A) LOCAL DE MALARIA",
"029-FACILITADOR (A) MONITOREO Y EVALUACION SUBVENCION MALARIA",
"029-FACILITADOR (A) MULTISECTORIAL",
"029-FACILITADOR (A) NORMATIVO DE SALUD MENTAL",
"029-FACILITADOR (A) UNIDAD DE INVESTIGACION Y ESTUDIO",
"029-FACILITADOR (A)PARA EL  RESGUARDO Y CLASIFICACION DE EXPEDIENTES DEL RECURSO HUMANO DE PLANTA CENTRAL.",
"029-FACILITADOR DE GESTION DE CALIDAD HOSPITALARIA",
"029-FACILITADOR DE PRENSA E IMAGEN INSTITUCIONAL",
"029-FACILITADOR DE PROCESOS ADMINISTRATIVOS",
"029-FOTOGRAFO (A)",
"029-GESTOR (A) ADMINISTRATIVO (A) DE PROYECTOS DE SALUD",
"029-INSPECTOR DE MULTISECTORIAL",
"029-MONITOR (A) DE CAMPO",
"029-MONITOR (A) DE ESCUELAS DE AUXILIARES  ",
"029-MONITOR (A) DEL LABORATORIO DE MALARIA",
"029-MONITOR (A) Y EVALUADOR (A)  DE MALARIA",
"029-NORMATIVO DEL PROGRAMA DE ZOONOSIS",
"029-NUTRICIONISTA PARA LA RED DE SERVICIOS DE SALUD",
"029-PRODUCTOR (A) DE VIDEO",
"029-PSICOLOGO (A) INDUSTRIAL",
"029-QUIMICO (A) BIOLOGO (A)",
"029-QUIMICO BIOLOGO",
"029-QUIMICO FARMACEUTICO",
"029-REVISION DE PROYECTOS DE INFRAESTRUCTURA",
"029-SEGURIDAD VEHICULAR",
"029-SERVICIO DE CONDUCCION DE VEHICULOS",
"029-SERVICIOS DE INFORMATICA PARA EL PROGRAMA DE MALARIA",
"029-SERVICIOS PARA EL DESARROLLO E IMPLEMENTACION DE PROCESOS INFORMATICOS",
"029-SERVICIOS PROFESIONALES DE PSICOLOGIA",
"029-TECNICO (A) DE VERIFICACION DE PROCEDIMIENTOS DE GESTION DE RIESGO EN HOSPITALES  ",
"029-TECNICO ADMINISTRATIVO EN BASE DE DATOS",
"029-TECNICO ADMINISTRATIVO EN DESARROLLO DE SIGSA",
"029-TECNICO DE AUTORIZACIONES",
"029-TECNICO DE ENTOMOLOGIA",
"029-TECNICO DE ESTABLECIMIENTOS FARMACEUTICOS",
"029-TECNICO DE INFORMACION, EDUCACION Y COMUNICACION DE MALARIA",
"029-TECNICO DE INFORMATICA",
"029-TECNICO DE INVESTIGACION Y ESTUDIO",
"029-TECNICO DE PROCESOS ADMINISTRATIVOS DE COORDINACION",
"029-TECNICO DE PROMOCION DE MALARIA",
"029-TECNICO ELECTRICISTA",
"029-TECNICO EN ADQUISICIONES ",
"029-TECNICO EN CALIDAD DE INFORMACION",
"029-TECNICO EN DIFUSION DE ESTADISTICAS DE SALUD",
"029-TECNICO EN DISEÑO E INTEGRACION DE SOLUCIONES",
"029-TECNICO EN IMPLEMENTACION Y ASISTENCIA TECNICA EN SISTEMAS DE INFORMACION",
"029-TECNICO EN INFORMACION",
"029-TECNICO EN INFORMATICA",
"029-TECNICO EN LABORATORIO",
"029-TECNICO EN PLANIFICACION Y COORDINACION EN EL CAMPO DE MALARIA",
"029-TECNICO EN RECEPCION Y PROCESAMIENTO DE DATOS",
"029-TECNICO EN REMOZAMIENTO E INFRAESTRUCTURA ",
"029-TECNICO EN SALUD RURAL",
"029-TECNICO EN SANEAMIENTO AMBIENTAL",
"029-TECNICO EN SOPORTE INFORMATICO",
"029-TECNICO EN TRABAJO SOCIAL",
"029-TECNICO NORMATIVO DE COORDINACION INTERINSTITUCIONAL",
"029-TECNICO NORMATIVO",
"029-TRABAJADOR (A) SOCIAL");

var Terminos_RENGLON_036 = new Array ("NO APLICA");

var Terminos_RENGLON_081 = new Array ("-", 
"081-ANALISTA CONTABLE ADMINISTRATIVO NIVEL 3",
"081-ASISTENTE ADMINISTRATIVO FINANCIERO",
"081-ASISTENTE ADMINISTRATIVO",
"081-ASISTENTE DE MONITOREO NIVEL 3",
"081-AUXILIAR DE ENFERMERIA DE TUBERCULOSIS",
"081-CONSULTOR ADMINISTRATIVO FINANCIERO NIVEL 1",
"081-CONSULTOR CAMBIO DE COMPORTAMIENTO NIVEL 1",
"081-CONSULTOR CONTABLE FINANCIERO",
"081-CONSULTOR EN ATENCION PRIMARIA EN SALUD Y NUTRICION NIVEL 1",
"081-CONSULTOR EN COMUNICACION E INFORMACION NIVEL 2",
"081-CONSULTOR EN CONSTRUCCIÓN PUESTOS DE SALUD NIVEL 1",
"081-CONSULTOR EN REMOZAMIENTO PUESTOS DE SALUD NIVEL 1",
"081-CONSULTOR FINANCIERO NIVEL1",
"081-CONSULTOR(A) FACILITADOR(A) DE LOS PROCESOS TECNICOS Y ADMINISTRATIVOS DE LAS ACTIVIDADES DEL PROYECTO CRECER SANO EN SESAN NIVEL 2",
"081-ENFERMERO DE CAMPO",
"081-ESPECIALISTA DE AGUA POTABLE, SANEAMIENTO E HIGIENE RURAL / CONSULTOR NIVEL 2",
"081-ESPECIALISTA DE GESTION SOCIAL Y COMUNITARIA, DE PROYECTOS DE AGUA, SANEAMIENTO E HIGIENE RURAL NIVEL 2",
"081-ESPECIALISTA DE MONITOREO, EVALUACION, SUPERVISION Y SEGUIMIENTO DE INDICADORES DEL PROYECTO / CONSULTOR NIVEL 2",
"081-ESPECIALISTA EN ADQUISICIONES / CONSULTOR EN ADQUISICIONES NIVEL 2",
"081-ESPECIALISTA EN CALIDAD DE LA APS Y FORTALECIMIENTO DE ESTRATEGIAS NIVEL 2",
"081-ESPECIALISTA EN CAPACITACION Y FORMACION EN APS Y NUTRICION NIVEL 2",
"081-ESPECIALISTA EN LOGISTICA Y CADENA DE SUMINISTRO DE ATENCION PRIMARIA EN SALUD  Y NUTRICION NIVEL 2",
"081-ESPECIALISTA EN NUTRICION EN ATENCION PRIMARIA EN SALUD NIVEL 2",
"081-ESPECIALISTA FINANCIERO/CONSULTOR FINANCIERO NIVEL 2",
"081-ESPECIALISTA REMOZAMIENTOS PUESTOS DE SALUD NIVEL 2",
"081-ESPECIALISTA SALVAGUARDA MANEJO SOCIAL / CONSULTOR NIVEL 2",
"081-ESPECIALISTA SALVAGUARDAS AMBIENTALES / CONSULTOR NIVEL 2",
"081-FACILITADOR DE LA GESTION CRECER SANO / CONSULTOR NIVEL 1",
"081-FACILITADOR DE LA RED DE LABORATORIOS DE SALUD",
"081-PROFESIONAL GESTION / COORDINACION DE PROYECTO",
"081-PROFESIONAL SALVAGUARDAS AMBIENTALES",
"081-RESPONSABLE DE ADQUISICIONES / CONSULTOR EN ADQUISICIONES NIVEL 1",
"081-RESPONSABLE DE AGUA, SANEAMIENTO E HIGIENE RURAL",
"081-SERVICIOS DE CONDUCCION DE VEHICULOS",
"081-SERVICIOS PROFESIONALES DE PSICOLOGIA",
"081-TECNICO DE MONITOREO Y MANEJO DE INFORMACION PARA AGUA Y SANEAMIENTO NIVEL 3",
"081-TECNICO EN REMOZAMIENTO E INFRAESTRUCTURA",
"081-TECNICO NORMATIVO",
"081-TECNICOS EN LABORATORIO");

var Terminos_RENGLON_181 = new Array ("NO APLICA");

var Terminos_RENGLON_182 = new Array ("-",
"182-ANALISTA DE DIAGNOSTICO Y VIGILANCIA EPIDEMIOLOGICA",
"182-ANALISTA DEL LABORATORIO NACIONAL DE SALUD",
"182-ASESORES MEDICOS",
"182-ASISTENTE DE ENLACE DEL PROGRAMA NACIONAL DE SALUD REPRODUCTIVA",
"182-ASISTENTE DE SANEAMIENTO AMBIENTAL",
"182-ASISTENTE TECNICO DESARROLLO DE LOS SERVICIOS",
"182-AUXILIAR DE ENFERMERIA DE AREA DE SALUD DEC. 11-2021",
"182-AUXILIAR DE ENFERMERIA DE AREA DE SALUD",
"182-AUXILIAR DE ENFERMERIA DE HOSPITAL DEC. 11-2021",
"182-AUXILIAR DE ENFERMERIA DE HOSPITAL",
"182-AUXILIAR DE ENFERMERIA DEL PRIMER NIVEL DE ATENCION DEC. 11-2021",
"182-AUXILIAR DE ENFERMERIA DEL PRIMER NIVEL DE ATENCION",
"182-AUXILIAR DE EPIDEMIOLOGIA",
"182-AUXILIAR DE FARMACIA",
"182-CARDIOLOGO",
"182-CIRUJANO DEC. 11-2021",
"182-CIRUJANO",
"182-CITOTECNOLOGO",
"182-EDUCADOR (A) EN SALUD Y NUTRICION",
"182-ENFERMERA (O) PROFESIONAL DEC. 11-2021",
"182-ENFERMERA (O) PROFESIONAL",
"182-ENFERMERA (O) TECNICO DEC. 11-2021",
"182-ENFERMERA (O) TECNICO",
"182-ENFERMERO (A) AMBULATORIO (A)/ NIVEL PROFESIONAL",
"182-ENFERMERO (A) AMBULATORIO (A)/ NIVEL TECNICO",
"182-ENFERMERO (A) PROFESIONAL DEL PRIMER NIVEL DE ATENCION",
"182-ENFERMERO DE EQUIPO INSTITUCIONAL DE SALUD",
"182-EPIDEMIOLOGO (A) DEC. 11-2021",
"182-EPIDEMIOLOGO (A)",
"182-FACILITADOR  (A) COMPONENTE  MATERNIDAD SALUDABLE ",
"182-FACILITADOR (A) COMPONENTE DE ADOLESCENTES",
"182-FACILITADOR (A) COMPONENTE DE COMADRONAS",
"182-FACILITADOR (A) DEL COMPONENTE DE MORTALIDAD MATERNA Y NEONATAL",
"182-FACILITADOR (A) DEL PROGRAMA DE SALUD REPRODUCTIVA",
"182-FACILITADOR (A) NORMATIVO DE VIGILANCIA EPIDEMIOLOGICA MATERNO NEONATAL",
"182-FACILITADOR DE PROVISION DE LOS SERVICIOS",
"182-FISIOTERAPISTA DEC. 11-2021",
"182-FISIOTERAPISTA",
"182-GESTOR COMUNITARIO",
"182-GINECOLOGO (A) Y OBSTETRA DEC. 11-2021",
"182-GINECOLOGO (A) Y OBSTETRA",
"182-GINECOLOGO (A)",
"182-INSPECTOR DE SANEAMIENTO AMBIENTAL",
"182-LABORATORISTA DEC. 11-2021",
"182-MEDICO AMBULATORIO",
"182-MEDICO ANESTESIOLOGO DEC. 11-2021",
"182-MEDICO ANESTESIOLOGO",
"182-MEDICO DE CONSULTA DEC. 11-2021",
"182-MEDICO DE CONSULTA",
"182-MEDICO DE CUIDADOS INTENSIVOS",
"182-MEDICO FACILITADOR INSTITUCIONAL",
"182-MEDICO GENERAL DEC. 11-2021",
"182-MEDICO GENERAL",
"182-MEDICO GENETISTA",
"182-MEDICO INFECTOLOGO",
"182-MEDICO INTERNISTA DEC. 11-2021",
"182-MEDICO INTERNISTA",
"182-MEDICO PATOLOGO",
"182-MEDICO PEDIATRA DEC. 11-2021",
"182-MEDICO PEDIATRA",
"182-MEDICO PSIQUIATRA",
"182-MEDICO TRAUMATOLOGO",
"182-MEDICO TURNISTA DEC. 11-2021",
"182-MEDICO TURNISTA",
"182-MEDICO UROLOGO",
"182-NEFROLOGO",
"182-NEUROCIRUJANO",
"182-NEUROLOGO",
"182-NUTRICIONISTA DE SERVICIOS DE SALUD DEC. 11-2021",
"182-NUTRICIONISTA DE SERVICIOS DE SALUD",
"182-ODONTOLOGO (A)",
"182-OFTALMOLOGO",
"182-OTORRINOLARINGOLOGO",
"182-QUIMICO (A) BIOLOGO (A)",
"182-QUIMICO (A) FARMACEUTICO (A)",
"182-QUIMICO BIOLOGO DEC. 11-2021",
"182-QUIMICO BIOLOGO",
"182-QUIMICO FARMACEUTICO DEC. 11-2021",
"182-QUIMICO FARMACEUTICO",
"182-RASTREADOR",
"182-SERVICIO DE MONITOREO DE SALUD PARA LA ORGANIZACION COMUNITARIA  ",
"182-SERVICIO MEDICO TRAUMATOLOGO Y ORTOPEDISTA",
"182-SERVICIOS PROFESIONALES DE PSICOLOGIA DEC. 11-2021",
"182-SERVICIOS PROFESIONALES DE PSICOLOGIA",
"182-SERVICIOS TECNICOS EN ANALISIS DE MEDIOS DE CULTIVO",
"182-SERVICIOS TECNICOS EN EL AREA DE RESPONSABILIDAD MEDICA DEC. 11-2021",
"182-SERVICIOS TECNICOS EN EL AREA DE RESPONSABILIDAD MEDICA",
"182-TECNICO ANALISTA FISICO QUIMICO DE ALIMENTOS",
"182-TECNICO DE DIAGNOSTICO DE MALARIA",
"182-TECNICO DE ENLACE DE SALUD REPRODUCTIVA",
"182-TECNICO DE MICROBIOLOGIA Y MEDICAMENTOS",
"182-TECNICO DE RAYOS X DEC. 11-2021",
"182-TECNICO DE RAYOS X",
"182-TECNICO DENTAL",
"182-TECNICO ECOCARDIOGRAFISTA",
"182-TECNICO EN ANESTESIA",
"182-TECNICO EN ATENCION PSICOLOGICA",
"182-TECNICO EN BANCO DE SANGRE",
"182-TECNICO EN CENTELLOGRAFIA",
"182-TECNICO EN CONTROL VECTORIAL",
"182-TECNICO EN ENTOMOLOGIA",
"182-TECNICO EN FISIOTERAPIA DEC. 11-2021",
"182-TECNICO EN FISIOTERAPIA",
"182-TECNICO EN HEMODIALISIS",
"182-TECNICO EN LABORATORIO DEC. 11-2021",
"182-TECNICO EN LABORATORIO",
"182-TECNICO EN SALUD RURAL",
"182-TECNICO EN TERAPIA RESPIRATORIA DEC. 11-2021",
"182-TECNICO EN TERAPIA RESPIRATORIA",
"182-TECNICO FISICO QUIMICO DE MEDICAMENTOS",
"182-TECNICO NORMATIVO PROGRAMA NACIONAL DE SALUD REPRODUCTIVA",
"182-TERAPISTA DE LENGUAJE",
"182-TERAPISTA OCUPACIONAL");

var Terminos_RENGLON_183 = new Array ("-",
"183-ASESOR (A) LEGAL",
"183-ASESOR LEGAL",
"183-ASISTENTE JURIDICO",
"183-SERVICIOS DE ABOGADO - NOTARIO");

var Terminos_RENGLON_184 = new Array ("-",
"184-ASESOR FINANCIERO",
"184-SERVICIOS PROFESIONALES DE AUDITORIA");

var Terminos_RENGLON_185 = new Array ("-",
"185-CATEDRATICO (A) ACADEMICO",
"185-CATEDRATICO (A) DE PRACTICA DEL AREA DE ENFERMERIA",
"185-SERVICIOS DE DOCENCIA EN ENFERMERIA");

var Terminos_RENGLON_186 = new Array ("-", 
"186-ASISTENTE DE INFORMATICA",
"186-AUXILIAR DE INFORMATICA",
"186-TECNICO DE  DATOS DE INFORMATICA");

var Terminos_RENGLON_187 = new Array ("NO APLICA");

var Terminos_RENGLON_188 = new Array ("-",
"188-ANALISTA PLANIFICADOR EN INFRAESTRUCTURA",
"188-ASISTENTE DEL PROFESIONAL DE PLANIFICACION Y SUPERVISION DE INFRAESTRUCTURA",
"188-FACILITADOR (A) DE PROYECTOS DE INFRAESTRUCTURA Y CONSTRUCCION",
"188-FACILITADOR DE PROYECTOS DE INFRAESTRUCTURA Y CONSTRUCCION",
"188-REVISION DE PROYECTOS INFRAESTRUCTURA");

var Terminos_RENGLON_189 = new Array ("-",
"189-ANALISTA DE COMPRAS",
"189-ANALISTA DE PRESUPUESTO",
"189-ANALISTA DE PROVISION DE LOS SERVICIOS",
"189-ANALISTA DE RECURSOS HUMANOS ",
"189-ANALISTA DE RECURSOS HUMANOS",
"189-ANALISTA DE REGISTROS DE ALIMENTOS",
"189-ANALISTA FINANCIERO",
"189-ASESOR (A) DE PROMOCION",
"189-ASESOR (A) PARA IMPLEMENTACION DE SISTEMAS",
"189-ASISTENTE ADMINISTRATIVO DE BODEGA DEC. 11-2021",
"189-ASISTENTE ADMINISTRATIVO DE PRESUPUESTO DE LABORATORIO NACIONAL DE SALUD",
"189-ASISTENTE ADMINISTRATIVO DEC. 11-2021",
"189-ASISTENTE ADMINISTRATIVO FINANCIERO",
"189-ASISTENTE ADMINISTRATIVO PROFESIONAL",
"189-ASISTENTE ADMINISTRATIVO UNIDAD DE AGUA",
"189-ASISTENTE ADMINISTRATIVO",
"189-ASISTENTE DE ATENCION AL USUARIO DEC. 11-2021",
"189-ASISTENTE DE COMUNICACION SOCIAL",
"189-ASISTENTE DE CONTABILIDAD",
"189-ASISTENTE DE DIRECCION",
"189-ASISTENTE DE INGENIERIA Y MANTENIMIENTO",
"189-ASISTENTE DE LOGISTICA DEC. 11-2021",
"189-ASISTENTE DE MANTENIMIENTO ",
"189-ASISTENTE DE MANTENIMIENTO DEC. 11-2021",
"189-ASISTENTE DE MANTENIMIENTO",
"189-ASISTENTE DE PROGRAMAS DE MEDIO AMBIENTE",
"189-ASISTENTE DE PROMOCION DE LA SALUD",
"189-ASISTENTE DE REGISTRO ACADEMICO",
"189-ASISTENTE DE REGISTROS SANITARIOS",
"189-ASISTENTE DE SERVICIOS GENERALES DEC. 11-2021",
"189-ASISTENTE DE SERVICIOS GENERALES",
"189-ASISTENTE DEL DESPACHO MINISTERIAL",
"189-ASISTENTE DEL FACILITADOR DE RECURSOS HUMANOS",
"189-ASISTENTE EN PROMOCION DE LA SALUD",
"189-AUXILIAR ADMINISTRATIVO DEC. 11-2021",
"189-AUXILIAR DE ALMACEN DEC. 11-2021",
"189-AUXILIAR DE ALMACEN",
"189-AUXILIAR DE ARCHIVO",
"189-AUXILIAR DE ATENCION AL USUARIO",
"189-AUXILIAR DE AUDITORIA",
"189-AUXILIAR DE BODEGA",
"189-AUXILIAR DE CLIMA ORGANIZACIONAL",
"189-AUXILIAR DE CONTABILIDAD",
"189-AUXILIAR DE ESTADISTICA",
"189-AUXILIAR DE FARMACIA DEC. 11-2021",
"189-AUXILIAR DE FARMACIA",
"189-AUXILIAR DE HOSPITAL DEC. 11-2021",
"189-AUXILIAR DE HOSPITAL",
"189-AUXILIAR DE INFORMACION (RECEPCION)",
"189-AUXILIAR DE INFORMATICA",
"189-AUXILIAR DE INSPECCION SANITARIA",
"189-AUXILIAR DE INVENTARIOS",
"189-AUXILIAR DE MANTENIMIENTO ",
"189-AUXILIAR DE MANTENIMIENTO DE MATERIAL VOLUMETRICO DE LABORATORIO NACIONAL DE SALUD",
"189-AUXILIAR DE MANTENIMIENTO DEC. 11-2021",
"189-AUXILIAR DE MANTENIMIENTO",
"189-AUXILIAR DE MONITOREO DE SERVICIOS",
"189-AUXILIAR DE PRESUPUESTO",
"189-AUXILIAR DE REGISTRO ACADEMICO",
"189-AUXILIAR DE REGISTROS MEDICOS DEC. 11-2021",
"189-AUXILIAR DE REGISTROS MEDICOS",
"189-DIGITADOR DE LABORATORIO CLINICO DEC. 11-2021",
"189-DIGITADOR DEC. 11-2021",
"189-DIGITADOR SIGSA WEB DEC. 11-2021",
"189-DIGITADOR SIGSA WEB",
"189-DIGITADOR",
"189-DISEÑADOR (A) GRAFICO (A)",
"189-DISEÑADOR (A) GRAFICO",
"189-EDUCADOR (A) EN SALUD Y NUTRICION",
"189-FACILITADOR (A) ADMINISTRATIVO FINANCIERO",
"189-FACILITADOR (A) DE ATENCION AL USUARIO",
"189-FACILITADOR (A) DE AUTORIZACIONES SANITARIAS",
"189-FACILITADOR (A) DE DIRECCION",
"189-FACILITADOR (A) DE INFORMACION, EDUCACION Y COMUNICACION DE MALARIA",
"189-FACILITADOR (A) DE MANTENIMIENTO",
"189-FACILITADOR (A) DE PLANIFICACION ESTRATEGICA",
"189-FACILITADOR (A) DE PROCESOS DE FORMACION EN FARMACIA",
"189-FACILITADOR (A) DE PROGRAMA DE MEDIO AMBIENTE",
"189-FACILITADOR (A) DE RECURSOS HUMANOS",
"189-FACILITADOR (A) DE SANEAMIENTO AMBIENTAL",
"189-FACILITADOR (A) LOCAL DE MALARIA",
"189-FACILITADOR (A) NORMATIVO DE LOGISTICA DE INSUMOS AFINES A SALUD REPRODUCTIVA Y PLANIFICACION FAMILIAR",
"189-FACILITADOR (A) SANEAMIENTO AMBIENTAL",
"189-FACILITADOR (A) TECNICO (A) DEL COMPONENTE DE EDUCACION INTEGRAL EN SEXUALIDAD",
"189-FACILITADOR (A)TECNICO (A) DE PROCESOS DEL COMPONENTE DE PATERNIDAD Y MATERNIDAD RESPONSABLE",
"189-FACILITADOR DE ATENCION AL USUARIO",
"189-FISICO RADIOLOGO",
"189-GESTOR AMBIENTAL",
"189-GESTOR COMUNITARIO DEC. 11-2021",
"189-GESTOR COMUNITARIO",
"189-GINECOLOGO (A)",
"189-MONITOR (A) DE CAMPO",
"189-PSICOLOGO (A) INDUSTRIAL",
"189-RASTREADOR DEC. 11-2021",
"189-RASTREADOR",
"189-SERVICIO DE CONDUCCION DE VEHICULOS",
"189-SERVICIOS DE CONDUCCION DE VEHICULOS DEC. 11-2021",
"189-SERVICIOS DE CONDUCCION DE VEHICULOS",
"189-SERVICIOS PARA EL DESARROLLO E IMPLEMENTACION DE PROCESOS INFORMATICOS",
"189-SERVICIOS PROFESIONALES EN IMPLEMENTACION DE PROCESOS DE INFORMATIVOS Y PROMOCIONALES",
"189-SERVICIOS PROFESIONALES PARA LA ELABORACION, ANALISIS Y EVALUACION EN PROCESOS ADMINISTRATIVOS",
"189-SERVICIOS TECNICOS DE ACOMPAÑAMIENTO EN PROCESOS Y ACTIVIDADES DE SUPERVISION DE FARMACIA",
"189-SERVICIOS TECNICOS DE LOGISTICA PARA EL MANEJO E INSTALACION DE EQUIPO AUDIOVISUAL EN EVENTOS",
"189-SERVICIOS TECNICOS EN GESTION DOCUMENTAL",
"189-SERVICIOS TECNICOS EN LOGISTICA DE MANTENIMIENTO INTERNO INSTITUCIONAL",
"189-SERVICIOS TECNICOS EN LOGISTICA DE TRANSPORTE INTERNO INSTITUCIONAL",
"189-SERVICIOS TECNICOS PARA DIGITALIZACION",
"189-SERVICIOS TECNICOS PARA LA ELABORACION, ANALISIS Y EVALUACION  RELACIONADOS A PROCESOS DEL RECURSO HUMANO",
"189-SERVICIOS TECNICOS PARA LA ELABORACION, ANALISIS Y EVALUACION EN PROCESOS FINANCIEROS",
"189-SERVICIOS TECNICOS PARA LA GESTION DE INSUMOS, DISEÑO, LINEAMIENTOS Y LOGISTICA EN LA RECEPCION Y ENTREGA DE BIENES Y SUMINISTROS",
"189-TECNICO ANALISTA EN REDES Y TELECOMUNICACIONES",
"189-TECNICO DE DIAGNOSTICO DE MALARIA",
"189-TECNICO DE INFORMACION, EDUCACION Y COMUNICACION DE MALARIA",
"189-TECNICO DE INFORMATICA Y SISTEMAS DE INFORMACION GEOGRAFICA DE MALARIA",
"189-TECNICO DE PROMOCION DE MALARIA",
"189-TECNICO EN CONTROL VECTORIAL",
"189-TECNICO EN PLANIFICACION Y COORDINACION EN EL CAMPO DE MALARIA",
"189-TECNICO EN SALUD RURAL",
"189-TECNICO EN TRABAJO SOCIAL DEC. 11-2021",
"189-TECNICO EN TRABAJO SOCIAL",
"189-TECNICO POLIFUNCIONAL PROGRAMA DE MALARIA",
"189-TECNICO PROTESISTA Y ORTESISTA",
"189-TRABAJADOR (A) SOCIAL");


// ---------------------------------------------2) crear una funcion que permita ejecutar el cambio dinamico---------------------------------------------

function cambias(){
    var Renglon;
    //Se toma el vamor de la "cosa seleccionada"
    Renglon = document.formulario1.Renglon[document.formulario1.Renglon.selectedIndex].value;
    //se chequea si la "cosa" esta definida
    if(Renglon!=0){
        //selecionamos las cosas Correctas
        mis_opts=eval("Terminos_" + Renglon);
        //se calcula el numero de cosas
        num_opts=mis_opts.length;
        //marco el numero de opt en el select
        document.formulario1.Terminos.length = num_opts;
        //para cada opt del array, la pongo en el select
        for(i=0; i<num_opts; i++){
            document.formulario1.Terminos.options[i].value=mis_opts[i];
            document.formulario1.Terminos.options[i].text=mis_opts[i];
        }
        }else{
            //si no habia ninguna opt seleccionada, elimino las cosas del select
            document.formulario1.opt.length = 1;
            //ponemos un guion en la unica opt que he dejado
            document.formulario1.opt.options[0].value="-";
            document.formulario1.opt.options[0].text="-";
        }
        //hacer un reset de las opts
        document.formulario1.Especialidad.options[0].selected = true;
        
    }





//--------------------------------------------- 1) Definir Las Variables Departamento y Municiío Correspondintes---------------------------------------------
var Municipio_GUATEMALA = new Array("-",
"GUATEMALA",
"SANTA CATARINA PINULA",
"SAN JOSÉ PINULA",
"SAN JOSÉ DEL GOLFO",
"PALENCIA",
"CHINAUTLA",
"SAN PEDRO AYAMPUC",
"MIXCO",
"SAN PEDRO SACATEPÉQUEZ",
"SAN JUAN SACATEPÉQUEZ",
"SAN RAYMUNDO",
"CHUARRANCHO",
"FRAIJANES",
"AMATITLÁN",
"VILLA NUEVA",
"VILLA CANALES",
"PETAPA");


var Municipio_EL_PROGRESO = new Array("-",
"GUASTATOYA",
"MORAZÁN",
"SAN AGUSTÍN ACASAGUASTLÁN",
"SAN CRISTÓBAL ACASAGUASTLÁN",
"EL JÍCARO",
"SANSARE",
"SANARATE",
"SAN ANTONIO LA PAZ");


var Municipio_SACATEPÉQUEZ = new Array("-",
"ANTIGUA GUATEMALA",
"JOCOTENANGO",
"PASTORES",
"SUMPANGO",
"SANTO DOMINGO XENACOJ",
"SANTIAGO SACATEPÉQUEZ",
"SAN BARTOLOMÉ MILPAS ALTAS",
"SAN LUCAS SACATEPÉQUEZ",
"SANTA LUCÍA MILPAS ALTAS",
"MAGDALENA MILPAS ALTAS",
"SANTA MARÍA DE JESÚS",
"CIUDAD VIEJA",
"SAN MIGUEL DUEÑAS",
"ALOTENANGO",
"SAN ANTONIO AGUAS CALIENTES",
"SANTA CATARINA BARAHONA");


var Municipio_CHIMALTENANGO = new Array("-",
"CHIMALTENANGO",
"SAN JOSÉ POAQUIL",
"SAN MARTÍN JILOTEPEQUE",
"COMALAPA",
"SANTA APOLONIA",
"TECPÁN GUATEMALA",
"PATZÚN",
"POCHUTA",
"PATZICÍA",
"SANTA CRUZ BALANYÁ",
"ACATENANGO",
"YEPOCAPA",
"SAN ANDRÉS ITZAPA",
"PARRAMOS",
"ZARAGOZA",
"EL TEJAR");


var Municipio_ESCUINTLA = new Array("-",
"ESCUINTLA",
"SANTA LUCÍA COTZUMALGUAPA",
"LA DEMOCRACIA",
"SIQUINALÁ",
"MASAGUA",
"TIQUISATE",
"LA GOMERA",
"GUANAGAZAPA",
"SAN JOSÉ",
"IZTAPA",
"PALÍN",
"SAN VICENTE PACAYA",
"NUEVA CONCEPCIÓN");


var Municipio_SANTA_ROSA = new Array("-",
"CUILAPA",
"BARBERENA",
"SANTA ROSA DE LIMA",
"CASILLAS",
"SAN RAFAEL LAS FLORES",
"ORATORIO",
"SAN JUAN TECUACO",
"CHIQUIMULILLA",
"TAXISCO",
"SANTA MARÍA IXHUATÁN",
"GUAZACAPÁN",
"SANTA CRUZ NARANJO",
"PUEBLO NUEVO VIÑAS",
"NUEVA SANTA ROSA");


var Municipio_SOLOLÁ = new Array("-",
"SOLOLÁ",
"SAN JOSÉ CHACAYÁ",
"SANTA MARÍA VISITACIÓN",
"SANTA LUCÍA UTATLÁN",
"NAHUALÁ",
"SANTA CATARINA IXTAHUACÁN",
"SANTA CLARA LA LAGUNA",
"CONCEPCIÓN",
"SAN ANDRÉS SEMETABAJ",
"PANAJACHEL",
"SANTA CATARINA PALOPÓ",
"SAN ANTONIO PALOPÓ",
"SAN LUCAS TOLIMÁN",
"SANTA CRUZ LA LAGUNA",
"SAN PABLO LA LAGUNA",
"SAN MARCOS LA LAGUNA",
"SAN JUAN LA LAGUNA",
"SAN PEDRO LA LAGUNA",
"SANTIAGO ATITLÁN");


var Municipio_TOTONICAPÁN = new Array("-",
"TOTONICAPÁN",
"SAN CRISTÓBAL TOTONICAPÁN",
"SAN FRANCISCO EL ALTO",
"SAN ANDRÉS XECUL",
"MOMOSTENANGO",
"SANTA MARÍA CHIQUIMULA",
"SANTA LUCÍA LA REFORMA",
"SAN BARTOLO");


var Municipio_QUETZALTENANGO = new Array("-",
"QUETZALTENANGO",
"SALCAJÁ",
"OLINTEPEQUE",
"SAN CARLOS SIJA",
"SIBILIA",
"CABRICÁN",
"CAJOLÁ",
"SAN MIGUEL SIGUILÁ",
"OSTUNCALCO",
"SAN MATEO",
"CONCEPCIÓN CHIQUIRICHAPA",
"SAN MARTÍN SACATEPÉQUEZ",
"ALMOLONGA",
"CANTEL",
"HUITÁN",
"ZUNIL",
"COLOMBA",
"SAN FRANCISCO LA UNIÓN",
"EL PALMAR",
"COATEPEQUE",
"GÉNOVA",
"FLORES COSTA CUCA",
"LA ESPERANZA",
"PALESTINA DE LOS ALTOS");


var Municipio_SUCHITEPÉQUEZ = new Array("-",
"MAZATENANGO",
"CUYOTENANGO",
"SAN FRANCISCO ZAPOTITLÁN",
"SAN BERNARDINO",
"SAN JOSÉ EL IDOLO",
"SANTO DOMINGO SUCHITEPÉQUEZ",
"SAN LORENZO",
"SAMAYAC",
"SAN PABLO JOCOPILAS",
"SAN ANTONIO SUCHITEPÉQUEZ",
"SAN MIGUEL PANÁN",
"SAN GABRIEL",
"CHICACAO",
"PATULUL",
"SANTA BÁRBARA",
"SAN JUAN BAUTISTA",
"SANTO TOMÁS LA UNIÓN",
"ZUNILITO",
"PUEBLO NUEVO",
"RÍO BRAVO",
"SAN JOSÉ LA MÁQUINA");


var Municipio_RETALHULEU = new Array("-",
"RETALHULEU",
"SAN SEBASTIÁN",
"SANTA CRUZ MULUÁ",
"SAN MARTÍN ZAPOTITLÁN",
"SAN FELIPE",
"SAN ANDRÉS VILLA SECA",
"CHAMPERICO",
"NUEVO SAN CARLOS",
"EL ASINTAL");


var Municipio_SAN_MARCOS = new Array("-",
"SAN MARCOS",
"SAN PEDRO SACATEPÉQUEZ",
"SAN ANTONIO SACATEPÉQUEZ",
"COMITANCILLO",
"SAN MIGUEL IXTAHUACÁN",
"CONCEPCIÓN TUTUAPA",
"TACANÁ",
"SIBINAL",
"TAJUMULCO",
"TEJUTLA",
"SAN RAFAEL PIÉ DE LA CUESTA",
"NUEVO PROGRESO",
"EL TUMBADOR",
"EL RODEO",
"MALACATÁN",
"CATARINA",
"AYUTLA",
"OCÓS",
"SAN PABLO",
"EL QUETZAL",
"LA REFORMA",
"PAJAPITA",
"IXCHIGUÁN",
"SAN JOSÉ OJETENÁN",
"SAN CRISTÓBAL CUCHO",
"SIPACAPA",
"ESQUIPULAS PALO GORDO",
"RÍO BLANCO",
"SAN LORENZO",
"LA BLANCA");


var Municipio_HUEHUETENANGO = new Array("-",
"HUEHUETENANGO",
"CHIANTLA",
"MALACATANCITO",
"CUILCO",
"NENTÓN",
"SAN PEDRO NECTA",
"JACALTENANGO",
"SOLOMA",
"IXTAHUACÁN",
"SANTA BÁRBARA",
"LA LIBERTAD",
"LA DEMOCRACIA",
"SAN MIGUEL ACATÁN",
"SAN RAFAEL LA INDEPENDENCIA",
"TODOS SANTOS CUCHUMATÁN",
"SAN JUAN ATITÁN",
"SANTA EULALIA",
"SAN MATEO IXTATÁN",
"COLOTENANGO",
"SAN SEBASTIÁN HUEHUETENANGO",
"TECTITÁN",
"TETAPAN",
"CONCEPCIÓN HUISTA",
"SAN JUAN IXCOY",
"SAN ANTONIO HUISTA",
"SAN SEBASTIÁN COATÁN",
"BARILLAS",
"AGUACATÁN",
"SAN RAFAEL PETZAL",
"SAN GASPAR IXCHIL",
"SANTIAGO CHIMALTENANGO",
"SANTA ANA HUISTA",
"UNIÓN CANTINIL");


var Municipio_QUICHÉ = new Array("-",
"SANTA CRUZ DEL QUICHÉ",
"CHICHÉ",
"CHINIQUE",
"ZACUALPA",
"CHAJUL",
"CHICHICASTENANGO",
"PATZITÉ",
"SAN ANTONIO ILOTENANGO",
"SAN PEDRO JOCOPILAS",
"CUNÉN",
"SAN JUAN COTZAL",
"JOYABAJ",
"NEBAJ",
"SAN ANDRÉS SAJCABAJÁ",
"USPANTÁN",
"SACAPULAS",
"SAN BARTOLOMÉ JOCOTENANGO",
"CANILLÁ",
"CHICAMÁN",
"IXCÁN",
"PACHALUM");


var Municipio_BAJA_VERAPAZ = new Array("-",
"SALAMÁ",
"SAN MIGUEL CHICAJ",
"RABINAL",
"CUBULCO",
"GRANADOS",
"EL CHOL",
"SAN JERÓNIMO",
"PURULHÁ");


var Municipio_ALTA_VERAPAZ = new Array("-",
"COBÁN",
"SANTA CRUZ VERAPAZ",
"SAN CRISTÓBAL VERAPAZ",
"TACTIC",
"TAMAHÚ",
"TUCURÚ",
"PANZÓS",
"SENAHÚ",
"SAN PEDRO CARCHÁ",
"SAN JUAN CHAMELCO",
"LANQUÍN",
"CAHABÓN",
"CHISEC",
"CHAHAL",
"FRAY BARTOLOMÉ DE LAS CASAS",
"SANTA CATALINA LA TINTA",
"RAXRUHÁ");


var Municipio_PETÉN = new Array("-",
"FLORES",
"SAN JOSÉ",
"SAN BENITO",
"SAN ANDRÉS",
"LA LIBERTAD",
"SAN FRANCISCO",
"SANTA ANA",
"DOLORES",
"SAN LUIS",
"SAYAXCHÉ",
"MELCHOR DE MENCOS",
"POPTÚN",
"LAS CRUCES",
"EL CHAL");


var Municipio_IZABAL = new Array("-",
"PUERTO BARRIOS",
"LIVINGSTON",
"EL ESTOR",
"MORALES",
"LOS AMATES");


var Municipio_ZACAPA = new Array("-",
"ZACAPA",
"ESTANZUELA",
"RÍO HONDO",
"GUALÁN",
"TECULUTÁN",
"USUMATLÁN",
"CABAÑAS",
"SAN DIEGO",
"LA UNIÓN",
"HUITÉ",
"SAN JORGE");


var Municipio_CHIQUIMULA = new Array("-",
"CHIQUIMULA",
"SAN JOSÉ LA ARADA",
"SAN JUAN ERMITA",
"JOCOTÁN",
"CAMOTÁN",
"OLOPA",
"ESQUIPULAS",
"CONCEPCIÓN LAS MINAS",
"QUETZALTEPEQUE",
"SAN JACINTO",
"IPALA");


var Municipio_JALAPA = new Array("-",
"JALAPA",
"SAN PEDRO PINULA",
"SAN LUIS JILOTEPEQUE",
"SAN MANUEL CHAPARRÓN",
"SAN CARLOS ALZATATE",
"MONJAS",
"MATAQUESCUINTLA");


var Municipio_JUTIAPA = new Array("-",
"JUTIAPA",
"EL PROGRESO",
"SANTA CATARINA MITA",
"AGUA BLANCA",
"ASUNCIÓN MITA",
"YUPILTEPEQUE",
"ATESCATEMPA",
"JEREZ",
"EL ADELANTO",
"ZAPOTITLÁN",
"COMAPA",
"JALPATAGUA",
"CONGUACO",
"MOYUTA",
"PASACO",
"SAN JOSÉ ACATEMPA",
"QUESADA");



// ---------------------------------------------2) crear una funcion que permita ejecutar el cambio dinamico---------------------------------------------

function cambiasss(){
    var Departamento;
    //Se toma el vamor de la "cosa seleccionada"
    Departamento = document.formulario1.Departamento[document.formulario1.Departamento.selectedIndex].value;
    //se chequea si la "cosa" esta definida
    if(Departamento!=0){
        //selecionamos las cosas Correctas
        mis_opts=eval("Municipio_" + Departamento);
        //se calcula el numero de cosas
        num_opts=mis_opts.length;
        //marco el numero de opt en el select
        document.formulario1.Municipio.length = num_opts;
        //para cada opt del array, la pongo en el select
        for(i=0; i<num_opts; i++){
            document.formulario1.Municipio.options[i].value=mis_opts[i];
            document.formulario1.Municipio.options[i].text=mis_opts[i];
        }
        }else{
            //si no habia ninguna opt seleccionada, elimino las cosas del select
            document.formulario1.opt.length = 1;
            //ponemos un guion en la unica opt que he dejado
            document.formulario1.opt.options[0].value="-";
            document.formulario1.opt.options[0].text="-";
        }
        //hacer un reset de las opts
        document.formulario1.Municipio.options[0].selected = true;
        
    }




    
//--------------------------------------------- 1) Definir Las Variables Educación Correspondintes---------------------------------------------

var NivelEdu_PRIMARIA = new Array ("-",
"PRIMERO",
"SEGUNDO",
"TERCERO",
"CUARTO",
"QUINTO",
"SEXTO");

var NivelEdu_SECUNDARIA = new Array ("-",
"PRIMERO BASICO",
"SEGUNDO BASICO",
"TERCERO BASICO");


var NivelEdu_DIVERSIFICADO = new Array ("-",
"BACH CON ORIENT.TECNICA OCUP. EN ELECTRICIDAD Y SOLDADURA",
"BACH EN CIENCIAS Y LETRAS POR MADUREZ CON ORIENT EN COMPU",
"BACH. EN CC Y LL CON ORIENT. OCUP. EN MECANICA AUTOMOTRIZ",
"BACH. EN CIENCIAS Y LETRAS CON ESPEC. EN MUSICA",
"BACH. INDUSTRIAL, PERITO EN ELECTRICIDAD Y MECANICA AUTOMOT.",
"BACH.IND.Y PER. EN ELECTRONICA,ELECTRICIDAD Y MEC.AUTOM.",
"BACHILLER EN CIENCIAS Y LETRAS CON ORIENTACION EN ELECTRICIDAD",
"BACHILLER INDUST.Y PERITO EN CONSTRUCC Y DIBUJO COMPUTARIZA",
"BACHILLER INDUSTRIAL CON ESPECIALIDAD EN BELLEZA",
"BACHILLER INDUSTRIAL Y PERITO EN CONSTRUCCION",
"BACHILLERATO BILINGUE EN CIENCIAS Y HUMANIDADES",
"BACHILLERATO EN ADMON INDUST. Y PERITO EN ALGUNA ESPEC.",
"BACHILLERATO EN ADMON. INDUSTRIAL Y P. DIBUJO CONSTRUCCION",
"BACHILLERATO EN CIENCAS Y LETRAS CON ORIENTACION EN HOTELERIA Y HOGAR",
"BACHILLERATO EN CIENCIAS DE LA COMUNICACION",
"BACHILLERATO EN CIENCIAS Y LETRAS",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN ARTES ESCENICAS",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN ARTES VISUALES",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN CIENCIAS BIOLOGICAS",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN COMPUTACION",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN DISEÑO GRAFICO",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN EDUCACION",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN EDUCACION DE ARTES PLASTICAS",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN EDUCACION DE PRODUCTIVIDAD Y DESARROLLO",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN EDUCACION FISICA",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN EDUCACION MUSICAL",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN FINANZAS Y ADMINISTRACION",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN GESTION DE OFICINAS",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN MECANICA AUTOMOTRIZ",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN MUSICA",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN PRODUCTIVIDAD Y EMPRENDIMIENTO",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN TEXTILES",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN TURISMO",
"BACHILLERATO EN CIENCIAS Y LETRAS POR MADUREZ",
"BACHILLERATO EN CIENCIAS Y LETRAS Y SECRETARIADO BILINGUE",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACIÓN EN CIENCIAS BIOLÓGICAS Y DIPLOMADO EN MEDICINA",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACIÓN EN MEDICINA",
"BACHILLERATO EN CIENCIAS Y LETRAS EN CIENCIAS DE LA SALUD",
"BACHILLERATO EN CIENCIAS DE LA SALUD",
"BACHILLERATO EN COMPUTACION",
"BACHILLERATO EN COMPUTACION CON ORIENTACION CIENTIFICA",
"BACHILLERATO EN COMPUTACION CON ORIENTACION COMERCIAL",
"BACHILLERATO EN CONSTRUCCION",
"BACHILLERATO EN CONSTRUCCION Y DIBUJO COMPUTARIZADO",
"BACHILLERATO EN COSMETOLOGIA",
"BACHILLERATO EN FISIOTERAPIA Y REHABILITACIÓN",
"BACHILLERATO EN DIBUJO TECNICO Y CONSTRUCION CON COMPUTACION",
"BACHILLERATO EN DIBUJO TECNICO Y DE CONSTRUCCION",
"BACHILLERATO EN DISEÑO DE INTERIORES",
"BACHILLERATO EN DISEÑO DE MODAS",
"BACHILLERATO EN DISEÑO GRAFICO",
"BACHILLERATO EN FILOSOFIA Y TEOLOGIA",
"BACHILLERATO EN HOTELERIA Y HOGAR",
"BACHILLERATO EN MERCADOTECNIA",
"BACHILLERATO EN TELECOMUNICACIONES",
"BACHILLERATO EN TURISMO",
"BACHILLERATO EN TURISMO CON ORIENTACION EN COMPUTACION",
"BACHILLERATO EN TURISMO ECOLOGICO",
"BACHILLERATO EN TURISMO Y ADMINISTRACION EN/DE HOTELES",
"BACHILLERATO EN TURISMO Y HOTELERIA",
"BACHILLERATO INDUS Y PERITO EN COSTURA INDUSTRIAL",
"BACHILLERATO INDUSTRIAL",
"BACHILLERATO INDUSTRIAL CON UNA ESPECIALIDAD",
"BACHILLERATO INDUSTRIAL Y PERITO CON ESP. EN DISEÑO DE MODAS",
"BACHILLERATO INDUSTRIAL Y PERITO CON ESPECIALIDAD EN COMPU.",
"BACHILLERATO INDUSTRIAL Y PERITO EN DIBUJO COMPUTARIZADO",
"BACHILLERATO INDUSTRIAL Y PERITO EN DIBUJO DE ARQUITECTURA E INGENIERIA",
"BACHILLERATO INDUSTRIAL Y PERITO EN DIBUJO DE CONSTRUCCION",
"BACHILLERATO INDUSTRIAL Y PERITO EN DISEÑO GRAFICO",
"BACHILLERATO INDUSTRIAL Y PERITO EN ELECTRICIDAD",
"BACHILLERATO INDUSTRIAL Y PERITO EN ELECTRONICA",
"BACHILLERATO INDUSTRIAL Y PERITO EN ENDEREZADO Y PINTURA",
"BACHILLERATO INDUSTRIAL Y PERITO EN INFORMATICA Y COMPUTACION",
"BACHILLERATO INDUSTRIAL Y PERITO EN MECANICA AUTOMOTRIZ",
"BACHILLERATO INDUSTRIAL Y PERITO EN MECANICA DE MANTENIMIENTO INDUSTRIAL",
"BACHTO. EN CIENCIAS Y LETRAS Y SECRET. BILG.(INGLES-ESPAÑOL)",
"MAGISTERIO DE EDUC. PREPRIMARIA CON ORIENT. A LA DEMOCRACIA",
"MAGISTERIO DE EDUCACION INFANTIL BILINGUE INTERCULTURAL",
"MAGISTERIO DE EDUCACION INFANTIL INTERCULTURAL",
"MAGISTERIO DE EDUCACION PREPRIMARIA BILINGUE ESPAÑOL-INGLES",
"MAGISTERIO DE EDUCACION PRIMARIA",
"MAGISTERIO DE EDUCACION PARA EL HOGAR",
"NORMAL PREPRIMARIA",
"NORMAL PREPRIMARIA BILINGUE",
"PERITO CONT. CON ESP. EN ADMON. DE PEQUEÑAS EMPRESAS AGRIC.",
"PERITO CONTADOR",
"PERITO CONTADOR BILINGUE (ESPAÑOL-INGLES)",
"PERITO CONTADOR CON ESPECIALIDAD EN COMPUTACION",
"PERITO CONTADOR CON ESPECIALIDAD EN COMPUTACION COMERCIAL",
"PERITO CONTADOR CON ORIENTACION ARTESANAL Y COMPUTACION",
"PERITO CONTADOR CON ORIENTACION COMERCIAL Y TURISMO",
"PERITO CONTADOR CON ORIENTACION EN ADMINISTRACION PORTUARIA",
"PERITO CONTADOR CON ORIENTACION EN COMPUTACION",
"PERITO CONTADOR CON ORIENTACION EN COMPUTACION COMERCIAL",
"PERITO CONTADOR EN COMPUTACION",
"PERITO EN ADMINISTRACION",
"PERITO EN ADMINISTRACION DE EMPRESAS",
"PERITO EN ADMINISTRACION DE EMPRESAS CON ORIENTACION EN COMP",
"PERITO EN ADMINISTRACION PUBLICA",
"PERITO EN ADMINISTRACION TURISTICA Y HOTELERA",
"PERITO EN ADMON. PUBLICA CON ORIENTACION EN COMPUTACION",
"PERITO EN CIEN DE LA COMUNI CON ESPECI EN TELE RADIO COMUNIC",
"PERITO EN CIENCIAS AMBIENTALES",
"PERITO EN CIENCIAS DE LA COMUNICACION",
"PERITO EN CIENCIAS TURISTICAS",
"PERITO EN COMPUTACION",
"PERITO EN COMPUTACION Y BACHILLERATO EN CIENCIAS Y LETRAS",
"PERITO EN DESARROLLO COMUNITARIO",
"PERITO EN DIBUJO DE CONSTRUCCION",
"PERITO EN DIBUJO TECNICO DE INGENIERIA Y ARQUITECTURA",
"PERITO EN DIBUJO TECNICO DE INGENIERIA Y ARQUITECTURA Y BACHILLERATO EN CIENCIAS Y LETRAS",
"PERITO EN ECOTURISMO",
"PERITO EN ELECTRICIDAD INDUSTRIAL",
"PERITO EN ELECTRONICA Y DISPOSITIVOS DIGITALES",
"PERITO EN GERENCIA ADMINISTRATIVA",
"PERITO EN INDUSTRIA DE ALIMENTOS",
"PERITO EN INFORMATICA",
"PERITO EN MECANICA AUTOMOTRIZ",
"PERITO EN MECANICA AUTOMOTRIZ Y BACHILLERATO EN CIENCIAS Y LETRAS",
"PERITO EN MECANICA GENERAL (TORNOS)",
"PERITO EN MERCADOTECNIA Y PUBLICIDAD",
"PERITO EN RELACIONES PUBLICAS EMPRESARIALES",
"PERITO EN TURISMO SUSTENTABLE",
"PERITO EN HIGIENE DENTAL",
"PERITO INDUSTRIAL",
"PERITO INDUSTRIAL CON ESPECIALIDAD EN DIBUJO TECNICO Y DE CONSTRUCCION",
"PERITO INDUSTRIAL CON ESPECIALIDAD EN MECANICA AUTOMOTRIZ",
"SECRET BILINGUE CON ORIENT EN IDIOMAS DIPLOMACIA Y REL INTER",
"SECRETARIADO BILINGUE / SECRETARIADO BILINGUE ESPAÑOL-INGLES",
"SECRETARIADO BILINGUE CON ESPECIALIDAD EN COMPUTACION",
"SECRETARIADO BILINGUE CON ORIENTA.TURISMO Y HOTELERIA",
"SECRETARIADO BILINGUE CON ORIENTACION EN COMPUTACION",
"SECRETARIADO BILINGUE ORIENTACION TURISMO-AGENCIA DE VIAJES",
"SECRETARIADO COMERCIAL",
"SECRETARIADO COMERCIAL CON ORIENTACION EN COMPUTACION",
"SECRETARIADO COMERCIAL Y OFICINISTA",
"SECRETARIADO EJECUTIVO",
"SECRETARIADO EJECUTIVO BILINGUE",
"SECRETARIADO EJECUTIVO BILINGUE CON ORIENT. EN MERC. Y PUB.",
"SECRETARIADO EJECUTIVO BILINGUE CON ORIENTA. COMP.COMERCIAL",
"SECRETARIADO EJECUTIVO EN COMPUTACION",
"SECRETARIADO EJECUTIVO EN ESPAÑOL",
"SECRETARIADO EJECUTIVO EN ESPAÑOL CON ORIENTACION EN COMPUT.",
"SECRETARIADO OFICINISTA CON ORIENTACION EN COMPUTACION",
"SECRETARIADO TRILINGUE CON ORIENT EN COMERCIO INTERNACIONAL",
"SECRETARIADO Y OFICINISTA",
"SECRETARIADO Y OFICINISTA CON ORIENTACION EN COMPUTACION",
"SECRETARIADO Y OFICINISTA CON ORIENTACION JURIDICA");



// ---------------------------------------------2) crear una funcion que permita ejecutar el cambio dinamico---------------------------------------------

function NivelEdus(){
    var Nivel_Academico;
    //Se toma el vamor de la "cosa seleccionada"
    Nivel_Academico = document.formulario1.Nivel_Academico[document.formulario1.Nivel_Academico.selectedIndex].value;
    //se chequea si la "cosa" esta definida
    if(Nivel_Academico!=0){
        //selecionamos las cosas Correctas
        mis_opts=eval("NivelEdu_" + Nivel_Academico);
        //se calcula el numero de cosas
        num_opts=mis_opts.length;
        //marco el numero de opt en el select
        document.formulario1.NivelEdu.length = num_opts;
        //para cada opt del array, la pongo en el select
        for(i=0; i<num_opts; i++){
            document.formulario1.NivelEdu.options[i].value=mis_opts[i];
            document.formulario1.NivelEdu.options[i].text=mis_opts[i];
        }
        }else{
            //si no habia ninguna opt seleccionada, elimino las cosas del select
            document.formulario1.opt.length = 1;
            //ponemos un guion en la unica opt que he dejado
            document.formulario1.opt.options[0].value="-";
            document.formulario1.opt.options[0].text="-";
        }
        //hacer un reset de las opts
        document.formulario1.NivelEdu.options[0].selected = true;
        
    }

//--------------------------------------------- 1) Definir Las Variables Colegio Profesional Correspondintes---------------------------------------------

var Colegio_GRADUADO = new Array ("-",
"Colegio De Abogados Y Notarios De Guatemala",
"Colegio De Arquitectos De Guatemala",
"Colegio De Contadores Públicos Y Auditores De Guatemala",
"Colegio De Economistas, Contadores Públicos Y Auditores Y Administradores De Empresas",
"Colegio De Farmacéuticos Y Químicos De Guatemala",
"Colegio De Ingenieros Agrónomos De Guatemala",
"Colegio De Ingenieros De Guatemala",
"Colegio De Ingenieros Químicos De Guatemala",
"Colegio De Médicos Veterinarios Y Zootecnistas De Guatemala",
"Colegio De Médicos Y Cirujanos De Guatemala",
"Colegio De Psicólogos De Guatemala",
"Colegio Estomatológico De Guatemala",
"Colegio Profesional De Humanidades De Guatemala",
"Colegio Profesional De Enfermería De Guatemala"
);


var Colegio_1er_TRIMESTRE = new Array("No Aplica");
var Colegio_2do_TRIMESTRE = new Array("No Aplica");
var Colegio_3er_TRIMESTRE = new Array("No Aplica");
var Colegio_4to_TRIMESTRE = new Array("No Aplica");
var Colegio_5to_TRIMESTRE = new Array("No Aplica");
var Colegio_6to_TRIMESTRE = new Array("No Aplica");
var Colegio_7mo_TRIMESTRE = new Array("No Aplica");
var Colegio_8avo_TRIMESTRE = new Array("No Aplica");
var Colegio_9no_TRIMESTRE = new Array("No Aplica");
var Colegio_10mo_TRIMESTRE = new Array("No Aplica");
var Colegio_11avo_TRIMESTRE = new Array("No Aplica");
var Colegio_12avo_TRIMESTRE = new Array("No Aplica");
var Colegio_13avo_TRIMESTRE = new Array("No Aplica");
var Colegio_14avo_TRIMESTRE = new Array("No Aplica");
var Colegio_15avo_TRIMESTRE = new Array("No Aplica");
var Colegio_16avo_TRIMESTRE = new Array("No Aplica");
var Colegio_17avo_TRIMESTRE = new Array("No Aplica");
var Colegio_18avo_TRIMESTRE = new Array("No Aplica");
var Colegio_19avo_TRIMESTRE = new Array("No Aplica");
var Colegio_20avo_TRIMESTRE = new Array("No Aplica");
var Colegio_21avo_TRIMESTRE = new Array("No Aplica");
var Colegio_22avo_TRIMESTRE = new Array("No Aplica");
var Colegio_23avo_TRIMESTRE = new Array("No Aplica");
var Colegio_24avo_TRIMESTRE = new Array("No Aplica");
var Colegio_1er_SEMESTRE = new Array("No Aplica");
var Colegio_2do_SEMESTRE = new Array("No Aplica");
var Colegio_3er_SEMESTRE = new Array("No Aplica");
var Colegio_4to_SEMESTRE = new Array("No Aplica");
var Colegio_5to_SEMESTRE = new Array("No Aplica");
var Colegio_6to_SEMESTRE = new Array("No Aplica");
var Colegio_7mo_SEMESTRE = new Array("No Aplica");
var Colegio_8vo_SEMESTRE = new Array("No Aplica");
var Colegio_9no_SEMESTRE = new Array("No Aplica");
var Colegio_10mo_SEMESTRE = new Array("No Aplica");
var Colegio_11avo_SEMESTRE = new Array("No Aplica");
var Colegio_12avo_SEMESTRE = new Array("No Aplica");
var Colegio_1er_AÑO = new Array("No Aplica");
var Colegio_2do_AÑO = new Array("No Aplica");
var Colegio_3er_AÑO = new Array("No Aplica");
var Colegio_4to_AÑO = new Array("No Aplica");
var Colegio_5to_AÑO = new Array("No Aplica");
var Colegio_6to_AÑO = new Array("No Aplica");
var Colegio_PENSUM_CERRADO = new Array("No Aplica");


// ---------------------------------------------2) crear una funcion que permita ejecutar el cambio dinamico---------------------------------------------

function NoColegioG(){
    var Grado;
    //Se toma el vamor de la "cosa seleccionada"
    Grado = document.formulario1.Grado[document.formulario1.Grado.selectedIndex].value;
    //se chequea si la "cosa" esta definida
    if(Grado!=0){
        //selecionamos las cosas Correctas
        mis_opts=eval("Colegio_" + Grado);
        //se calcula el numero de cosas
        num_opts=mis_opts.length;
        //marco el numero de opt en el select
        document.formulario1.Colegio.length = num_opts;
        //para cada opt del array, la pongo en el select
        for(i=0; i<num_opts; i++){
            document.formulario1.Colegio.options[i].value=mis_opts[i];
            document.formulario1.Colegio.options[i].text=mis_opts[i];
        }
        }else{
            //si no habia ninguna opt seleccionada, elimino las cosas del select
            document.formulario1.opt.length = 1;
            //ponemos un guion en la unica opt que he dejado
            document.formulario1.opt.options[0].value="-";
            document.formulario1.opt.options[0].text="-";
        }
        //hacer un reset de las opts
        document.formulario1.Colegio.options[0].selected = true;
        
    }


//--------------------------------------------- 1) Definir Las Variables Departamento y Municiío Correspondintes---------------------------------------------
var MuniLabol_GUATEMALA = new Array("-",
"GUATEMALA",
"SANTA CATARINA PINULA",
"SAN JOSÉ PINULA",
"SAN JOSÉ DEL GOLFO",
"PALENCIA",
"CHINAUTLA",
"SAN PEDRO AYAMPUC",
"MIXCO",
"SAN PEDRO SACATEPÉQUEZ",
"SAN JUAN SACATEPÉQUEZ",
"SAN RAYMUNDO",
"CHUARRANCHO",
"FRAIJANES",
"AMATITLÁN",
"VILLA NUEVA",
"VILLA CANALES",
"PETAPA",
);


var MuniLabol_EL_PROGRESO = new Array("-",
"GUASTATOYA",
"MORAZÁN",
"SAN AGUSTÍN ACASAGUASTLÁN",
"SAN CRISTÓBAL ACASAGUASTLÁN",
"EL JÍCARO",
"SANSARE",
"SANARATE",
"SAN ANTONIO LA PAZ",
);


var MuniLabol_SACATEPÉQUEZ = new Array("-",
"ANTIGUA GUATEMALA",
"JOCOTENANGO",
"PASTORES",
"SUMPANGO",
"SANTO DOMINGO XENACOJ",
"SANTIAGO SACATEPÉQUEZ",
"SAN BARTOLOMÉ MILPAS ALTAS",
"SAN LUCAS SACATEPÉQUEZ",
"SANTA LUCÍA MILPAS ALTAS",
"MAGDALENA MILPAS ALTAS",
"SANTA MARÍA DE JESÚS",
"CIUDAD VIEJA",
"SAN MIGUEL DUEÑAS",
"ALOTENANGO",
"SAN ANTONIO AGUAS CALIENTES",
"SANTA CATARINA BARAHONA",
);


var MuniLabol_CHIMALTENANGO = new Array("-",
"CHIMALTENANGO",
"SAN JOSÉ POAQUIL",
"SAN MARTÍN JILOTEPEQUE",
"COMALAPA",
"SANTA APOLONIA",
"TECPÁN GUATEMALA",
"PATZÚN",
"POCHUTA",
"PATZICÍA",
"SANTA CRUZ BALANYÁ",
"ACATENANGO",
"YEPOCAPA",
"SAN ANDRÉS ITZAPA",
"PARRAMOS",
"ZARAGOZA",
"EL TEJAR",
);


var MuniLabol_ESCUINTLA = new Array("-",
"ESCUINTLA",
"SANTA LUCÍA COTZUMALGUAPA",
"LA DEMOCRACIA",
"SIQUINALÁ",
"MASAGUA",
"TIQUISATE",
"LA GOMERA",
"GUANAGAZAPA",
"SAN JOSÉ",
"IZTAPA",
"PALÍN",
"SAN VICENTE PACAYA",
"NUEVA CONCEPCIÓN",
);


var MuniLabol_SANTA_ROSA = new Array("-",
"CUILAPA",
"BARBERENA",
"SANTA ROSA DE LIMA",
"CASILLAS",
"SAN RAFAEL LAS FLORES",
"ORATORIO",
"SAN JUAN TECUACO",
"CHIQUIMULILLA",
"TAXISCO",
"SANTA MARÍA IXHUATÁN",
"GUAZACAPÁN",
"SANTA CRUZ NARANJO",
"PUEBLO NUEVO VIÑAS",
"NUEVA SANTA ROSA",
);


var MuniLabol_SOLOLÁ = new Array("-",
"SOLOLÁ",
"SAN JOSÉ CHACAYÁ",
"SANTA MARÍA VISITACIÓN",
"SANTA LUCÍA UTATLÁN",
"NAHUALÁ",
"SANTA CATARINA IXTAHUACÁN",
"SANTA CLARA LA LAGUNA",
"CONCEPCIÓN",
"SAN ANDRÉS SEMETABAJ",
"PANAJACHEL",
"SANTA CATARINA PALOPÓ",
"SAN ANTONIO PALOPÓ",
"SAN LUCAS TOLIMÁN",
"SANTA CRUZ LA LAGUNA",
"SAN PABLO LA LAGUNA",
"SAN MARCOS LA LAGUNA",
"SAN JUAN LA LAGUNA",
"SAN PEDRO LA LAGUNA",
"SANTIAGO ATITLÁN",
);


var MuniLabol_TOTONICAPÁN = new Array("-",
"TOTONICAPÁN",
"SAN CRISTÓBAL TOTONICAPÁN",
"SAN FRANCISCO EL ALTO",
"SAN ANDRÉS XECUL",
"MOMOSTENANGO",
"SANTA MARÍA CHIQUIMULA",
"SANTA LUCÍA LA REFORMA",
"SAN BARTOLO",
);


var MuniLabol_QUETZALTENANGO = new Array("-",
"QUETZALTENANGO",
"SALCAJÁ",
"OLINTEPEQUE",
"SAN CARLOS SIJA",
"SIBILIA",
"CABRICÁN",
"CAJOLÁ",
"SAN MIGUEL SIGUILÁ",
"OSTUNCALCO",
"SAN MATEO",
"CONCEPCIÓN CHIQUIRICHAPA",
"SAN MARTÍN SACATEPÉQUEZ",
"ALMOLONGA",
"CANTEL",
"HUITÁN",
"ZUNIL",
"COLOMBA",
"SAN FRANCISCO LA UNIÓN",
"EL PALMAR",
"COATEPEQUE",
"GÉNOVA",
"FLORES COSTA CUCA",
"LA ESPERANZA",
"PALESTINA DE LOS ALTOS",
);


var MuniLabol_SUCHITEPÉQUEZ = new Array("-",
"MAZATENANGO",
"CUYOTENANGO",
"SAN FRANCISCO ZAPOTITLÁN",
"SAN BERNARDINO",
"SAN JOSÉ EL IDOLO",
"SANTO DOMINGO SUCHITEPÉQUEZ",
"SAN LORENZO",
"SAMAYAC",
"SAN PABLO JOCOPILAS",
"SAN ANTONIO SUCHITEPÉQUEZ",
"SAN MIGUEL PANÁN",
"SAN GABRIEL",
"CHICACAO",
"PATULUL",
"SANTA BÁRBARA",
"SAN JUAN BAUTISTA",
"SANTO TOMÁS LA UNIÓN",
"ZUNILITO",
"PUEBLO NUEVO",
"RÍO BRAVO",
"SAN JOSÉ LA MÁQUINA",
);


var MuniLabol_RETALHULEU = new Array("-",
"RETALHULEU",
"SAN SEBASTIÁN",
"SANTA CRUZ MULUÁ",
"SAN MARTÍN ZAPOTITLÁN",
"SAN FELIPE",
"SAN ANDRÉS VILLA SECA",
"CHAMPERICO",
"NUEVO SAN CARLOS",
"EL ASINTAL",
);


var MuniLabol_SAN_MARCOS = new Array("-",
"SAN MARCOS",
"SAN PEDRO SACATEPÉQUEZ",
"SAN ANTONIO SACATEPÉQUEZ",
"COMITANCILLO",
"SAN MIGUEL IXTAHUACÁN",
"CONCEPCIÓN TUTUAPA",
"TACANÁ",
"SIBINAL",
"TAJUMULCO",
"TEJUTLA",
"SAN RAFAEL PIÉ DE LA CUESTA",
"NUEVO PROGRESO",
"EL TUMBADOR",
"EL RODEO",
"MALACATÁN",
"CATARINA",
"AYUTLA",
"OCÓS",
"SAN PABLO",
"EL QUETZAL",
"LA REFORMA",
"PAJAPITA",
"IXCHIGUÁN",
"SAN JOSÉ OJETENÁN",
"SAN CRISTÓBAL CUCHO",
"SIPACAPA",
"ESQUIPULAS PALO GORDO",
"RÍO BLANCO",
"SAN LORENZO",
"LA BLANCA",
);


var MuniLabol_HUEHUETENANGO = new Array("-",
"HUEHUETENANGO",
"CHIANTLA",
"MALACATANCITO",
"CUILCO",
"NENTÓN",
"SAN PEDRO NECTA",
"JACALTENANGO",
"SOLOMA",
"IXTAHUACÁN",
"SANTA BÁRBARA",
"LA LIBERTAD",
"LA DEMOCRACIA",
"SAN MIGUEL ACATÁN",
"SAN RAFAEL LA INDEPENDENCIA",
"TODOS SANTOS CUCHUMATÁN",
"SAN JUAN ATITÁN",
"SANTA EULALIA",
"SAN MATEO IXTATÁN",
"COLOTENANGO",
"SAN SEBASTIÁN HUEHUETENANGO",
"TECTITÁN",
"TETAPAN",
"CONCEPCIÓN HUISTA",
"SAN JUAN IXCOY",
"SAN ANTONIO HUISTA",
"SAN SEBASTIÁN COATÁN",
"BARILLAS",
"AGUACATÁN",
"SAN RAFAEL PETZAL",
"SAN GASPAR IXCHIL",
"SANTIAGO CHIMALTENANGO",
"SANTA ANA HUISTA",
"UNIÓN CANTINIL",
);


var MuniLabol_QUICHÉ = new Array("-",
"SANTA CRUZ DEL QUICHÉ",
"CHICHÉ",
"CHINIQUE",
"ZACUALPA",
"CHAJUL",
"CHICHICASTENANGO",
"PATZITÉ",
"SAN ANTONIO ILOTENANGO",
"SAN PEDRO JOCOPILAS",
"CUNÉN",
"SAN JUAN COTZAL",
"JOYABAJ",
"NEBAJ",
"SAN ANDRÉS SAJCABAJÁ",
"USPANTÁN",
"SACAPULAS",
"SAN BARTOLOMÉ JOCOTENANGO",
"CANILLÁ",
"CHICAMÁN",
"IXCÁN",
"PACHALUM",
);


var MuniLabol_BAJA_VERAPAZ = new Array("-",
"SALAMÁ",
"SAN MIGUEL CHICAJ",
"RABINAL",
"CUBULCO",
"GRANADOS",
"EL CHOL",
"SAN JERÓNIMO",
"PURULHÁ",
);


var MuniLabol_ALTA_VERAPAZ = new Array("-",
"COBÁN",
"SANTA CRUZ VERAPAZ",
"SAN CRISTÓBAL VERAPAZ",
"TACTIC",
"TAMAHÚ",
"TUCURÚ",
"PANZÓS",
"SENAHÚ",
"SAN PEDRO CARCHÁ",
"SAN JUAN CHAMELCO",
"LANQUÍN",
"CAHABÓN",
"CHISEC",
"CHAHAL",
"FRAY BARTOLOMÉ DE LAS CASAS",
"SANTA CATALINA LA TINTA",
"RAXRUHÁ",
);


var MuniLabol_PETÉN = new Array("-",
"FLORES",
"SAN JOSÉ",
"SAN BENITO",
"SAN ANDRÉS",
"LA LIBERTAD",
"SAN FRANCISCO",
"SANTA ANA",
"DOLORES",
"SAN LUIS",
"SAYAXCHÉ",
"MELCHOR DE MENCOS",
"POPTÚN",
"LAS CRUCES",
"EL CHAL",
);


var MuniLabol_IZABAL = new Array("-",
"PUERTO BARRIOS",
"LIVINGSTON",
"EL ESTOR",
"MORALES",
"LOS AMATES",
);


var MuniLabol_ZACAPA = new Array("-",
"ZACAPA",
"ESTANZUELA",
"RÍO HONDO",
"GUALÁN",
"TECULUTÁN",
"USUMATLÁN",
"CABAÑAS",
"SAN DIEGO",
"LA UNIÓN",
"HUITÉ",
"SAN JORGE",
);


var MuniLabol_CHIQUIMULA = new Array("-",
"CHIQUIMULA",
"SAN JOSÉ LA ARADA",
"SAN JUAN ERMITA",
"JOCOTÁN",
"CAMOTÁN",
"OLOPA",
"ESQUIPULAS",
"CONCEPCIÓN LAS MINAS",
"QUETZALTEPEQUE",
"SAN JACINTO",
"IPALA",
);


var MuniLabol_JALAPA = new Array("-",
"JALAPA",
"SAN PEDRO PINULA",
"SAN LUIS JILOTEPEQUE",
"SAN MANUEL CHAPARRÓN",
"SAN CARLOS ALZATATE",
"MONJAS",
"MATAQUESCUINTLA",
);


var MuniLabol_JUTIAPA = new Array("-",
"JUTIAPA",
"EL PROGRESO",
"SANTA CATARINA MITA",
"AGUA BLANCA",
"ASUNCIÓN MITA",
"YUPILTEPEQUE",
"ATESCATEMPA",
"JEREZ",
"EL ADELANTO",
"ZAPOTITLÁN",
"COMAPA",
"JALPATAGUA",
"CONGUACO",
"MOYUTA",
"PASACO",
"SAN JOSÉ ACATEMPA",
"QUESADA",
);



// ---------------------------------------------2) crear una funcion que permita ejecutar el cambio dinamico---------------------------------------------

function DepartamentoLabol(){
    var DeptoLabol;
    //Se toma el vamor de la "cosa seleccionada"
    DeptoLabol = document.formulario1.DeptoLabol[document.formulario1.DeptoLabol.selectedIndex].value;
    //se chequea si la "cosa" esta definida
    if(DeptoLabol!=0){
        //selecionamos las cosas Correctas
        mis_opts=eval("MuniLabol_" + DeptoLabol);
        //se calcula el numero de cosas
        num_opts=mis_opts.length;
        //marco el numero de opt en el select
        document.formulario1.MuniLabol.length = num_opts;
        //para cada opt del array, la pongo en el select
        for(i=0; i<num_opts; i++){
            document.formulario1.MuniLabol.options[i].value=mis_opts[i];
            document.formulario1.MuniLabol.options[i].text=mis_opts[i];
        }
        }else{
            //si no habia ninguna opt seleccionada, elimino las cosas del select
            document.formulario1.opt.length = 1;
            //ponemos un guion en la unica opt que he dejado
            document.formulario1.opt.options[0].value="-";
            document.formulario1.opt.options[0].text="-";
        }
        //hacer un reset de las opts
        document.formulario1.MuniLabol.options[0].selected = true;
        
    }
