//--------------------------------------------- 1) Definir Las Variables Departamento y Municiío Correspondintes---------------------------------------------
var Municipio_GUATEMALA = new Array("-",
"GUATEMALA",
"SANTA CATARINA PINULA",
"SAN JOSÉ PINULA",
"SAN JOSÉ DEL GOLFO",
"PALENCIA",
"CHINAUTLA",
"SAN PEDRO AYAMPUC",
"MIXCO",
"SAN PEDRO SACATEPÉQUEZ",
"SAN JUAN SACATEPÉQUEZ",
"SAN RAYMUNDO",
"CHUARRANCHO",
"FRAIJANES",
"AMATITLÁN",
"VILLA NUEVA",
"VILLA CANALES",
"PETAPA",
);


var Municipio_EL_PROGRESO = new Array("-",
"GUASTATOYA",
"MORAZÁN",
"SAN AGUSTÍN ACASAGUASTLÁN",
"SAN CRISTÓBAL ACASAGUASTLÁN",
"EL JÍCARO",
"SANSARE",
"SANARATE",
"SAN ANTONIO LA PAZ",
);


var Municipio_SACATEPÉQUEZ = new Array("-",
"ANTIGUA GUATEMALA",
"JOCOTENANGO",
"PASTORES",
"SUMPANGO",
"SANTO DOMINGO XENACOJ",
"SANTIAGO SACATEPÉQUEZ",
"SAN BARTOLOMÉ MILPAS ALTAS",
"SAN LUCAS SACATEPÉQUEZ",
"SANTA LUCÍA MILPAS ALTAS",
"MAGDALENA MILPAS ALTAS",
"SANTA MARÍA DE JESÚS",
"CIUDAD VIEJA",
"SAN MIGUEL DUEÑAS",
"ALOTENANGO",
"SAN ANTONIO AGUAS CALIENTES",
"SANTA CATARINA BARAHONA",
);


var Municipio_CHIMALTENANGO = new Array("-",
"CHIMALTENANGO",
"SAN JOSÉ POAQUIL",
"SAN MARTÍN JILOTEPEQUE",
"COMALAPA",
"SANTA APOLONIA",
"TECPÁN GUATEMALA",
"PATZÚN",
"POCHUTA",
"PATZICÍA",
"SANTA CRUZ BALANYÁ",
"ACATENANGO",
"YEPOCAPA",
"SAN ANDRÉS ITZAPA",
"PARRAMOS",
"ZARAGOZA",
"EL TEJAR",
);


var Municipio_ESCUINTLA = new Array("-",
"ESCUINTLA",
"SANTA LUCÍA COTZUMALGUAPA",
"LA DEMOCRACIA",
"SIQUINALÁ",
"MASAGUA",
"TIQUISATE",
"LA GOMERA",
"GUANAGAZAPA",
"SAN JOSÉ",
"IZTAPA",
"PALÍN",
"SAN VICENTE PACAYA",
"NUEVA CONCEPCIÓN",
);


var Municipio_SANTA_ROSA = new Array("-",
"CUILAPA",
"BARBERENA",
"SANTA ROSA DE LIMA",
"CASILLAS",
"SAN RAFAEL LAS FLORES",
"ORATORIO",
"SAN JUAN TECUACO",
"CHIQUIMULILLA",
"TAXISCO",
"SANTA MARÍA IXHUATÁN",
"GUAZACAPÁN",
"SANTA CRUZ NARANJO",
"PUEBLO NUEVO VIÑAS",
"NUEVA SANTA ROSA",
);


var Municipio_SOLOLÁ = new Array("-",
"SOLOLÁ",
"SAN JOSÉ CHACAYÁ",
"SANTA MARÍA VISITACIÓN",
"SANTA LUCÍA UTATLÁN",
"NAHUALÁ",
"SANTA CATARINA IXTAHUACÁN",
"SANTA CLARA LA LAGUNA",
"CONCEPCIÓN",
"SAN ANDRÉS SEMETABAJ",
"PANAJACHEL",
"SANTA CATARINA PALOPÓ",
"SAN ANTONIO PALOPÓ",
"SAN LUCAS TOLIMÁN",
"SANTA CRUZ LA LAGUNA",
"SAN PABLO LA LAGUNA",
"SAN MARCOS LA LAGUNA",
"SAN JUAN LA LAGUNA",
"SAN PEDRO LA LAGUNA",
"SANTIAGO ATITLÁN",
);


var Municipio_TOTONICAPÁN = new Array("-",
"TOTONICAPÁN",
"SAN CRISTÓBAL TOTONICAPÁN",
"SAN FRANCISCO EL ALTO",
"SAN ANDRÉS XECUL",
"MOMOSTENANGO",
"SANTA MARÍA CHIQUIMULA",
"SANTA LUCÍA LA REFORMA",
"SAN BARTOLO",
);


var Municipio_QUETZALTENANGO = new Array("-",
"QUETZALTENANGO",
"SALCAJÁ",
"OLINTEPEQUE",
"SAN CARLOS SIJA",
"SIBILIA",
"CABRICÁN",
"CAJOLÁ",
"SAN MIGUEL SIGUILÁ",
"OSTUNCALCO",
"SAN MATEO",
"CONCEPCIÓN CHIQUIRICHAPA",
"SAN MARTÍN SACATEPÉQUEZ",
"ALMOLONGA",
"CANTEL",
"HUITÁN",
"ZUNIL",
"COLOMBA",
"SAN FRANCISCO LA UNIÓN",
"EL PALMAR",
"COATEPEQUE",
"GÉNOVA",
"FLORES COSTA CUCA",
"LA ESPERANZA",
"PALESTINA DE LOS ALTOS",
);


var Municipio_SUCHITEPÉQUEZ = new Array("-",
"MAZATENANGO",
"CUYOTENANGO",
"SAN FRANCISCO ZAPOTITLÁN",
"SAN BERNARDINO",
"SAN JOSÉ EL IDOLO",
"SANTO DOMINGO SUCHITEPÉQUEZ",
"SAN LORENZO",
"SAMAYAC",
"SAN PABLO JOCOPILAS",
"SAN ANTONIO SUCHITEPÉQUEZ",
"SAN MIGUEL PANÁN",
"SAN GABRIEL",
"CHICACAO",
"PATULUL",
"SANTA BÁRBARA",
"SAN JUAN BAUTISTA",
"SANTO TOMÁS LA UNIÓN",
"ZUNILITO",
"PUEBLO NUEVO",
"RÍO BRAVO",
"SAN JOSÉ LA MÁQUINA",
);


var Municipio_RETALHULEU = new Array("-",
"RETALHULEU",
"SAN SEBASTIÁN",
"SANTA CRUZ MULUÁ",
"SAN MARTÍN ZAPOTITLÁN",
"SAN FELIPE",
"SAN ANDRÉS VILLA SECA",
"CHAMPERICO",
"NUEVO SAN CARLOS",
"EL ASINTAL",
);


var Municipio_SAN_MARCOS = new Array("-",
"SAN MARCOS",
"SAN PEDRO SACATEPÉQUEZ",
"SAN ANTONIO SACATEPÉQUEZ",
"COMITANCILLO",
"SAN MIGUEL IXTAHUACÁN",
"CONCEPCIÓN TUTUAPA",
"TACANÁ",
"SIBINAL",
"TAJUMULCO",
"TEJUTLA",
"SAN RAFAEL PIÉ DE LA CUESTA",
"NUEVO PROGRESO",
"EL TUMBADOR",
"EL RODEO",
"MALACATÁN",
"CATARINA",
"AYUTLA",
"OCÓS",
"SAN PABLO",
"EL QUETZAL",
"LA REFORMA",
"PAJAPITA",
"IXCHIGUÁN",
"SAN JOSÉ OJETENÁN",
"SAN CRISTÓBAL CUCHO",
"SIPACAPA",
"ESQUIPULAS PALO GORDO",
"RÍO BLANCO",
"SAN LORENZO",
"LA BLANCA",
);


var Municipio_HUEHUETENANGO = new Array("-",
"HUEHUETENANGO",
"CHIANTLA",
"MALACATANCITO",
"CUILCO",
"NENTÓN",
"SAN PEDRO NECTA",
"JACALTENANGO",
"SOLOMA",
"IXTAHUACÁN",
"SANTA BÁRBARA",
"LA LIBERTAD",
"LA DEMOCRACIA",
"SAN MIGUEL ACATÁN",
"SAN RAFAEL LA INDEPENDENCIA",
"TODOS SANTOS CUCHUMATÁN",
"SAN JUAN ATITÁN",
"SANTA EULALIA",
"SAN MATEO IXTATÁN",
"COLOTENANGO",
"SAN SEBASTIÁN HUEHUETENANGO",
"TECTITÁN",
"CONCEPCIÓN HUISTA",
"SAN JUAN IXCOY",
"SAN ANTONIO HUISTA",
"SAN SEBASTIÁN COATÁN",
"BARILLAS",
"AGUACATÁN",
"SAN RAFAEL PETZAL",
"SAN GASPAR IXCHIL",
"SANTIAGO CHIMALTENANGO",
"SANTA ANA HUISTA",
"UNIÓN CANTINIL",
);


var Municipio_QUICHÉ = new Array("-",
"SANTA CRUZ DEL QUICHÉ",
"CHICHÉ",
"CHINIQUE",
"ZACUALPA",
"CHAJUL",
"CHICHICASTENANGO",
"PATZITÉ",
"SAN ANTONIO ILOTENANGO",
"SAN PEDRO JOCOPILAS",
"CUNÉN",
"SAN JUAN COTZAL",
"JOYABAJ",
"NEBAJ",
"SAN ANDRÉS SAJCABAJÁ",
"USPANTÁN",
"SACAPULAS",
"SAN BARTOLOMÉ JOCOTENANGO",
"CANILLÁ",
"CHICAMÁN",
"IXCÁN",
"PACHALUM",
);


var Municipio_BAJA_VERAPAZ = new Array("-",
"SALAMÁ",
"SAN MIGUEL CHICAJ",
"RABINAL",
"CUBULCO",
"GRANADOS",
"EL CHOL",
"SAN JERÓNIMO",
"PURULHÁ",
);


var Municipio_ALTA_VERAPAZ = new Array("-",
"COBÁN",
"SANTA CRUZ VERAPAZ",
"SAN CRISTÓBAL VERAPAZ",
"TACTIC",
"TAMAHÚ",
"TUCURÚ",
"PANZÓS",
"SENAHÚ",
"SAN PEDRO CARCHÁ",
"SAN JUAN CHAMELCO",
"LANQUÍN",
"CAHABÓN",
"CHISEC",
"CHAHAL",
"FRAY BARTOLOMÉ DE LAS CASAS",
"SANTA CATALINA LA TINTA",
"RAXRUHÁ",
);


var Municipio_PETÉN = new Array("-",
"FLORES",
"SAN JOSÉ",
"SAN BENITO",
"SAN ANDRÉS",
"LA LIBERTAD",
"SAN FRANCISCO",
"SANTA ANA",
"DOLORES",
"SAN LUIS",
"SAYAXCHÉ",
"MELCHOR DE MENCOS",
"POPTÚN",
"LAS CRUCES",
"EL CHAL",
);


var Municipio_IZABAL = new Array("-",
"PUERTO BARRIOS",
"LIVINGSTON",
"EL ESTOR",
"MORALES",
"LOS AMATES",
);


var Municipio_ZACAPA = new Array("-",
"ZACAPA",
"ESTANZUELA",
"RÍO HONDO",
"GUALÁN",
"TECULUTÁN",
"USUMATLÁN",
"CABAÑAS",
"SAN DIEGO",
"LA UNIÓN",
"HUITÉ",
"SAN JORGE",
);


var Municipio_CHIQUIMULA = new Array("-",
"CHIQUIMULA",
"SAN JOSÉ LA ARADA",
"SAN JUAN ERMITA",
"JOCOTÁN",
"CAMOTÁN",
"OLOPA",
"ESQUIPULAS",
"CONCEPCIÓN LAS MINAS",
"QUETZALTEPEQUE",
"SAN JACINTO",
"IPALA",
);


var Municipio_JALAPA = new Array("-",
"JALAPA",
"SAN PEDRO PINULA",
"SAN LUIS JILOTEPEQUE",
"SAN MANUEL CHAPARRÓN",
"SAN CARLOS ALZATATE",
"MONJAS",
"MATAQUESCUINTLA",
);


var Municipio_JUTIAPA = new Array("-",
"JUTIAPA",
"EL PROGRESO",
"SANTA CATARINA MITA",
"AGUA BLANCA",
"ASUNCIÓN MITA",
"YUPILTEPEQUE",
"ATESCATEMPA",
"JEREZ",
"EL ADELANTO",
"ZAPOTITLÁN",
"COMAPA",
"JALPATAGUA",
"CONGUACO",
"MOYUTA",
"PASACO",
"SAN JOSÉ ACATEMPA",
"QUESADA",
);



// ---------------------------------------------2) crear una funcion que permita ejecutar el cambio dinamico---------------------------------------------

function DeptoMuni(){
    var Departamento;
    //Se toma el vamor de la "cosa seleccionada"
    Departamento = document.regForm.Departamento[document.regForm.Departamento.selectedIndex].value;
    //se chequea si la "cosa" esta definida
    if(Departamento!=0){
        //selecionamos las cosas Correctas
        mis_opts=eval("Municipio_" + Departamento);
        //se calcula el numero de cosas
        num_opts=mis_opts.length;
        //marco el numero de opt en el select
        document.regForm.Municipio.length = num_opts;
        //para cada opt del array, la pongo en el select
        for(i=0; i<num_opts; i++){
            document.regForm.Municipio.options[i].value=mis_opts[i];
            document.regForm.Municipio.options[i].text=mis_opts[i];
        }
        }else{
            //si no habia ninguna opt seleccionada, elimino las cosas del select
            document.regForm.opt.length = 1;
            //ponemos un guion en la unica opt que he dejado
            document.regForm.opt.options[0].value="-";
            document.regForm.opt.options[0].text="-";
        }
        //hacer un reset de las opts
        document.regForm.Municipio.options[0].selected = true;
        
    }

//--------------------------------------------- 1) Definir Las Variables Correspondintes---------------------------------------------
var opt_RENGLON_011 = new Array ("-",
"011-ASESOR PROFESIONAL ESPECIALIZADO II",
"011-ASESOR PROFESIONAL ESPECIALIZADO IV",
"011-ASISTENTE PROFESIONAL I",
"011-ASISTENTE PROFESIONAL II",
"011-ASISTENTE PROFESIONAL III",
"011-ASISTENTE PROFESIONAL IV",
"011-ASISTENTE PROFESIONAL JEFE",
"011-DIRECTOR DE AREA DE SALUD",
"011-DIRECTOR DE DISPENSARIO I 4 HRS.",
"011-DIRECTOR DE HOSPITAL DISTRITAL",
"011-DIRECTOR DE HOSPITAL I",
"011-DIRECTOR DE HOSPITAL I 4 HRS.",
"011-DIRECTOR DE HOSPITAL II",
"011-DIRECTOR REGIONAL",
"011-DIRECTOR TECNICO II",
"011-JEFE DE AREA",
"011-JEFE TECNICO I",
"011-JEFE TECNICO II",
"011-JEFE TECNICO PROFESIONAL I",
"011-JEFE TECNICO PROFESIONAL I 4 HRS.",
"011-JEFE TECNICO PROFESIONAL II",
"011-JEFE TECNICO PROFESIONAL III",
"011-OFICIAL MAYOR",
"011-OFICINISTA I",
"011-OFICINISTA II",
"011-OFICINISTA III",
"011-OFICINISTA IV",
"011-PARAMEDICO I",
"011-PARAMEDICO I 2 HRS.",
"011-PARAMEDICO I 3 HRS.",
"011-PARAMEDICO I 4 HRS.",
"011-PARAMEDICO II",
"011-PARAMEDICO III",
"011-PARAMEDICO III 4 HRS.",
"011-PARAMEDICO IV",
"011-PARAMEDICO IV 4 HRS.",
"011-PARAMEDICO JEFE I",
"011-PARAMEDICO JEFE II",
"011-PARAMEDICO JEFE III",
"011-PROFESIONAL I",
"011-PROFESIONAL I 2 HRS.",
"011-PROFESIONAL I 3 HRS.",
"011-PROFESIONAL I 4 HRS.",
"011-PROFESIONAL I 6 HRS.",
"011-PROFESIONAL II",
"011-PROFESIONAL II 1 HRA.",
"011-PROFESIONAL II 2 HRS.",
"011-PROFESIONAL II 4 HRS.",
"011-PROFESIONAL II 6 HRS.",
"011-PROFESIONAL III",
"011-PROFESIONAL III 1 HRA.",
"011-PROFESIONAL III 2 HRS.",
"011-PROFESIONAL III 4 HRS.",
"011-PROFESIONAL III 6 HRS.",
"011-PROFESIONAL JEFE I",
"011-PROFESIONAL JEFE I 2 HRS.",
"011-PROFESIONAL JEFE I 3 HRS.",
"011-PROFESIONAL JEFE I 4 HRS.",
"011-PROFESIONAL JEFE I 6 HRS.",
"011-PROFESIONAL JEFE II",
"011-PROFESIONAL JEFE II 2 HRS.",
"011-PROFESIONAL JEFE II 3 HRS.",
"011-PROFESIONAL JEFE II 4 HRS.",
"011-PROFESIONAL JEFE II 6 HRS.",
"011-PROFESIONAL JEFE III",
"011-PROFESIONAL JEFE III 2 HRS.",
"011-PROFESIONAL JEFE III 3 HRS.",
"011-PROFESIONAL JEFE III 4 HRS.",
"011-PROFESIONAL JEFE III 6 HRS.",
"011-SECRETARIO EJECUTIVO I",
"011-SECRETARIO EJECUTIVO II",
"011-SECRETARIO EJECUTIVO III",
"011-SECRETARIO EJECUTIVO IV",
"011-SECRETARIO EJECUTIVO MINISTERIAL I",
"011-SECRETARIO EJECUTIVO MINISTERIAL II",
"011-SECRETARIO EJECUTIVO V",
"011-SECRETARIO OFICINISTA",
"011-SUB DIRECTOR DE HOSPITAL I",
"011-SUB DIRECTOR DE HOSPITAL II",
"011-SUB DIRECTOR GENERAL",
"011-SUBDIRECTOR TECNICO II",
"011-TECNICO EN INFORMATICA I",
"011-TECNICO I",
"011-TECNICO II",
"011-TECNICO III",
"011-TECNICO III 4 HRS.",
"011-TECNICO III 6 HRS.",
"011-TECNICO PROFESIONAL I",
"011-TECNICO PROFESIONAL I 4 HRS.",
"011-TECNICO PROFESIONAL I 6 HRS.",
"011-TECNICO PROFESIONAL II",
"011-TECNICO PROFESIONAL II 1 HRA.",
"011-TECNICO PROFESIONAL III",
"011-TECNICO PROFESIONAL INFORMATICA III",
"011-TRABAJADOR ESPECIALIZADO I",
"011-TRABAJADOR ESPECIALIZADO I 6 HRS.",
"011-TRABAJADOR ESPECIALIZADO II",
"011-TRABAJADOR ESPECIALIZADO III",
"011-TRABAJADOR ESPECIALIZADO JEFE I",
"011-TRABAJADOR ESPECIALIZADO JEFE II",
"011-TRABAJADOR OPERATIVO II",
"011-TRABAJADOR OPERATIVO III",
"011-TRABAJADOR OPERATIVO IV",
"011-TRABAJADOR OPERATIVO JEFE I",
"011-TRABAJADOR OPERATIVO JEFE II",
"011-VICEMINISTRO",
"011-MINISTRO DE SALUD PUBLICA Y A.S.",
"011-ASESOR PROFESIONAL ESPEC I 6 HRS",
"011-PARAMEDICO II 4 HRS.",
"011-PARAMEDICO IV 6 HRS.",
"011-PARAMEDICO JEFE I 4 HRS.",
"011-PEÓN",
"011-PROFESIONAL III 3 HRS.",
"011-PROFESIONAL III 4 HORAS",
"011-PROFESIONAL JEFE III 4 HRS.",
"011-TECNICO I 6 HRS.",
"011-TECNICO PROFESIONAL  EN INFORMATICA II",
"011-TECNICO PROFESIONAL II 6 HRS.",
"011-TRABAJADOR ESPECIALIZADO II 4 HRS.",
"011-TRABAJADOR ESPECIALIZADO III 4 HRS",
"011-TRABAJADOR ESPECIALIZADO III 6 HRS",);

var opt_RENGLON_021 = new Array ("-", 
"021-ANALISTA DE CONTABILIDAD",
"021-ANALISTA DE PRESUPUESTO",
"021-ENCARGADO DE COMPRAS",
"021-ENCARGADO DE PRESUPUESTO",
"021-ENCARGADO DE TESORERÍA",
"021-JEFE ADMINISTRATIVO",
"021-JEFE DE GESTIÓN DE PROGRAMAS, PROYECTOS Y COOPERACIÓN INTERNACIONAL",
"021-JEFE DE INGENIERÍA DE PROYECTOS",
"021-JEFE DE RESIDENTE",
"021-JEFE DE SEGUIMIENTO DE INGENIERÍA",
"021-MÉDICO DE URGENCIA",
"021-MÉDICO RESIDENTE I",
"021-MÉDICO RESIDENTE II",
"021-MÉDICO RESIDENTE III",
"021-MÉDICO RESIDENTE IV",
"021-MÉDICO TURNISTA 4 HORAS",
"021-PROFESIONAL AMBIENTAL",
"021-PROFESIONAL EN ADMINISTRACIÓN DE PROGRAMAS Y PROYECTOS",
"021-PROFESIONAL EN INGENIERÍA INDUSTRIAL",
"021-PROFESIONAL II",
"021-PROFESIONAL JURÍDICO",
"021-SECRETARIA",
"021-SECRETARIA EJECUTIVA",
"021-JEFE FINANCIERO",
"021-TÉCNICO DE ALMACÉN",
"021-ANALISTA DE TESORERÍA",
"021-PROFESIONAL EN INGENIERÍA CIVIL",
"021-PROFESIONAL EN INGENIERÍA MECÁNICA",
"021-PROFESIONAL EN PROGRAMAS, PROYECTOS Y COOPERACIÓN INTERNACIONAL",
"021-PROFESIONAL EN ARQUITECTURA",
"021-MENSAJERO",
"021-CONSERJE",
"021-ENCARGADO DE INVENTARIOS",
"021-PILOTO",
"021-TÉCNICO DE INVENTARIOS",
"021-ENCARGADO DE CONTABILIDAD",
"021-ENCARGADO DE ALMACEN",
"021-ANALISTA DE COMPRAS",
"021-PROFESIONAL EN SERVICIOS DE SALUD",
"021-PROFESIONAL EN INGENIERÍA ELÉCTRICA",
"021-PROFESIONAL EN INGENIERÍA SANITARIA",
"021-AUXILIAR DE SERVICIOS TEMPORAL ATENCIÓN COVID-19",
"021-MÉDICO GENERAL TEMPORAL ATENCIÓN COVID-19",
"021-TÉCNICO TEMPORAL III ATENCIÓN COVID-19",
"021-PROFESIONAL TEMPORAL ATENCIÓN COVID-19",
"021-TÉCNICO TEMPORAL I ATENCIÓN COVID-19",
"021-TÉCNICO TEMPORAL II ATENCIÓN COVID-19",
"021-JEFE DE GESTIÓN DE PROGRAMAS, PROYECTOS Y COOPERACIÓN INTERNACIONAL",
"021-MÉDICO ESPECIALISTA TEMPORAL ATENCIÓN COVID -19",
"021-PROFESIONAL EN PROGRAMAS, PROYECTOS Y COOPERACIÓN INTERNACIONAL",
"021-PROFESIONAL EN INGENIERÍA SANITARIA",
"021-MÉDICO SUB-ESPECIALISTA TEMPORAL ATENCIÓN COVID-19");

var opt_RENGLON_022 = new Array ("-",
"022-DIRECTOR EJECUTIVO I",
"022-DIRECTOR EJECUTIVO II",
"022-OFICINISTA IV",
"022-SUBDIRECTOR EJECUTIVO I",
"022-SUBDIRECTOR EJECUTIVO II",
"022-TECNICO I",
"022-TECNICO III",
"022-PROFESIONAL II",
"022-TRABAJADOR ESPECIALIZADO II");


var opt_RENGLON_029 = new Array ("-", 
"029-SERVICIOS TÉCNICOS", 
"029-SERVICIOS PROFESIONALES");

var opt_RENGLON_031 = new Array ("-", 
"031-ALBAÑIL I",
"031-AUXILIAR DE BODEGA",
"031-AUXILIAR DE OPERACIÓN DE ",
"031-AUXILIAR MISCELÁNEO",
"031-BODEGUERO IV",
"031-CARPINTERO I",
"031-COCINERO",
"031-CONDUCTOR DE VEHÍCULOS ",
"031-CONSERJE",
"031-ELECTRICISTA I",
"031-FONTANERO I",
"031-HERRERO I",
"031-LAVANDERA I",
"031-MECÁNICO AUTOMOTRÍZ I",
"031-MENSAJERO I",
"031-OPERADOR DE EQUIPO DE ",
"031-PEÓN VIGILANTE I",
"031-PEÓN VIGILANTE II",
"031-PEÓN VIGILANTE V",
"031-PEÓN VIVANDERA",
"031-PILOTO I VEHÍCULOS ",
"031-PINTOR I",
"031-TRABAJADOR ECÓNOMO",
"031-ALBAÑIL III",
"031-ALBAÑIL IV",
"031-ALBAÑIL V",
"031-AUXILIAR DE ALBAÑILERÍA",
"031-AUXILIAR DE CAPORAL",
"031-AUXILIAR DE CARPINTERÍA",
"031-AUXILIAR DE ELECTRICIDAD",
"031-AUXILIAR DE FONTANERÍA",
"031-AUXILIAR DE HERRERÍA",
"031-AUXILIAR DE MECÁNICA",
"031-AUXILIAR DE OPERACIÓN DE MAQUINARIA Y EQUIPO",
"031-BODEGUERO I",
"031-BODEGUERO II",
"031-BODEGUERO III",
"031-CONDUCTOR DE VEHÍCULOS LIVIANOS",
"031-CONDUCTOR DE VEHÍCULOS PESADOS",
"031-ELECTRICISTA II",
"031-ELECTRICISTA III",
"031-ENCARGADO I DE OPERACIONES DE MAQUINARIA Y EQUIPO",
"031-JARDINERO I",
"031-JARDINERO II",
"031-LAVANDERA II",
"031-MAESTRO DE OBRAS",
"031-MECÁNICO AUTOMOTRÍZ II",
"031-MECÁNICO AUTOMOTRÍZ III",
"031-MENSAJERO II",
"031-OPERADOR DE EQUIPO",
"031-OPERADOR DE EQUIPO DE ESTADÍSTICA",
"031-OPERADOR DE MAQUINARIA",
"031-PEÓN",
"031-PEÓN VIGILANTE III",
"031-PEÓN VIGILANTE IV",
"031-PILOTO I VEHÍCULOS LIVIANOS",
"031-PILOTO II VEHÍCULOS PESADOS",
"031-Puesto Oficial",
"031-SASTRE",
"031-TRABAJADOR  VIVANDERA",
"031-TRABAJADOR DE MANTENIMIENTO DE TELECOMUNICACIONES I");


var opt_RENGLON_036 = new Array ("-", 
"036-RETRIBUCIÓN POR SERVICIOS");

var opt_RENGLON_SUBG18 = new Array ("-", 
"181-SERVICIOS DE ESTUDIO Y INVESTIGACIÓN",
"182-SERVICIOS MÉDICOS Y SANITARIOS",
"183-SERVICIOS JURÍDICOS", 
"184-SERVICIOS ECONÓMICOS", 
"185-SERVICIOS DE CAPACITACIÓN",
"186-SERVICIOS DE INFORMÁTICA",
"187-SERVICIOS POR ACTUACIONES", 
"188-SERVICIOS POR INGENIERÍA", 
"189-SERVICIOS TÉCNICOS", 
"189-SERVICIOS PROFESIONALES");



// ---------------------------------------------2) crear una funcion que permita ejecutar el cambio dinamico---------------------------------------------

function cambia(){
    var Renglon;
    //Se toma el vamor de la "cosa seleccionada"
    Renglon = document.regForm.Renglon[document.regForm.Renglon.selectedIndex].value;
    //se chequea si la "cosa" esta definida
    if(Renglon!=0){
        //selecionamos las cosas Correctas
        mis_opts=eval("opt_" + Renglon);
        //se calcula el numero de cosas
        num_opts=mis_opts.length;
        //marco el numero de opt en el select
        document.regForm.opt.length = num_opts;
        //para cada opt del array, la pongo en el select
        for(i=0; i<num_opts; i++){
            document.regForm.opt.options[i].value=mis_opts[i];
            document.regForm.opt.options[i].text=mis_opts[i];
        }
        }else{
            //si no habia ninguna opt seleccionada, elimino las cosas del select
            document.regForm.opt.length = 1;
            //ponemos un guion en la unica opt que he dejado
            document.regForm.opt.options[0].value="-";
            document.regForm.opt.options[0].text="-";
        }
        //hacer un reset de las opts
        document.regForm.opt.options[0].selected = true;
        
    }


//--------------------------------------------- 1) Definir Las Variables Depto Correspondintes---------------------------------------------


var DeptoTrabajo_DESPACHO_MINISTERIAL = new Array ("-",
"DESPACHO MINISTERIAL",
"ASESORA JURIDICA - AREA DE ASUNTOS ADMINISTRATIVOS",
"ASESORA JURIDICA - AREA DE CONVENIOS",
"ASESORA JURIDICA - AREA DE LEGISLACION Y COMPILACION DE LEYES EN MATERIA DE SALUD",
"ASESORA JURIDICA - ASUNTOS CONSTITUCIONALES",
"ASESORA JURIDICA - ASUNTOS DE BIENES Y REGISTRO DEL ESTADO",
"ASESORA JURIDICA - ASUNTOS LABORALES",
"ASESORA JURIDICA - ASUNTOS PENALES",
"ASESORA JURIDICA - ASUNTOS PENALES Y DERECHOS HUMANOS",
"ASESORA JURIDICA - JEFATURA",
"ASESORÍA JURÍDICA - ASUNTOS ADMINISTRATIVOS",
"COMUNICACIÓN SOCIAL",
"UNIDAD ESPECIALIZADA DE COOPERACION INTERNACIONAL",
"PROYECTO CRECER SANO NUTRICION Y SALUD",
"SECRETARIA EJECUTIVA",
"SEGURIDAD DE DESPACHO",
"SIGSA",
"UNIDAD DE AUDITORIA INTERNA",
"UNIDAD DE GENERO DE LA SALUD",
"UNIDAD DE PLANIFICACION ESTRATEGICA (ZONA 7)",
"UNIDAD DE PLANIFICACION ESTRATEGICA",
"UNIDAD DE PUEBLOS INDIGENAS  E INTERCULTURALIDAD",
"UNIDAD DE TRANSPARENCIA Y ANTICORRUPCION");


var DeptoTrabajo_VICEMINISTERIO_ADMINISTRATIVO_FINANCIERO = new Array ("-",
"VICEMINISTERIO ADMINISTRATIVO FINANCIERO",
"COMISION TECNICA Y EVALUACION",
"DEPARTAMENTO ADMINISTRATIVO  - JEFATURA",
"DEPARTAMENTO ADMINISTRATIVO - ADUANAS",
"DEPARTAMENTO ADMINISTRATIVO - ARCHIVO ADMINISTRATIVO FINANCIERO",
"DEPARTAMENTO ADMINISTRATIVO - BODEGA DE MEDICAMENTOS",
"DEPARTAMENTO ADMINISTRATIVO - COMPRAS 201",
"DEPARTAMENTO ADMINISTRATIVO - CONTABILIDAD",
"DEPARTAMENTO ADMINISTRATIVO - SERVICIOS GENERALES",
"DEPARTAMENTO ADMINISTRATIVO - INVENTARIOS",
"DEPARTAMENTO ADMINISTRATIVO - JEFATURA",
"DEPARTAMENTO ADMINISTRATIVO - MANTENIMIENTO",
"DEPARTAMENTO ADMINISTRATIVO - PRESUPUESTO 201",
"DEPARTAMENTO ADMINISTRATIVO - SUMINISTROS",
"DEPARTAMENTO ADMINISTRATIVO - TRANSPORTES",
"DEPARTAMENTO ADMINISTRATIVO - TRANSPORTES (ZONA 7)",
"DEPARTAMENTO ADMINISTRATIVO - VENTANILLA DE SIAD",
"DEPARTAMENTO DE ADQUISICIONES Y MANTENIMIENTO",
"DEPARTAMENTO DE CONTABILIDAD FINANCIERA",
"DEPARTAMENTO DE PRESUPUESTO FINANCIERO",
"DEPARTAMENTO FINANCIERO",
"DGRRHH",
"DGRRHH - DEPARTAMENTO DE ADMINISTRACION DE NOMINAS",
"DGRRHH - DEPARTAMENTO DE CAPACITACION",
"DGRRHH - DEPARTAMENTO DE DOTACION DE PERSONAL",
"DGRRHH - SECCION DE ACCIONES DE PERSONAL",
"DGRRHH - SECCION DE CONTRATOS",
"DGRRHH - SECCION DE RECURSOS HUMANOS PLANTA CENTRAL",
"DGRRHH - SECCION DE SEGUIMIENTO DE PROCESOS",
"DGRRHH - DEPARTAMENTO DE FORMACION DE RECURSOS HUMANOS",
"GERENCIA GENERAL ADMINISTRATIVA FINANCIERA",
"TESORERIA",
"UNIDAD DE GESTIÓN LOGÍSTICA",
"UNIDAD DE INFORMACION PUBLICA");

var DeptoTrabajo_VICEMINISTERIO_DE_ATENCION_PRIMARIA = new Array ("-",
"VICEMINISTERIO DE ATENCION PRIMARIA",
"DEPARTAMENTO DE EPIDEMIOLOGIA",
"SIAS - ADMINISTRACIÓN ",
"SIAS - ADMINISTRACIÓN - COMPRAS",
"SIAS - ADMINISTRACIÓN - CONTABILIDAD",
"SIAS - ADMINISTRACIÓN - DEFUNCIONES",
"SIAS - ADMINISTRACIÓN - INFORMACION",
"SIAS - ADMINISTRACIÓN - INFORMÁTICA",
"SIAS - ADMINISTRACIÓN - MANTENIMIENTO E INTENDENCIA",
"SIAS - ADMINISTRACIÓN - PLANTA TELEFÓNICA",
"SIAS - ADMINISTRACIÓN - SUMINISTROS - BODEGA DE DONACIONES",
"SIAS - ADMINISTRACIÓN - TRANSPORTES",
"SIAS - ADMINISTRACIÓN - SUMINISTROS",
"SIAS - DELEGACIÓN DE RECURSOS HUMANOS - ARCHIVO",
"SIAS - DELEGACIÓN DE RECURSOS HUMANOS - BIBLIOTECA",
"SIAS - DELEGACIÓN DE RECURSOS HUMANOS - CLÍNICA DE PERSONAL",
"SIAS - DELEGACIÓN DE RECURSOS HUMANOS",
"SIAS - DEPARTAMENTO DESARROLLO DE LOS SERVICIOS DE SALUD",
"SIAS - DEPARTAMENTO DESARROLLO DE LOS SERVICIOS DE SALUD - SECCIÓN DE ATENCIÓN INTEGRAL",
"SIAS - DEPARTAMENTO DESARROLLO DE LOS SERVICIOS DE SALUD - SECCIÓN DE DESARROLLO DE LA RED INTEGRAL DE SERVICIOS DE SALUD",
"SIAS - DEPARTAMENTO DESARROLLO DE LOS SERVICIOS DE SALUD - SECCIÓN DE HABILITACIÓN CATEGORIZACIÓN Y MEJORA DE LA RED DE SERVICIOS DE SALUD",
"SIAS - DEPARTAMENTO DESARROLLO DE LOS SERVICIOS DE SALUD - UNIDAD DE DESARROLLO DE LOS SERVICIOS DE ENFERMERÍA",
"SIAS - DIRECCIÓN GENERAL - ARCHIVO DE LA DIRECCIÓN GENERAL",
"SIAS - DIRECCIÓN GENERAL - DESPACHO DIRECTOR",
"SIAS - GESTIÓN DE RIESGO",
"SIAS - INVENTARIOS Y ADUANAS - ADUANAS",
"SIAS - INVENTARIOS Y ADUANAS - INVENTARIOS ",
"SIAS - PROEDUSA",
"SIAS - PROYECTO CRECER SANO",
"SIAS - TESORERIA",
"SIAS - UNIDAD MULTISECTORIAL",
"SIAS - USME");

var DeptoTrabajo_VICEMINISTERIO_DE_HOSPITALES = new Array ("-",
"VICEMINISTERIO DE HOSPITALES",
"VICEMINISTERIO DE HOSPITALES - COORDINACION INTERINSTITUCIONAL",
"VICEMINISTERIO DE HOSPITALES - DEPARTAMENTO DE NUTRICION Y BANCOS DE LECHE",
"VICEMINISTERIO DE HOSPITALES - PROGRAMA DE FORTALECIMIENTO DE LA RED HOSPITALARIA",
"VICEMINISTERIO DE HOSPITALES - ASISTENCIA TECNICA Y SERVICIO DE APOYO",
"VICEMINISTERIO DE HOSPITALES - COORDINACION DE HOSPITALES",
"VICEMINISTERIO DE HOSPITALES - PROGRAMA DE FORTALECIMIENTO DE LA RED HOSPITALARIA",
"VICEMINISTERIO DE HOSPITALES - SECCION DE BIOESTADISTICA E INFORMATICA",
"VICEMINISTERIO DE HOSPITALES - SUPERVISION DE REDES GESTION HOSPITALARIAS",
"VICEMINISTERIO DE HOSPITALES - VIOLENCIA SEXUAL");

var DeptoTrabajo_VICEMINISTERIO_TECNICO = new Array ("-",
"VICEMINISTERIO TECNICO",
"DGRVCS",
"DGRVCS - DRACES",
"DGRVCS - DRCA",
"DGRVCS - DRCPFA",
"DGRVCS - DRPSA",
"DGRVCS - DRCA",
"DGRVCS - DRPAP",
"DGRVCS - DRPAP  PROGRAMA DE IRAS Y ETAS",
"DGRVCS - DRPAP PROGRAMA DE ADOLESCENCIA Y JUVENTUD",
"DGRVCS - DRPAP PROGRAMA DE INMUNIZACIONES",
"DGRVCS - DRPAP PROGRAMA DE IRAS Y ETAS",
"DGRVCS - DRPAP PROGRAMA DE SALUD BUCODENTAL",
"DGRVCS - DRPAP PROGRAMA DE SALUD INTEGRAL DE LA NIÑEZ",
"DGRVCS - DRPAP PROGRAMA DE SALUD MENTAL",
"DGRVCS - DRPAP PROGRAMA DE TUBERCULOSIS",
"DGRVCS - DRPAP PROGRAMA DE VECTORES",
"DGRVCS - DRPAP PROGRAMA DE VIH SIDA",
"DGRVCS - DRPAP PROGRAMA DE ZOONOSIS",
"DGRVCS - DRPAP PROGRAMA NACIONAL DE MEDICINA TRADICIONAL Y ALTERNATIVA",
"DGRVCS - DRPAP PROGRAMA NACIONAL DE MEDICINA TRANSFUSIONAL Y BANCOS DE SANGRE",
"DGRVCS - DRPAP PROGRAMA NACIONAL PARA LA PREVENCION DE ENFERMEDADES CRONICAS",
"DGRVCS - DRPAP SALUD REPRODUCTIVA",
"DGRVCS - DRPAP SUBVENCION DE TUBERCULOSIS",
"DGRVCS - DRPAP UGA",
"DGRVCS - DRPAP UNIDAD DE DESARROLLO EDITORIAL",
"DGRVCS - DRPAPA PROGRAMA DE VECTORES",
"DGRVCS - DRPAP PROGRAMA DISCAPACIDAD");





// ---------------------------------------------2) crear una funcion que permita ejecutar el cambio dinamico---------------------------------------------

function DeptoTrabajos(){
    var Dependencia;
    //Se toma el vamor de la "cosa seleccionada"
    Dependencia = document.regForm.Dependencia[document.regForm.Dependencia.selectedIndex].value;
    //se chequea si la "cosa" esta definida
    if(Dependencia!=0){
        //selecionamos las cosas Correctas
        mis_opts=eval("DeptoTrabajo_" + Dependencia);
        //se calcula el numero de cosas
        num_opts=mis_opts.length;
        //marco el numero de opt en el select
        document.regForm.DeptoTrabajo.length = num_opts;
        //para cada opt del array, la pongo en el select
        for(i=0; i<num_opts; i++){
            document.regForm.DeptoTrabajo.options[i].value=mis_opts[i];
            document.regForm.DeptoTrabajo.options[i].text=mis_opts[i];
        }
        }else{
            //si no habia ninguna opt seleccionada, elimino las cosas del select
            document.regForm.opt.length = 1;
            //ponemos un guion en la unica opt que he dejado
            document.regForm.opt.options[0].value="-";
            document.regForm.opt.options[0].text="-";
        }
        //hacer un reset de las opts
        document.regForm.DeptoTrabajo.options[0].selected = true;
        
    }


//--------------------------------------------- 1) Definir Las Variables Educación Correspondintes---------------------------------------------


var NivelEdu_PRIMARIA = new Array ("-",
"PRIMERO",
"SEGUNDO",
"TERCERO",
"CUARTO",
"QUINTO",
"SEXTO");

var NivelEdu_SECUNDARIA = new Array ("-",
"PRIMERO BASICO",
"SEGUNDO BASICO",
"TERCERO BASICO");


var NivelEdu_DIVERSIFICADO = new Array ("-",
"BACH CON ORIENT.TECNICA OCUP. EN ELECTRICIDAD Y SOLDADURA",
"BACH EN CIENCIAS Y LETRAS POR MADUREZ CON ORIENT EN COMPU",
"BACH. EN CC Y LL CON ORIENT. OCUP. EN MECANICA AUTOMOTRIZ",
"BACH. EN CIENCIAS Y LETRAS CON ESPEC. EN MUSICA",
"BACH. INDUSTRIAL, PERITO EN ELECTRICIDAD Y MECANICA AUTOMOT.",
"BACH.IND.Y PER. EN ELECTRONICA,ELECTRICIDAD Y MEC.AUTOM.",
"BACHILLER EN CIENCIAS Y LETRAS CON ORIENTACION EN ELECTRICIDAD",
"BACHILLER INDUST.Y PERITO EN CONSTRUCC Y DIBUJO COMPUTARIZA",
"BACHILLER INDUSTRIAL CON ESPECIALIDAD EN BELLEZA",
"BACHILLER INDUSTRIAL Y PERITO EN CONSTRUCCION",
"BACHILLERATO BILINGUE EN CIENCIAS Y HUMANIDADES",
"BACHILLERATO EN ADMON INDUST. Y PERITO EN ALGUNA ESPEC.",
"BACHILLERATO EN ADMON. INDUSTRIAL Y P. DIBUJO CONSTRUCCION",
"BACHILLERATO EN CIENCAS Y LETRAS CON ORIENTACION EN HOTELERIA Y HOGAR",
"BACHILLERATO EN CIENCIAS DE LA COMUNICACION",
"BACHILLERATO EN CIENCIAS Y LETRAS",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN ARTES ESCENICAS",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN ARTES VISUALES",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN CIENCIAS BIOLOGICAS",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN COMPUTACION",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN DISEÑO GRAFICO",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN EDUCACION",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN EDUCACION DE ARTES PLASTICAS",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN EDUCACION DE PRODUCTIVIDAD Y DESARROLLO",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN EDUCACION FISICA",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN EDUCACION MUSICAL",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN FINANZAS Y ADMINISTRACION",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN GESTION DE OFICINAS",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN MECANICA AUTOMOTRIZ",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN MUSICA",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN PRODUCTIVIDAD Y EMPRENDIMIENTO",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN TEXTILES",
"BACHILLERATO EN CIENCIAS Y LETRAS CON ORIENTACION EN TURISMO",
"BACHILLERATO EN CIENCIAS Y LETRAS POR MADUREZ",
"BACHILLERATO EN CIENCIAS Y LETRAS Y SECRETARIADO BILINGUE",
"BACHILLERATO EN COMPUTACION",
"BACHILLERATO EN COMPUTACION CON ORIENTACION CIENTIFICA",
"BACHILLERATO EN COMPUTACION CON ORIENTACION COMERCIAL",
"BACHILLERATO EN CONSTRUCCION",
"BACHILLERATO EN CONSTRUCCION Y DIBUJO COMPUTARIZADO",
"BACHILLERATO EN COSMETOLOGIA",
"BACHILLERATO EN DIBUJO TECNICO Y CONSTRUCION CON COMPUTACION",
"BACHILLERATO EN DIBUJO TECNICO Y DE CONSTRUCCION",
"BACHILLERATO EN DISEÑO DE INTERIORES",
"BACHILLERATO EN DISEÑO DE MODAS",
"BACHILLERATO EN DISEÑO GRAFICO",
"BACHILLERATO EN FILOSOFIA Y TEOLOGIA",
"BACHILLERATO EN HOTELERIA Y HOGAR",
"BACHILLERATO EN MERCADOTECNIA",
"BACHILLERATO EN TELECOMUNICACIONES",
"BACHILLERATO EN TURISMO",
"BACHILLERATO EN TURISMO CON ORIENTACION EN COMPUTACION",
"BACHILLERATO EN TURISMO ECOLOGICO",
"BACHILLERATO EN TURISMO Y ADMINISTRACION EN/DE HOTELES",
"BACHILLERATO EN TURISMO Y HOTELERIA",
"BACHILLERATO INDUS Y PERITO EN COSTURA INDUSTRIAL",
"BACHILLERATO INDUSTRIAL",
"BACHILLERATO INDUSTRIAL CON UNA ESPECIALIDAD",
"BACHILLERATO INDUSTRIAL Y PERITO CON ESP. EN DISEÑO DE MODAS",
"BACHILLERATO INDUSTRIAL Y PERITO CON ESPECIALIDAD EN COMPU.",
"BACHILLERATO INDUSTRIAL Y PERITO EN DIBUJO COMPUTARIZADO",
"BACHILLERATO INDUSTRIAL Y PERITO EN DIBUJO DE ARQUITECTURA E INGENIERIA",
"BACHILLERATO INDUSTRIAL Y PERITO EN DIBUJO DE CONSTRUCCION",
"BACHILLERATO INDUSTRIAL Y PERITO EN DISEÑO GRAFICO",
"BACHILLERATO INDUSTRIAL Y PERITO EN ELECTRICIDAD",
"BACHILLERATO INDUSTRIAL Y PERITO EN ELECTRONICA",
"BACHILLERATO INDUSTRIAL Y PERITO EN ENDEREZADO Y PINTURA",
"BACHILLERATO INDUSTRIAL Y PERITO EN INFORMATICA Y COMPUTACION",
"BACHILLERATO INDUSTRIAL Y PERITO EN MECANICA AUTOMOTRIZ",
"BACHILLERATO INDUSTRIAL Y PERITO EN MECANICA DE MANTENIMIENTO INDUSTRIAL",
"BACHTO. EN CIENCIAS Y LETRAS Y SECRET. BILG.(INGLES-ESPAÑOL)",
"MAGISTERIO DE EDUC. PREPRIMARIA CON ORIENT. A LA DEMOCRACIA",
"MAGISTERIO DE EDUCACION INFANTIL BILINGUE INTERCULTURAL",
"MAGISTERIO DE EDUCACION INFANTIL INTERCULTURAL",
"MAGISTERIO DE EDUCACION PREPRIMARIA BILINGUE ESPAÑOL-INGLES",
"NORMAL PREPRIMARIA",
"NORMAL PREPRIMARIA BILINGUE",
"PERITO CONT. CON ESP. EN ADMON. DE PEQUEÑAS EMPRESAS AGRIC.",
"PERITO CONTADOR",
"PERITO CONTADOR BILINGUE (ESPAÑOL-INGLES)",
"PERITO CONTADOR CON ESPECIALIDAD EN COMPUTACION",
"PERITO CONTADOR CON ESPECIALIDAD EN COMPUTACION COMERCIAL",
"PERITO CONTADOR CON ORIENTACION ARTESANAL Y COMPUTACION",
"PERITO CONTADOR CON ORIENTACION COMERCIAL Y TURISMO",
"PERITO CONTADOR CON ORIENTACION EN ADMINISTRACION PORTUARIA",
"PERITO CONTADOR CON ORIENTACION EN COMPUTACION",
"PERITO CONTADOR CON ORIENTACION EN COMPUTACION COMERCIAL",
"PERITO CONTADOR EN COMPUTACION",
"PERITO EN ADMINISTRACION",
"PERITO EN ADMINISTRACION DE EMPRESAS",
"PERITO EN ADMINISTRACION DE EMPRESAS CON ORIENTACION EN COMP",
"PERITO EN ADMINISTRACION PUBLICA",
"PERITO EN ADMINISTRACION TURISTICA Y HOTELERA",
"PERITO EN ADMON. PUBLICA CON ORIENTACION EN COMPUTACION",
"PERITO EN CIEN DE LA COMUNI CON ESPECI EN TELE RADIO COMUNIC",
"PERITO EN CIENCIAS AMBIENTALES",
"PERITO EN CIENCIAS DE LA COMUNICACION",
"PERITO EN CIENCIAS TURISTICAS",
"PERITO EN COMPUTACION",
"PERITO EN COMPUTACION Y BACHILLERATO EN CIENCIAS Y LETRAS",
"PERITO EN DESARROLLO COMUNITARIO",
"PERITO EN DIBUJO DE CONSTRUCCION",
"PERITO EN DIBUJO TECNICO DE INGENIERIA Y ARQUITECTURA",
"PERITO EN DIBUJO TECNICO DE INGENIERIA Y ARQUITECTURA Y BACHILLERATO EN CIENCIAS Y LETRAS",
"PERITO EN ECOTURISMO",
"PERITO EN ELECTRICIDAD INDUSTRIAL",
"PERITO EN ELECTRONICA Y DISPOSITIVOS DIGITALES",
"PERITO EN GERENCIA ADMINISTRATIVA",
"PERITO EN INDUSTRIA DE ALIMENTOS",
"PERITO EN INFORMATICA",
"PERITO EN MECANICA AUTOMOTRIZ",
"PERITO EN MECANICA AUTOMOTRIZ Y BACHILLERATO EN CIENCIAS Y LETRAS",
"PERITO EN MECANICA GENERAL (TORNOS)",
"PERITO EN MERCADOTECNIA Y PUBLICIDAD",
"PERITO EN RELACIONES PUBLICAS EMPRESARIALES",
"PERITO EN TURISMO SUSTENTABLE",
"PERITO INDUSTRIAL",
"PERITO INDUSTRIAL CON ESPECIALIDAD EN DIBUJO TECNICO Y DE CONSTRUCCION",
"PERITO INDUSTRIAL CON ESPECIALIDAD EN MECANICA AUTOMOTRIZ",
"SECRET BILINGUE CON ORIENT EN IDIOMAS DIPLOMACIA Y REL INTER",
"SECRETARIADO BILINGUE / SECRETARIADO BILINGUE ESPAÑOL-INGLES",
"SECRETARIADO BILINGUE CON ESPECIALIDAD EN COMPUTACION",
"SECRETARIADO BILINGUE CON ORIENTA.TURISMO Y HOTELERIA",
"SECRETARIADO BILINGUE CON ORIENTACION EN COMPUTACION",
"SECRETARIADO BILINGUE ORIENTACION TURISMO-AGENCIA DE VIAJES",
"SECRETARIADO COMERCIAL",
"SECRETARIADO COMERCIAL CON ORIENTACION EN COMPUTACION",
"SECRETARIADO COMERCIAL Y OFICINISTA",
"SECRETARIADO EJECUTIVO",
"SECRETARIADO EJECUTIVO BILINGUE",
"SECRETARIADO EJECUTIVO BILINGUE CON ORIENT. EN MERC. Y PUB.",
"SECRETARIADO EJECUTIVO BILINGUE CON ORIENTA. COMP.COMERCIAL",
"SECRETARIADO EJECUTIVO EN COMPUTACION",
"SECRETARIADO EJECUTIVO EN ESPAÑOL",
"SECRETARIADO EJECUTIVO EN ESPAÑOL CON ORIENTACION EN COMPUT.",
"SECRETARIADO OFICINISTA CON ORIENTACION EN COMPUTACION",
"SECRETARIADO TRILINGUE CON ORIENT EN COMERCIO INTERNACIONAL",
"SECRETARIADO Y OFICINISTA",
"SECRETARIADO Y OFICINISTA CON ORIENTACION EN COMPUTACION",
"SECRETARIADO Y OFICINISTA CON ORIENTACION JURIDICA");

var NivelEdu_UNIVERSIDAD = new Array ("-",
"DIPLOMADO UNIVERSITARIO",
"TECNICO UNIVERSITARIO",
"LICENCIATURA",
"POSGRADO",
"MAESTRIA",
"DOCTORADO");



// ---------------------------------------------2) crear una funcion que permita ejecutar el cambio dinamico---------------------------------------------

function NivelEdus(){
    var NivelCademico;
    //Se toma el vamor de la "cosa seleccionada"
    NivelCademico = document.regForm.NivelCademico[document.regForm.NivelCademico.selectedIndex].value;
    //se chequea si la "cosa" esta definida
    if(NivelCademico!=0){
        //selecionamos las cosas Correctas
        mis_opts=eval("NivelEdu_" + NivelCademico);
        //se calcula el numero de cosas
        num_opts=mis_opts.length;
        //marco el numero de opt en el select
        document.regForm.NivelEdu.length = num_opts;
        //para cada opt del array, la pongo en el select
        for(i=0; i<num_opts; i++){
            document.regForm.NivelEdu.options[i].value=mis_opts[i];
            document.regForm.NivelEdu.options[i].text=mis_opts[i];
        }
        }else{
            //si no habia ninguna opt seleccionada, elimino las cosas del select
            document.regForm.opt.length = 1;
            //ponemos un guion en la unica opt que he dejado
            document.regForm.opt.options[0].value="-";
            document.regForm.opt.options[0].text="-";
        }
        //hacer un reset de las opts
        document.regForm.NivelEdu.options[0].selected = true;
        
    }

//--------------------------------------------- 1) Definir Las Variables Colegio Profesional Correspondintes---------------------------------------------


var Colegio_100 = new Array ("-",
"Colegio De Abogados Y Notarios De Guatemala",
"Colegio De Arquitectos De Guatemala",
"Colegio De Contadores Públicos Y Auditores De Guatemala",
"Colegio De Economistas, Contadores Públicos Y Auditores Y Administradores De Empresas",
"Colegio De Farmacéuticos Y Químicos De Guatemala",
"Colegio De Ingenieros Agrónomos De Guatemala",
"Colegio De Ingenieros De Guatemala",
"Colegio De Ingenieros Químicos De Guatemala",
"Colegio De Médicos Veterinarios Y Zootecnistas De Guatemala",
"Colegio De Médicos Y Cirujanos De Guatemala",
"Colegio De Psicólogos De Guatemala",
"Colegio Estomatológico De Guatemala",
"Colegio Profesional De Humanidades De Guatemala",
"Colegio Profesional De Enfermería De Guatemala"
);


// ---------------------------------------------2) crear una funcion que permita ejecutar el cambio dinamico---------------------------------------------

function cambiass(){
    var Grado;
    //Se toma el vamor de la "cosa seleccionada"
    Grado = document.formulario1.Grado[document.formulario1.Grado.selectedIndex].value;
    //se chequea si la "cosa" esta definida
    if(Grado!=0){
        //selecionamos las cosas Correctas
        mis_opts=eval("Colegio_" + Grado);
        //se calcula el numero de cosas
        num_opts=mis_opts.length;
        //marco el numero de opt en el select
        document.formulario1.Colegio.length = num_opts;
        //para cada opt del array, la pongo en el select
        for(i=0; i<num_opts; i++){
            document.formulario1.Colegio.options[i].value=mis_opts[i];
            document.formulario1.Colegio.options[i].text=mis_opts[i];
        }
        }else{
            //si no habia ninguna opt seleccionada, elimino las cosas del select
            document.formulario1.opt.length = 1;
            //ponemos un guion en la unica opt que he dejado
            document.formulario1.opt.options[0].value="-";
            document.formulario1.opt.options[0].text="-";
        }
        //hacer un reset de las opts
        document.formulario1.Colegio.options[0].selected = true;
        
    }

